import type { RunOptions } from "./RunOptions.ts";
import type { RunResult } from "@smithers/scheduler";
import type { WorkflowDriverOptions } from "./WorkflowDriverOptions.ts";
export declare class WorkflowDriver<Schema = unknown> {
    private readonly workflow;
    private readonly runtime;
    private readonly db?;
    private readonly configuredRunId?;
    private readonly rootDir?;
    private readonly workflowPath?;
    private readonly executeTask;
    private readonly onSchedulerWait?;
    private readonly onWait?;
    private readonly continueAsNewHandler?;
    private readonly createSession?;
    private readonly renderer;
    private session?;
    private activeRunId;
    private activeOptions?;
    private lastGraph?;
    private readonly outputTablesByNodeId;
    private baseOutputs;
    constructor(options: WorkflowDriverOptions<Schema>);
    run(options: RunOptions): Promise<RunResult>;
    private initializeSession;
    private renderAndSubmit;
    private executeTasks;
    private handleWait;
    private continueAsNew;
    private cancelRun;
    private runEffect;
}
