/**
 * Alchemy infrastructure-as-code for testing.smithers.sh, the @smthrs/testing docs site.
 * Generated by apps/docs/shared/gen-sites.mjs from apps/docs/shared/manifest.mjs. Edit the generator, then rerun it: node apps/docs/shared/gen-sites.mjs
 *
 * Deploy:   CLOUDFLARE_API_TOKEN=... ALCHEMY_PASSWORD=... pnpm -C apps/docs/testing deploy
 * Destroy:  pnpm -C apps/docs/testing destroy
 *
 * Optional env: TESTING_SITE_DOMAIN (preview deploys, default testing.smithers.sh),
 * CLOUDFLARE_SMITHERS_ZONE_ID (alchemy resolves the zone from the domain when
 * omitted).
 */
import { deployDocsSite } from "@smithers/docs-shared/alchemy-site"

export const site = await deployDocsSite({ slug: "testing" })
