/** @typedef {import("./CliAgentSurfaceTypes.ts").CliAgentSurfaceManifestEntry} CliAgentSurfaceManifestEntry */

/**
 * Compatibility contract for CLI-backed agents. Keep this list focused on the
 * command surface Smithers emits directly; user-supplied extraArgs remain an
 * escape hatch and are intentionally not modeled here.
 *
 * @type {readonly CliAgentSurfaceManifestEntry[]}
 */
export const CLI_AGENT_SURFACE_MANIFEST = [
  {
    id: "omp",
    displayName: "Oh My Pi",
    binary: "omp",
    packageExport: "OmpAgent",
    defaultOutputFormat: "text",
    docsUrls: [
      "https://github.com/can1357/oh-my-pi/blob/main/docs/sdk.md",
      "https://github.com/can1357/oh-my-pi/blob/main/docs/rpc.md",
    ],
    emittedFlags: [
      "--print",
      "--mode",
      "--model",
      "--provider",
      "--system-prompt",
      "--append-system-prompt",
      "--cwd",
      "--continue",
      "--resume",
      "--session-dir",
      "--no-session",
      "--tools",
      "--no-tools",
      "--extension",
      "--no-extensions",
      "--skills",
      "--no-skills",
      "--thinking",
      "--hide-thinking",
      "--print-thoughts",
      "--hook",
      "--max-time",
      "--auto-approve",
      "--approval-mode",
    ],
    supportedFlags: [
      "--print",
      "--mode",
      "--model",
      "--provider",
      "--api-key",
      "--system-prompt",
      "--append-system-prompt",
      "--cwd",
      "--continue",
      "--resume",
      "--session-dir",
      "--no-session",
      "--tools",
      "--no-tools",
      "--extension",
      "--no-extensions",
      "--skills",
      "--no-skills",
      "--thinking",
      "--hide-thinking",
      "--print-thoughts",
      "--hook",
      "--max-time",
      "--auto-approve",
      "--approval-mode",
    ],
    unsupportedFlags: [
      {
        flag: "--session",
        replacement: "--resume",
        reason: "OMP v17.0.5 uses valued --resume; --session is not public.",
      },
      { flag: "--skill", replacement: "--skills", reason: "OMP uses plural comma-separated --skills." },
      { flag: "--list-models", reason: "Not exposed by OMP v17.0.5." },
      { flag: "--prompt-template", reason: "Not exposed by OMP v17.0.5." },
      { flag: "--theme", reason: "Not exposed by OMP v17.0.5." },
    ],
    optionMappings: [
      { option: "apiKey", env: "provider-specific OMP API-key environment variable" },
      { option: "resumeSession", flag: "--resume" },
    ],
    resume: {
      kind: "flag",
      emitted: ["--continue", "--resume"],
      notes: "--resume takes precedence over --continue; --continue selects the recent session.",
    },
  },
  {
    id: "claude",
    displayName: "Claude Code",
    binary: "claude",
    packageExport: "ClaudeCodeAgent",
    defaultOutputFormat: "stream-json",
    docsUrls: ["https://docs.anthropic.com/en/docs/claude-code/cli-reference"],
    emittedFlags: [
      "--print",
      "--add-dir",
      "--agent",
      "--agents",
      "--allow-dangerously-skip-permissions",
      "--dangerously-skip-permissions",
      "--permission-mode",
      "--allowed-tools",
      "--append-system-prompt",
      "--betas",
      "--chrome",
      "--no-chrome",
      "--continue",
      "--debug",
      "--debug-file",
      "--disable-slash-commands",
      "--disallowed-tools",
      "--fallback-model",
      "--file",
      "--fork-session",
      "--from-pr",
      "--ide",
      "--include-partial-messages",
      "--input-format",
      "--json-schema",
      "--max-budget-usd",
      "--mcp-config",
      "--mcp-debug",
      "--model",
      "--no-session-persistence",
      "--output-format",
      "--plugin-dir",
      "--replay-user-messages",
      "--resume",
      "--session-id",
      "--setting-sources",
      "--settings",
      "--strict-mcp-config",
      "--system-prompt",
      "--tools",
      "--verbose",
    ],
    supportedFlags: [],
    unsupportedFlags: [],
    optionMappings: [
      { option: "configDir", env: "CLAUDE_CONFIG_DIR" },
      { option: "apiKey", env: "ANTHROPIC_API_KEY" },
      { option: "resume", flag: "--resume" },
    ],
    resume: {
      kind: "flag",
      emitted: ["--resume"],
      notes: "Native Claude session id.",
    },
  },
  {
    id: "codex",
    displayName: "Codex",
    binary: "codex",
    packageExport: "CodexAgent",
    defaultOutputFormat: "stream-json",
    docsUrls: ["https://developers.openai.com/codex/cli/reference"],
    emittedFlags: [
      "-c",
      "--enable",
      "--disable",
      "--image",
      "--model",
      "--oss",
      "--local-provider",
      "--sandbox",
      "--profile",
      "--full-auto",
      "--dangerously-bypass-approvals-and-sandbox",
      "--cd",
      "--skip-git-repo-check",
      "--add-dir",
      "--output-schema",
      "--color",
      "--json",
      "--output-last-message",
      "-",
    ],
    supportedFlags: [],
    unsupportedFlags: [],
    optionMappings: [
      { option: "configDir", env: "CODEX_HOME" },
      { option: "apiKey", env: "OPENAI_API_KEY" },
      { option: "resumeSession", notes: "Uses `codex exec resume <thread-id>`." },
    ],
    resume: {
      kind: "subcommand",
      emitted: ["exec", "resume"],
      notes: "Resume uses `codex exec resume <thread-id>` and omits output schema wiring.",
    },
  },
  {
    id: "cursor",
    displayName: "Cursor",
    binary: "cursor-agent",
    packageExport: "CursorAgent",
    defaultOutputFormat: "stream-json",
    docsUrls: ["https://cursor.com/docs/cli/using", "https://cursor.com/docs/cli/reference/output-format"],
    emittedFlags: [
      "--print",
      "--output-format",
      "--stream-partial-output",
      "--model",
      "--mode",
      "--force",
      "--auto-review",
      "--sandbox",
      "--approve-mcps",
      "--trust",
      "--workspace",
      "--plugin-dir",
      "--resume",
      "--continue",
      "--worktree",
      "--worktree-base",
      "--skip-worktree-setup",
      "--header",
      "--",
    ],
    supportedFlags: [],
    unsupportedFlags: [
      {
        flag: "--output-schema",
        reason: "Cursor CLI does not expose schema-constrained output; Smithers uses prompt-injection plus output validation.",
      },
    ],
    optionMappings: [
      { option: "apiKey", env: "CURSOR_API_KEY" },
      { option: "header", flag: "--header" },
      { option: "model", flag: "--model" },
      { option: "mode", flag: "--mode" },
      { option: "force", flag: "--force" },
      { option: "sandbox", flag: "--sandbox" },
      { option: "workspace", flag: "--workspace" },
      { option: "pluginDir", flag: "--plugin-dir" },
      { option: "resumeSession", flag: "--resume" },
      { option: "continueSession", flag: "--continue" },
      { option: "worktree", flag: "--worktree" },
    ],
    resume: {
      kind: "flag",
      emitted: ["--resume"],
      notes: "Smithers maps native session ids to `cursor-agent --resume <id>`.",
    },
  },
  {
    id: "antigravity",
    displayName: "Antigravity",
    binary: "agy",
    packageExport: "AntigravityAgent",
    defaultOutputFormat: "text",
    docsUrls: [
      "https://antigravity.google/docs/cli-best-practices",
      "https://antigravity.google/docs/cli-conversations",
      "https://antigravity.google/docs/cli-plugins",
    ],
    emittedFlags: [
      "-p",
      "--cwd",
      "--model",
      "--sandbox",
      "--dangerously-skip-permissions",
      "--allowed-mcp-server-names",
      "--allowed-tools",
      "--add-dir",
      "--continue",
      "--conversation",
      "--gemini_dir",
    ],
    supportedFlags: [
      "-p",
      "--cwd",
      "--model",
      "--sandbox",
      "--dangerously-skip-permissions",
      "--allowed-mcp-server-names",
      "--allowed-tools",
      "--add-dir",
      "--continue",
      "--conversation",
      "-c",
      "--gemini_dir",
    ],
    unsupportedFlags: [
      {
        flag: "--output-format",
        reason: "Current agy builds do not expose an output-format flag; Smithers treats stdout as text.",
      },
      {
        flag: "--include-directories",
        replacement: "--add-dir",
        reason: "The directory allow-list flag was renamed.",
      },
      {
        flag: "--resume",
        replacement: "--conversation",
        reason: "Conversation resume now uses --conversation or -c.",
      },
      {
        flag: "--list-sessions",
        replacement: "/resume",
        reason: "Conversation listing is an interactive slash command.",
      },
      {
        flag: "--screen-reader",
        reason: "Current agy builds do not expose this flag.",
      },
      {
        flag: "--debug",
        reason: "Current agy builds do not expose this flag.",
      },
      {
        flag: "--extensions",
        replacement: "agy plugin",
        reason: "Extensions were renamed to plugins and are managed by the plugin subcommand.",
      },
      {
        flag: "--list-extensions",
        replacement: "agy plugin list",
        reason: "Plugins are listed through the plugin subcommand.",
      },
      {
        flag: "--delete-session",
        replacement: "/resume",
        reason: "Conversation management is handled inside the CLI session.",
      },
      {
        flag: "--prompt",
        replacement: "-p",
        reason: "Non-interactive prompts use -p.",
      },
    ],
    optionMappings: [
      { option: "includeDirectories", flag: "--add-dir" },
      { option: "resume", flag: "--conversation" },
      { option: "conversation", flag: "--conversation" },
      { option: "continue", flag: "--continue" },
      { option: "configDir", flag: "--gemini_dir", env: "GEMINI_DIR" },
      { option: "geminiDir", flag: "--gemini_dir", env: "GEMINI_DIR" },
      { option: "apiKey", env: "GEMINI_API_KEY" },
    ],
    resume: {
      kind: "flag",
      emitted: ["--conversation"],
      notes: "Smithers maps native session ids to `agy --conversation <id>`.",
    },
  },
  {
    id: "pi",
    displayName: "Pi",
    binary: "pi",
    packageExport: "PiAgent",
    defaultOutputFormat: "text",
    docsUrls: ["https://github.com/withpi/pi"],
    emittedFlags: [
      "--print",
      "--mode",
      "--provider",
      "--model",
      "--api-key",
      "--system-prompt",
      "--append-system-prompt",
      "--continue",
      "--resume",
      "--session",
      "--session-dir",
      "--no-session",
      "--models",
      "--list-models",
      "--export",
      "--tools",
      "--no-tools",
      "--extension",
      "--no-extensions",
      "--skill",
      "--no-skills",
      "--prompt-template",
      "--no-prompt-templates",
      "--theme",
      "--no-themes",
      "--thinking",
      "--verbose",
    ],
    supportedFlags: [],
    unsupportedFlags: [],
    optionMappings: [
      { option: "resumeSession", flag: "--session" },
      { option: "apiKey", flag: "--api-key" },
    ],
    resume: {
      kind: "flag",
      emitted: ["--session"],
      notes: "Per-call resumeSession maps to a Pi session id.",
    },
  },
  {
    id: "kimi",
    displayName: "Kimi",
    binary: "kimi",
    packageExport: "KimiAgent",
    defaultOutputFormat: "text",
    docsUrls: ["https://github.com/MoonshotAI/kimi-cli"],
    emittedFlags: [
      "--print",
      "--output-format",
      "--final-message-only",
      "--work-dir",
      "--session",
      "--continue",
      "--model",
      "--thinking",
      "--no-thinking",
      "--quiet",
      "--agent",
      "--agent-file",
      "--mcp-config-file",
      "--mcp-config",
      "--skills-dir",
      "--max-steps-per-turn",
      "--max-retries-per-step",
      "--max-ralph-iterations",
      "--verbose",
      "--debug",
      "--prompt",
    ],
    supportedFlags: [],
    unsupportedFlags: [],
    optionMappings: [
      { option: "configDir", env: "KIMI_SHARE_DIR" },
      { option: "resumeSession", flag: "--session" },
    ],
    resume: {
      kind: "flag",
      emitted: ["--session"],
      notes: "Smithers persists the Kimi session id and reuses it through --session.",
    },
  },
  {
    id: "forge",
    displayName: "Forge",
    binary: "forge",
    packageExport: "ForgeAgent",
    defaultOutputFormat: "text",
    docsUrls: ["https://forgecode.dev/docs/cli"],
    emittedFlags: [
      "--model",
      "--provider",
      "--agent",
      "--conversation-id",
      "--sandbox",
      "--restricted",
      "--verbose",
      "--workflow",
      "--event",
      "--conversation",
      "-C",
      "--prompt",
    ],
    supportedFlags: [],
    unsupportedFlags: [],
    optionMappings: [
      { option: "conversationId", flag: "--conversation-id" },
      { option: "resumeSession", flag: "--conversation-id" },
    ],
    resume: {
      kind: "flag",
      emitted: ["--conversation-id"],
      notes: "Smithers persists Forge conversation ids.",
    },
  },
  {
    id: "hermes",
    displayName: "Hermes",
    binary: "hermes",
    packageExport: "HermesCliAgent",
    defaultOutputFormat: "text",
    docsUrls: ["https://hermes-agent.nousresearch.com/docs/reference/cli-commands"],
    emittedFlags: ["--model", "--provider", "-c", "-r", "-z"],
    supportedFlags: [],
    unsupportedFlags: [],
    optionMappings: [
      { option: "provider", flag: "--provider" },
      { option: "continueSession", flag: "-c" },
      { option: "resumeSession", flag: "-r" },
    ],
    resume: {
      kind: "flag",
      emitted: ["-r", "-c"],
      notes:
        "`-r <session>` resumes a specific Hermes session id; `-c [name]` continues the most recent or a named session.",
    },
  },
  {
    id: "amp",
    displayName: "Amp",
    binary: "amp",
    packageExport: "AmpAgent",
    defaultOutputFormat: "text",
    docsUrls: ["https://ampcode.com/manual"],
    emittedFlags: [
      "--dangerously-allow-all",
      "--model",
      "--visibility",
      "--mcp-config",
      "--settings-file",
      "--log-level",
      "--log-file",
      "--no-ide",
      "--no-jetbrains",
      "--no-color",
      "--archive",
      "--execute",
      "--stream-json",
    ],
    supportedFlags: [],
    unsupportedFlags: [],
    optionMappings: [{ option: "dangerouslyAllowAll", flag: "--dangerously-allow-all" }],
    resume: {
      kind: "subcommand",
      emitted: ["threads", "continue"],
      notes: "Native hijack uses `amp threads continue`; headless generate starts a managed thread.",
    },
  },
  {
    id: "vibe",
    displayName: "Vibe",
    binary: "vibe",
    packageExport: "VibeAgent",
    defaultOutputFormat: "stream-json",
    docsUrls: ["https://docs.mistral.ai/mistral-vibe/terminal"],
    emittedFlags: [
      "--agent",
      "--max-turns",
      "--max-price",
      "--max-tokens",
      "--enabled-tools",
      "--trust",
      "--output",
      "--workdir",
      "--prompt",
      "--resume",
      "-c",
    ],
    supportedFlags: [],
    unsupportedFlags: [],
    optionMappings: [{ option: "resumeSession", flag: "--resume" }],
    resume: {
      kind: "flag",
      emitted: ["--resume"],
      notes: "Maps to vibe --resume <session-id> for headless continuation.",
    },
  },
  {
    id: "opencode",
    displayName: "OpenCode",
    binary: "opencode",
    packageExport: "OpenCodeAgent",
    defaultOutputFormat: "stream-json",
    docsUrls: ["https://opencode.ai/docs/cli"],
    emittedFlags: ["run", "-m", "--dir", "--format", "--agent", "-f", "--continue", "--session", "--variant", "--"],
    supportedFlags: [],
    unsupportedFlags: [],
    optionMappings: [
      { option: "sessionId", flag: "--session" },
      { option: "resumeSession", flag: "--session" },
      { option: "yolo", env: "OPENCODE_PERMISSION" },
    ],
    resume: {
      kind: "flag",
      emitted: ["--session"],
      notes: "OpenCode receives a session id through --session for headless continuation.",
    },
  },
  {
    id: "openclaw",
    displayName: "OpenClaw",
    binary: "openclaw",
    packageExport: "OpenClawAgent",
    defaultOutputFormat: "json",
    docsUrls: ["https://docs.openclaw.ai/cli/agent"],
    emittedFlags: ["agent", "--agent", "--session-id", "--continue", "--workspace", "--json", "--message"],
    supportedFlags: [],
    unsupportedFlags: [],
    optionMappings: [
      { option: "agent", flag: "--agent" },
      { option: "sessionId", flag: "--session-id" },
      { option: "session", flag: "--session-id" },
      { option: "resumeSession", flag: "--session-id" },
      { option: "workspace", flag: "--workspace" },
    ],
    resume: {
      kind: "flag",
      emitted: ["--session-id"],
      notes: "Smithers sends prompts through `openclaw agent --session-id <id>` when a session id is supplied.",
    },
  },
  {
    id: "pool",
    displayName: "Pool",
    binary: "pool",
    packageExport: "PoolAgent",
    defaultOutputFormat: "stream-json",
    docsUrls: ["https://poolside.ai/docs"],
    emittedFlags: ["exec", "-o", "-d", "--unsafe-auto-allow", "-m", "-a", "-r", "--continue", "--sandbox", "-p"],
    supportedFlags: [],
    unsupportedFlags: [],
    optionMappings: [
      { option: "agentName", flag: "-a" },
      { option: "resumeSession", flag: "-r" },
      { option: "resume", flag: "-r" },
      { option: "continue", flag: "--continue" },
    ],
    resume: {
      kind: "flag",
      emitted: ["-r"],
      notes: "Smithers persists the Pool session id and reuses it through -r for headless continuation.",
    },
  },
];

/**
 * @param {string} id
 * @returns {CliAgentSurfaceManifestEntry | undefined}
 */
export function getCliAgentSurfaceManifestEntry(id) {
  return CLI_AGENT_SURFACE_MANIFEST.find((entry) => entry.id === id);
}

/**
 * @returns {CliAgentSurfaceManifestEntry[]}
 */
export function listCliAgentSurfaceManifests() {
  return [...CLI_AGENT_SURFACE_MANIFEST];
}
