import { captureSnapshot as captureSnapshotEffect } from "./captureSnapshotEffect";
import { loadLatestSnapshot as loadLatestSnapshotEffect, loadSnapshot as loadSnapshotEffect } from "./loadSnapshotEffect";
import { listSnapshots as listSnapshotsEffect } from "./listSnapshotsEffect";
export { parseSnapshot } from "./parseSnapshot";
export { captureSnapshotEffect, listSnapshotsEffect, loadLatestSnapshotEffect, loadSnapshotEffect, };
export type { Snapshot } from "./Snapshot";
export type { SnapshotData } from "./SnapshotData";
export declare function captureSnapshot(...args: Parameters<typeof captureSnapshotEffect>): Promise<import("./Snapshot").Snapshot>;
export declare function loadSnapshot(...args: Parameters<typeof loadSnapshotEffect>): Promise<import("./Snapshot").Snapshot | undefined>;
export declare function loadLatestSnapshot(...args: Parameters<typeof loadLatestSnapshotEffect>): Promise<import("./Snapshot").Snapshot | undefined>;
export declare function listSnapshots(...args: Parameters<typeof listSnapshotsEffect>): Promise<Pick<import("./Snapshot").Snapshot, "runId" | "createdAtMs" | "frameNo" | "vcsPointer" | "contentHash">[]>;
