#!/usr/bin/env node
/** Generates the package-local README and JSDoc export index. */
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { Manifest } from "../docs/Manifest.ts"

const check = process.argv.includes("--check")
const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const repoRoot = join(packageRoot, "..", "..")
const readPackage = (path) => readFileSync(join(packageRoot, path), "utf8")
const readRepo = (path) => readFileSync(join(repoRoot, path), "utf8")

const ungutter = (block) => block.split("\n").map((line) => line.replace(/^\s*\* ?/, "")).join("\n")
const description = (body) => {
  const lines = []
  for (const line of body.split("\n")) {
    if (/^@\w+/.test(line)) break
    lines.push(line)
  }
  return lines.join("\n").trim()
}
const firstSentence = (value) => {
  const flat = value.split("\n\n")[0].split("\n").join(" ").replaceAll(/\s+/g, " ").trim()
  return (/^[\s\S]*?\.(?=\s|$)/.exec(flat)?.[0] ?? flat).trim()
}
const documented = /\/\*\*((?:[^*]|\*(?!\/))*)\*\/\s*\n(?:\/\/[^\n]*\n)*export (?:declare )?(const|type|interface|class|function) (\w+)/g
const exportsOf = (source) => {
  const entries = []
  for (let match = documented.exec(source); match !== null; match = documented.exec(source)) {
    const body = ungutter(match[1])
    const category = /@category (\S+)/.exec(body)?.[1]
    if (category === undefined) continue
    entries.push({
      category,
      kind: match[2],
      name: match[3],
      since: /@since (\S+)/.exec(body)?.[1],
      summary: firstSentence(description(body))
    })
  }
  return entries
}

const markdownTable = (headings, rows) => {
  const allRows = [headings, ...rows]
  const widths = headings.map((_, index) =>
    Math.max(3, ...allRows.map((row) => row[index].length))
  )
  const line = (row) => `| ${row.map((cell, index) => cell.padEnd(widths[index])).join(" | ")} |`
  return [line(headings), line(widths.map((width) => "-".repeat(width))), ...rows.map(line)].join("\n")
}

const failures = []
const manifest = JSON.parse(readPackage("package.json"))
if (manifest.name !== Manifest.name) failures.push("Manifest.ts and package.json names differ")
if (manifest.private !== true) failures.push("@smthrs/fs must remain private at rc.0")

const barrel = readPackage("src/index.ts")
const barrelNamespaces = [...barrel.matchAll(/export \* as (\w+) from/g)].map((match) => match[1])
const declaredNamespaces = Manifest.modules.map((entry) => entry.namespace)
if (JSON.stringify(barrelNamespaces) !== JSON.stringify(declaredNamespaces)) {
  failures.push("Manifest.ts modules differ from the root barrel")
}

let total = 0
const sections = Manifest.modules.map((module) => {
  const entries = exportsOf(readPackage(module.source))
  total += entries.length
  if (entries.length === 0) failures.push(`${module.source}: no export carries @category`)
  for (const entry of entries) {
    if (entry.since === undefined) failures.push(`${module.source}: ${entry.name} has no @since`)
    if (entry.summary === "") failures.push(`${module.source}: ${entry.name} has no summary`)
  }
  const rows = entries.map((entry) => [
    `\`${entry.name}\``,
    entry.kind,
    entry.category,
    entry.summary
  ])
  return `## \`${module.namespace}\`\n\n\`${module.specifier}\`\n\n${
    markdownTable(["Export", "Kind", "Category", "Summary"], rows)
  }`
}).join("\n\n")

const exportIndex = `<!-- Generated by \`node ${Manifest.generator}\`. Edit exported JSDoc, never this file. -->

# Exported members

${Manifest.modules.length} namespaces and ${total} documented members. An export without an
\`@category\` tag is not part of this generated contract.

${sections}
`
const readme = `<!-- Generated by \`node ${Manifest.generator}\`. Edit docs/README.md, never this file. -->

${readPackage(Manifest.readme.source).trim()}
`

for (const fragment of Manifest.fragments) {
  try {
    readRepo(fragment)
  } catch {
    failures.push(`${fragment}: missing package-owned documentation`)
  }
}

const outputs = new Map([
  [Manifest.readme.target, readme],
  [Manifest.exports.target, exportIndex]
])
for (const [path, content] of outputs) {
  if (content.includes("—")) failures.push(`${path}: generated content contains an em-dash`)
  const absolute = join(repoRoot, path)
  let current
  try {
    current = readFileSync(absolute, "utf8")
  } catch {}
  if (current === content) continue
  if (check) failures.push(`${path}: drifted; run node ${Manifest.generator}`)
  else writeFileSync(absolute, content)
}

if (failures.length > 0) {
  for (const failure of failures) console.error(`x ${failure}`)
  process.exit(1)
}
console.log(check ? "fs package documentation is current" : "fs package documentation regenerated")
