#!/usr/bin/env node
/** Projects package-owned Sandbox documentation into the repository site. */
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { Package } from "../Package.ts"

const check = process.argv.includes("--check")
const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const repoRoot = join(packageRoot, "..", "..")
const read = (path) => readFileSync(path, "utf8")

const ungutter = (block) => block.split("\n").map((line) => line.replace(/^\s*\* ?/, "")).join("\n")

const description = (body) => {
  const lines = []
  for (const line of body.split("\n")) {
    if (/^@\w+/.test(line)) break
    lines.push(line)
  }
  return lines.join("\n").trim()
}

const delink = (value) => value.replace(/\{@link\s+([^}]+)\}/g, "`$1`")

const paragraphs = (value) => {
  const blocks = []
  let current = []
  for (const line of value.split("\n")) {
    if (line.trim() === "") {
      if (current.length > 0) blocks.push(current.join(" "))
      current = []
    } else current.push(line.trim())
  }
  if (current.length > 0) blocks.push(current.join(" "))
  return blocks.join("\n\n")
}

const firstSentence = (value) => {
  const flat = delink(value).split("\n\n")[0].split("\n").join(" ")
  return (/^[\s\S]*?\.(?=\s|$)/.exec(flat)?.[0] ?? flat).trim()
}

/** A table cell cannot carry a pipe, and a summary is one line. */
const cell = (value) => value.replaceAll("|", "\\|").replaceAll("\n", " ")

const moduleDoc = (source) => {
  const match = /\/\*\*([\s\S]*?)\*\//.exec(source)
  if (match === null) throw new Error("sandbox docs: no module JSDoc block")
  return delink(description(ungutter(match[1])))
}

/**
 * Every export in one module that carries an `@category`. Undocumented
 * exports are invisible to this page on purpose: the category is the author
 * saying the export is part of the published surface.
 */
const exportedDocs = (source) => {
  const entries = []
  const pattern = /\/\*\*((?:[^*]|\*(?!\/))*)\*\/\s*\nexport (type|const|class|interface) (\w+)/g
  for (let match = pattern.exec(source); match !== null; match = pattern.exec(source)) {
    const body = ungutter(match[1])
    const category = /@category (\S+)/.exec(body)?.[1]
    if (category === undefined) continue
    entries.push({
      name: match[3],
      declaration: match[2],
      category,
      summary: firstSentence(description(body))
    })
  }
  return entries
}

const manifest = JSON.parse(read(join(packageRoot, "package.json")))
if (manifest.name !== Package.name) throw new Error("sandbox docs: Package.ts and package.json names differ")

// The barrel re-exports one namespace per module directory, each introduced by
// its own one-line comment, so the walk is namespace first and export second.
const barrel = read(join(packageRoot, "src", "index.ts"))
const namespaces = [
  ...barrel.matchAll(/\/\*\*((?:[^*]|\*(?!\/))*)\*\/\s*\nexport \* as (\w+) from "\.\/(\w+)\/index\.ts"/g)
].map((match) => ({
  blurb: delink(description(ungutter(match[1]))).replaceAll("\n", " ").trim(),
  name: match[2],
  directory: match[3]
}))
if (namespaces.length === 0) throw new Error("sandbox docs: no namespace re-exports found in the barrel")

for (const namespace of namespaces) {
  const index = read(join(packageRoot, "src", namespace.directory, "index.ts"))
  const modules = [...index.matchAll(/export \* from "\.\/(\w+)\.ts"/g)].map((match) => match[1])
  namespace.exports = modules.flatMap((module) =>
    exportedDocs(read(join(packageRoot, "src", namespace.directory, `${module}.ts`)))
  )
  if (namespace.exports.length === 0) {
    throw new Error(`sandbox docs: ${namespace.name} documents no exports`)
  }
}

const exportTable = (namespace) =>
  [
    `### ${namespace.name}`,
    "",
    namespace.blurb,
    "",
    "| Export | Kind | Summary |",
    "| --- | --- | --- |",
    ...namespace.exports.map((entry) => `| \`${entry.name}\` (${entry.declaration}) | ${entry.category} | ${
      cell(entry.summary)
    } |`)
  ].join("\n")

const namespaceTable = [
  "| Namespace | Import | What it is |",
  "| --- | --- | --- |",
  ...namespaces.map((namespace) =>
    `| \`${namespace.name}\` | \`@smthrs/sandbox/${namespace.name}\` | ${cell(namespace.blurb)} |`
  )
].join("\n")

const apiPage = `---
description: "${manifest.description}."
---

{/* Generated by \`node packages/sandbox/scripts/docs.mjs\` from packages/sandbox. Edit package sources, never this file. */}

# @smthrs/sandbox

${paragraphs(moduleDoc(barrel))}

## Namespaces

${namespaceTable}

${read(join(packageRoot, Package.api.source)).trim()}

## Limits

${read(join(packageRoot, "docs", "limits.md")).trim()}

## Exports

Every export below carries an \`@category\` in its own source. The summary is
that export's first documented sentence.

${namespaces.map(exportTable).join("\n\n")}
`

const regionStart = (name) => `{/* generated:${name} start */}`
const regionEnd = (name) => `{/* generated:${name} end */}`
const replaceRegion = (source, name, body) => {
  const start = source.indexOf(regionStart(name))
  const end = source.indexOf(regionEnd(name))
  if (start < 0 || end < 0 || end < start) throw new Error(`sandbox docs: region ${name} is missing`)
  return `${source.slice(0, start)}${regionStart(name)}\n\n${body.trim()}\n\n${source.slice(end)}`
}

const outputs = new Map([[Package.api.target, apiPage]])
for (const snippet of Package.snippets) {
  const current = outputs.get(snippet.target) ?? read(join(repoRoot, snippet.target))
  outputs.set(snippet.target, replaceRegion(current, snippet.region, read(join(packageRoot, snippet.source))))
}

const failures = []

// The README's namespace table is a fragment rather than generated text,
// because it lives inside this package's dprint scope and a formatter that
// pads a table and a generator that does not would rewrite each other forever.
// It is still not hand-owned: it has to name exactly the namespaces the barrel
// exports, which is the drift the four-of-fifteen table used to be.
{
  const fragment = read(join(packageRoot, "docs", "namespaces.md"))
  const listed = [...fragment.matchAll(/^\|\s*`(\w+)`\s*\|/gm)].map((match) => match[1])
  const expected = namespaces.map((namespace) => namespace.name)
  if (listed.join(",") !== expected.join(",")) {
    failures.push(
      `packages/sandbox/docs/namespaces.md: lists ${listed.join(", ")}; the barrel exports ${expected.join(", ")}`
    )
  }
}

for (const path of Package.references) {
  const content = read(join(repoRoot, path))
  if (!content.includes(Package.name) || !content.includes("/api/sandbox")) {
    failures.push(`${path}: must reference ${Package.name} and /api/sandbox`)
  }
}
for (const [path, content] of outputs) {
  if (content.includes("—")) failures.push(`${path}: generated content contains an em-dash`)
}

let drifted = false
for (const [path, content] of outputs) {
  const absolute = join(repoRoot, path)
  if (read(absolute) === content) continue
  drifted = true
  if (check) failures.push(`${path}: drifted; run node packages/sandbox/scripts/docs.mjs`)
  else {
    writeFileSync(absolute, content)
    console.log(`wrote ${path}`)
  }
}

if (failures.length > 0) {
  for (const failure of failures) console.error(`✗ ${failure}`)
  process.exit(1)
}

console.log(
  check
    ? "✓ the sandbox package documentation is current"
    : drifted
    ? "✓ sandbox package documentation regenerated"
    : "✓ sandbox package documentation already current"
)
