// smithers-source: generated (placeholder — regenerated by bun .smithers/lib/ddd/build.ts)
export const workflowSourcePath: string = ".smithers/workflows/docs-driven-development.tsx";
export const workflowSource: string =
  "// Placeholder workflow source. Run `bun .smithers/lib/ddd/build.ts` to embed the real workflow .tsx source.\n";
