// Generated by .smithers/lib/ddd/generateUiModules.ts - do not edit.
// One ticket per open gap (features.json broken/partial/missing* + each missing[] item).
export const ticketsBacklog: { path: string; kind: string; status: string; updatedAtMs: number; featureId: string; featureTitle: string; content: string }[] = [
  {
    "path": "tickets/cli--01-cli-read-commands-have-historically-been-sqlite-coupled-keep.md",
    "kind": "e2e",
    "status": "todo",
    "updatedAtMs": 0,
    "featureId": "cli",
    "featureTitle": "smithers CLI",
    "content": "# CLI read commands have historically been sqlite-coupled; keep pglite/postgres parity covered by e2e for every read command\n\nFeature: smithers CLI (cli)\nStatus: todo · Kind: e2e · Feature status: partial\n\n## Gap\n\nCLI read commands have historically been sqlite-coupled; keep pglite/postgres parity covered by e2e for every read command\n"
  },
  {
    "path": "tickets/agent-adapters--01-kimi-auth-setup-error-should-fail-over-to-the-next-pool-agen.md",
    "kind": "fix",
    "status": "todo",
    "updatedAtMs": 0,
    "featureId": "agent-adapters",
    "featureTitle": "Agent adapters",
    "content": "# Kimi auth-setup error should fail over to the next pool agent instead of failing the run\n\nFeature: Agent adapters (agent-adapters)\nStatus: todo · Kind: fix · Feature status: partial\n\n## Gap\n\nKimi auth-setup error should fail over to the next pool agent instead of failing the run\n"
  },
  {
    "path": "tickets/gateway-server--01-serverless-resume-cron-tick-and-run-lease-claims-are-new-add.md",
    "kind": "e2e",
    "status": "todo",
    "updatedAtMs": 0,
    "featureId": "gateway-server",
    "featureTitle": "Gateway and server",
    "content": "# Serverless resume/cron tick and run-lease claims are new; add end-to-end proof beyond unit tests\n\nFeature: Gateway and server (gateway-server)\nStatus: todo · Kind: e2e · Feature status: partial\n\n## Gap\n\nServerless resume/cron tick and run-lease claims are new; add end-to-end proof beyond unit tests\n"
  },
  {
    "path": "tickets/time-travel-replay--01-durability-snapshots-phase-2-restore-in-test-only-tool-conte.md",
    "kind": "e2e",
    "status": "todo",
    "updatedAtMs": 0,
    "featureId": "time-travel-replay",
    "featureTitle": "Time travel and replay",
    "content": "# Durability snapshots phase 2 (restore in test-only tool context) is not finished\n\nFeature: Time travel and replay (time-travel-replay)\nStatus: todo · Kind: e2e · Feature status: partial\n\n## Gap\n\nDurability snapshots phase 2 (restore in test-only tool context) is not finished\n"
  },
  {
    "path": "tickets/crash-recovery-resume--01-crash-recovery-workflow-.smithers-workflows-crash-recovery.t.md",
    "kind": "fix",
    "status": "todo",
    "updatedAtMs": 0,
    "featureId": "crash-recovery-resume",
    "featureTitle": "Crash recovery and resume",
    "content": "# Crash-recovery workflow (.smithers/workflows/crash-recovery.tsx) is new and unverified end to end\n\nFeature: Crash recovery and resume (crash-recovery-resume)\nStatus: todo · Kind: fix · Feature status: partial\n\n## Gap\n\nCrash-recovery workflow (.smithers/workflows/crash-recovery.tsx) is new and unverified end to end\n"
  },
  {
    "path": "tickets/sandbox-vcs--01-jj-bookmark-conflicts-from-git-commits-in-chained-worktrees-.md",
    "kind": "issue",
    "status": "todo",
    "updatedAtMs": 0,
    "featureId": "sandbox-vcs",
    "featureTitle": "Sandboxes, worktrees, and VCS",
    "content": "# jj bookmark conflicts from git commits in chained worktrees need an automated repair path\n\nFeature: Sandboxes, worktrees, and VCS (sandbox-vcs)\nStatus: todo · Kind: issue · Feature status: partial\n\n## Gap\n\njj bookmark conflicts from git commits in chained worktrees need an automated repair path\n"
  },
  {
    "path": "tickets/open-code-review--01-cloud-deployment-blocked-on-a-funded-anthropic_api_key.md",
    "kind": "issue",
    "status": "todo",
    "updatedAtMs": 0,
    "featureId": "open-code-review",
    "featureTitle": "Open code review",
    "content": "# Cloud deployment blocked on a funded ANTHROPIC_API_KEY\n\nFeature: Open code review (open-code-review)\nStatus: todo · Kind: issue · Feature status: partial\n\n## Gap\n\nCloud deployment blocked on a funded ANTHROPIC_API_KEY\n"
  },
  {
    "path": "tickets/memory--01-no-end-to-end-proof-that-seeded-workflows-read-and-write-mem.md",
    "kind": "e2e",
    "status": "todo",
    "updatedAtMs": 0,
    "featureId": "memory",
    "featureTitle": "Agent memory",
    "content": "# No end-to-end proof that seeded workflows read and write memory across separate runs\n\nFeature: Agent memory (memory)\nStatus: todo · Kind: e2e · Feature status: partial\n\n## Gap\n\nNo end-to-end proof that seeded workflows read and write memory across separate runs\n"
  },
  {
    "path": "tickets/observability--01-otlp-exporter-is-not-installed-in-the-reference-deployments-.md",
    "kind": "issue",
    "status": "todo",
    "updatedAtMs": 0,
    "featureId": "observability",
    "featureTitle": "Observability",
    "content": "# OTLP exporter is not installed in the reference deployments; prove a real export path\n\nFeature: Observability (observability)\nStatus: todo · Kind: issue · Feature status: partial\n\n## Gap\n\nOTLP exporter is not installed in the reference deployments; prove a real export path\n"
  },
  {
    "path": "tickets/docs-driven-development--01-mermaid-diagram-preview-in-the-docs-tab.md",
    "kind": "issue",
    "status": "todo",
    "updatedAtMs": 0,
    "featureId": "docs-driven-development",
    "featureTitle": "Docs driven development",
    "content": "# Mermaid diagram preview in the Docs tab\n\nFeature: Docs driven development (docs-driven-development)\nStatus: todo · Kind: issue · Feature status: partial\n\n## Gap\n\nMermaid diagram preview in the Docs tab\n"
  },
  {
    "path": "tickets/docs-driven-development--02-image-upload-target-crepe-imageblock-needs-an-asset-server-v.md",
    "kind": "issue",
    "status": "todo",
    "updatedAtMs": 0,
    "featureId": "docs-driven-development",
    "featureTitle": "Docs driven development",
    "content": "# Image upload target: Crepe ImageBlock needs an asset server; v1 wires ?assetBaseUrl passthrough but ships no asset server (uploads disabled when absent)\n\nFeature: Docs driven development (docs-driven-development)\nStatus: todo · Kind: issue · Feature status: partial\n\n## Gap\n\nImage upload target: Crepe ImageBlock needs an asset server; v1 wires ?assetBaseUrl passthrough but ships no asset server (uploads disabled when absent)\n"
  },
  {
    "path": "tickets/docs-driven-development--03-only-work-1-single-agent-wave-matching-multi-s-sqlite-fanout.md",
    "kind": "issue",
    "status": "todo",
    "updatedAtMs": 0,
    "featureId": "docs-driven-development",
    "featureTitle": "Docs driven development",
    "content": "# Only work:1 single-agent wave, matching multi's SQLite-fanout caution\n\nFeature: Docs driven development (docs-driven-development)\nStatus: todo · Kind: issue · Feature status: partial\n\n## Gap\n\nOnly work:1 single-agent wave, matching multi's SQLite-fanout caution\n"
  }
];
