// smithers-source: generated (placeholder — regenerated by bun .smithers/lib/ddd/build.ts)
export const docsContent: { path: string; title: string; content: string }[] = [
  {
    path: "overview.md",
    title: "Overview",
    content: "# Overview\n\nPlaceholder narrative doc. Run `bun .smithers/lib/ddd/build.ts` to regenerate the real content modules from `.smithers/spec/content`.\n",
  },
];
export type DocsContentEntry = (typeof docsContent)[number];
