// smithers-source: generated (placeholder — regenerated by bun .smithers/lib/ddd/build.ts)
export const ticketsBacklog: { path: string; kind: string; status: string; updatedAtMs: number; content: string }[] = [
  {
    path: "backlog--placeholder",
    kind: "ticket",
    status: "todo",
    updatedAtMs: 0,
    content: "# Placeholder backlog ticket\n\nRun `bun .smithers/lib/ddd/build.ts` to derive the real backlog from features.json.\n",
  },
];
