/**
 * Alchemy infrastructure-as-code for artifacts.smithers.sh, the @smthrs/artifacts docs site.
 * Generated by apps/docs/shared/gen-sites.mjs from apps/docs/shared/manifest.mjs. Edit the generator, then rerun it: node apps/docs/shared/gen-sites.mjs
 *
 * Deploy:   CLOUDFLARE_API_TOKEN=... ARTIFACTS_WORKER_NAME=... pnpm -C apps/docs/artifacts deploy
 * Destroy:  pnpm -C apps/docs/artifacts destroy
 *
 * Required: ARTIFACTS_WORKER_NAME, preserving the existing Worker name.
 * See apps/docs/README.md for Alchemy 1 state migration and explicit adoption.
 * Optional env: ARTIFACTS_SITE_DOMAIN (preview deploys, default artifacts.smithers.sh),
 * CLOUDFLARE_SMITHERS_ZONE_ID (alchemy resolves the zone from the domain when
 * omitted).
 */
import { makeDocsSiteStack } from "@smithers/docs-shared/alchemy-site"

export default makeDocsSiteStack({ slug: "artifacts" })
