#!/usr/bin/env node
/** Projects package-owned Capability documentation into the repository site. */
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { DocsManifest } from "../DocsManifest.ts"

const check = process.argv.includes("--check")
const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const repoRoot = join(packageRoot, "..", "..")
const read = (path) => readFileSync(path, "utf8")

const ungutter = (block) => block.split("\n").map((line) => line.replace(/^\s*\* ?/, "")).join("\n")

const description = (body) => {
  const lines = []
  for (const line of body.split("\n")) {
    if (/^@\w+/.test(line)) break
    lines.push(line)
  }
  return lines.join("\n").trim()
}

const delink = (value) => value.replace(/\{@link\s+([^}]+)\}/g, "`$1`")

const paragraphs = (value) => {
  const blocks = []
  let current = []
  for (const line of value.split("\n")) {
    if (line.trim() === "") {
      if (current.length > 0) blocks.push(current.join(" "))
      current = []
    } else current.push(line.trim())
  }
  if (current.length > 0) blocks.push(current.join(" "))
  return blocks.join("\n\n")
}

const firstSentence = (value) => {
  const flat = delink(value).split("\n\n")[0].split("\n").join(" ")
  return (/^[\s\S]*?\.(?=\s|$)/.exec(flat)?.[0] ?? flat).trim()
}

const moduleDoc = (source) => {
  const match = /\/\*\*((?:[^*]|\*(?!\/))*)\*\//.exec(source)
  if (match === null) throw new Error("capability docs: no module JSDoc block")
  return delink(description(ungutter(match[1])))
}

const exportedDocs = (source, namespace) => {
  const entries = []
  // The opening `/**` is anchored to the start of a line so a `"/**"` glob
  // literal inside a function body cannot be read as a doc comment. Without the
  // anchor the `resourceSubsumes` suffix check swallowed the `subsumes` JSDoc
  // and published a slice of source as its summary.
  const pattern = /^\/\*\*((?:[^*]|\*(?!\/))*)\*\/\s*\nexport (type|const|class|interface) (\w+)/gm
  for (let match = pattern.exec(source); match !== null; match = pattern.exec(source)) {
    const body = ungutter(match[1])
    const category = /@category (\S+)/.exec(body)?.[1]
    if (category === undefined) continue
    entries.push({
      name: `${namespace}.${match[3]}`,
      declaration: match[2],
      category,
      summary: firstSentence(description(body))
    })
  }
  return entries
}

const manifest = JSON.parse(read(join(packageRoot, "package.json")))
if (manifest.name !== DocsManifest.name) throw new Error("capability docs: DocsManifest.ts and package.json names differ")

// The barrel re-exports namespaces (`export * as Capability from "./Capability.ts"`),
// so every published symbol is reached as `Namespace.Export` and the table says so.
const barrel = read(join(packageRoot, "src", "index.ts"))
const modules = [...barrel.matchAll(/export \* as (\w+) from "\.\/(\w+)\.ts"/g)]
  .map((match) => ({ namespace: match[1], file: match[2] }))
if (modules.length === 0) throw new Error("capability docs: no namespace exports found in the barrel")
const exports = modules.flatMap((module) =>
  exportedDocs(read(join(packageRoot, "src", `${module.file}.ts`)), module.namespace)
)
if (exports.length === 0) throw new Error("capability docs: no documented exports found")

const table = [
  "| Export | Kind | Summary |",
  "| --- | --- | --- |",
  ...exports.map((entry) => `| \`${entry.name}\` (${entry.declaration}) | ${entry.category} | ${entry.summary} |`)
].join("\n")

const apiPage = `---
description: "${manifest.description}."
---

{/* Generated by \`node packages/capability/scripts/docs.mjs\` from packages/capability. Edit package sources, never this file. */}

# @smthrs/capability

${paragraphs(moduleDoc(barrel))}

${read(join(packageRoot, DocsManifest.api.source)).trim()}

## Exports

${table}
`

const regionStart = (name) => `{/* generated:${name} start */}`
const regionEnd = (name) => `{/* generated:${name} end */}`
const replaceRegion = (source, name, body) => {
  const start = source.indexOf(regionStart(name))
  const end = source.indexOf(regionEnd(name))
  if (start < 0 || end < 0 || end < start) throw new Error(`capability docs: region ${name} is missing`)
  return `${source.slice(0, start)}${regionStart(name)}\n\n${body.trim()}\n\n${source.slice(end)}`
}

const outputs = new Map([[DocsManifest.api.target, apiPage]])
for (const snippet of DocsManifest.snippets) {
  const current = outputs.get(snippet.target) ?? read(join(repoRoot, snippet.target))
  outputs.set(snippet.target, replaceRegion(current, snippet.region, read(join(packageRoot, snippet.source))))
}

const failures = []
for (const path of DocsManifest.references) {
  const content = read(join(repoRoot, path))
  if (!content.includes(DocsManifest.name) || !content.includes("/api/capability")) {
    failures.push(`${path}: must reference ${DocsManifest.name} and /api/capability`)
  }
}
for (const [path, content] of outputs) {
  if (content.includes("—")) failures.push(`${path}: generated content contains an em-dash`)
}

let drifted = false
for (const [path, content] of outputs) {
  const absolute = join(repoRoot, path)
  if (read(absolute) === content) continue
  drifted = true
  if (check) failures.push(`${path}: drifted; run node packages/capability/scripts/docs.mjs`)
  else {
    writeFileSync(absolute, content)
    console.log(`wrote ${path}`)
  }
}

if (failures.length > 0) {
  for (const failure of failures) console.error(`✗ ${failure}`)
  process.exit(1)
}

console.log(
  check
    ? "✓ the capability package documentation is current"
    : drifted
    ? "✓ capability package documentation regenerated"
    : "✓ capability package documentation already current"
)
