/**
 * The Implementation tab: a file tree over the sources that actually run this
 * demo, with a viewer and per-file GitHub links.
 *
 * Composed from shipped components. `FileTree`, `Card`, `EmptyState`,
 * `Badge`, and `Button` come from `smthrs/ui` unchanged; `StatusPill` comes
 * from `smthrs/gateway-ui`. Nothing here reimplements a smithers component.
 *
 * The one thing `smthrs/ui` does not ship is a syntax highlighter, so the
 * viewer applies a small tokenizer of its own. It is presentation over the
 * exact bytes read from the repository at build time; the text itself is
 * unmodified.
 */
import { createRoot } from "react-dom/client";
import { useMemo, useState } from "react";
import { Badge, Button, Card, CardContent, CardHeader, CardTitle, EmptyState, FileTree } from "smthrs/ui";
import { StatusPill } from "smthrs/gateway-ui";
// Generated by build.mjs immediately before this bundle is produced.
import { implFiles } from "./impl-files.generated.js";

const GITHUB = "https://github.com/smithersai/smithers/blob/main";
// Every file lives under one directory, so the tree shows paths relative to it
// and keeps the repository path for the GitHub link.
const PREFIX = "apps/stereos-site/";
const paths = Object.keys(implFiles).sort();
const shortOf = (path) => (path.startsWith(PREFIX) ? path.slice(PREFIX.length) : path);
const fullOf = (short) => paths.find((path) => shortOf(path) === short) ?? short;
const treeNodes = paths.map(shortOf);

/** What each top-level area of the tree is for, shown above the viewer. */
const AREAS = [
  [/^apps\/stereos-site\/service\//, "Demo service", "The gateway workspace, the guard, and the systemd units behind the Live demo tab."],
  [/^apps\/stereos-site\/real\//, "Recorded runs", "The provider, guest workflow, and host scripts that produced the captures."],
  [/^apps\/stereos-site\/page\//, "This page", "The page shell and the scripts behind each tab."],
  [/^apps\/stereos-site\//, "Build and checks", "The site build and the end-to-end check that runs against production."],
];

const areaOf = (path) => AREAS.find(([pattern]) => pattern.test(path)) ?? [null, "Source", ""];

const LANGUAGE = {
  ts: "typescript", tsx: "tsx", js: "javascript", jsx: "jsx", mjs: "javascript",
  sh: "shell", md: "markdown", toml: "toml", json: "json", html: "html", css: "css",
  svg: "svg", service: "systemd",
};
const languageOf = (path) => LANGUAGE[path.split(".").pop() ?? ""] ?? "text";

const KEYWORDS = new RegExp(
  `\\b(${[
    "import", "export", "from", "const", "let", "var", "function", "return", "async", "await",
    "if", "else", "for", "while", "try", "catch", "finally", "throw", "new", "class", "extends",
    "type", "interface", "default", "as", "of", "in", "typeof", "instanceof", "void", "null",
    "undefined", "true", "false", "this", "set", "exec", "echo", "then", "fi", "do", "done",
    "local", "sudo", "systemctl",
  ].join("|")})\\b`,
  "g",
);

/**
 * Split source into styled spans. Comments and strings win over keywords, so
 * the pass runs longest-match-first over one combined pattern.
 */
function highlight(source, language) {
  if (language === "markdown" || language === "text") return [{ text: source }];
  const pattern =
    /(\/\*[\s\S]*?\*\/|\/\/[^\n]*|#[^\n]*|"(?:[^"\\\n]|\\.)*"|'(?:[^'\\\n]|\\.)*'|`(?:[^`\\]|\\.)*`)/g;
  const out = [];
  let last = 0;
  for (const match of source.matchAll(pattern)) {
    if (match.index > last) out.push(...keywords(source.slice(last, match.index)));
    const value = match[0];
    const kind = value.startsWith("//") || value.startsWith("/*") || value.startsWith("#") ? "comment" : "string";
    out.push({ text: value, kind });
    last = match.index + value.length;
  }
  if (last < source.length) out.push(...keywords(source.slice(last)));
  return out;
}

function keywords(chunk) {
  const out = [];
  let last = 0;
  for (const match of chunk.matchAll(KEYWORDS)) {
    if (match.index > last) out.push({ text: chunk.slice(last, match.index) });
    out.push({ text: match[0], kind: "keyword" });
    last = match.index + match[0].length;
  }
  if (last < chunk.length) out.push({ text: chunk.slice(last) });
  return out;
}

const TONE = {
  comment: "var(--muted)",
  string: "var(--green)",
  keyword: "var(--purple)",
};

function App() {
  const [selected, setSelected] = useState("apps/stereos-site/service/guard.ts");
  const source = implFiles[selected] ?? "";
  const language = languageOf(selected);
  const spans = useMemo(() => highlight(source, language), [source, language]);
  const [, areaTitle, areaNote] = areaOf(selected);
  const lines = source ? source.split("\n").length : 0;

  return (
    <div style={{ display: "grid", gridTemplateColumns: "minmax(220px, 300px) minmax(0, 1fr)", gap: 14, alignItems: "start" }}>
      <Card data-testid="impl-tree">
        <CardHeader>
          <CardTitle style={{ fontSize: 13 }}>
            {paths.length} files <Badge variant="muted">read at build time</Badge>
          </CardTitle>
        </CardHeader>
        <CardContent style={{ maxHeight: 620, overflow: "auto" }}>
          <FileTree
            nodes={treeNodes}
            selected={shortOf(selected)}
            onSelect={(short) => setSelected(fullOf(short))}
          />
        </CardContent>
      </Card>

      {source ? (
        <Card data-testid="impl-viewer" data-path={selected}>
          <CardHeader>
            <CardTitle style={{ display: "flex", flexWrap: "wrap", gap: 8, alignItems: "center", fontSize: 13 }}>
              <code data-testid="impl-path" style={{ fontSize: 12 }}>
                {selected}
              </code>
              <StatusPill status="ok" label={language} />
              <Badge variant="muted">{lines} lines</Badge>
              <Button asChild size="sm" variant="outline" style={{ marginLeft: "auto" }}>
                <a href={`${GITHUB}/${selected}`} target="_blank" rel="noreferrer" data-testid="impl-github">
                  View on GitHub
                </a>
              </Button>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p style={{ margin: "0 0 10px", color: "var(--muted)", fontSize: 12, lineHeight: 1.5 }}>
              <strong style={{ color: "var(--ink)" }}>{areaTitle}.</strong> {areaNote}
            </p>
            <pre
              data-testid="impl-source"
              style={{
                margin: 0,
                maxHeight: 560,
                overflow: "auto",
                padding: "12px 14px",
                // Card content is muted by default; source must stay full contrast.
                color: "var(--ink)",
                background: "var(--diagram)",
                border: "1px solid var(--line)",
                borderRadius: 10,
                font: "11.5px/1.6 ui-monospace, SFMono-Regular, Menlo, monospace",
                whiteSpace: "pre",
              }}
            >
              {spans.map((span, index) => (
                // eslint-disable-next-line react/no-array-index-key -- spans are positional
                <span key={index} style={span.kind ? { color: TONE[span.kind] } : undefined}>
                  {span.text}
                </span>
              ))}
            </pre>
          </CardContent>
        </Card>
      ) : (
        <EmptyState title="Pick a file" description="Every source that runs the demo is in the tree." />
      )}
    </div>
  );
}

const mount = document.getElementById("impl-root");
if (mount) createRoot(mount).render(<App />);
