import { compileScenario } from "../scenario/compile.ts";
import type { ScenarioAst } from "../scenario/ast.ts";
import type { ControlMessage } from "../control/ControlMessage.ts";
const controlsValid = (ast: ScenarioAst, controls: readonly ControlMessage[]): boolean => { const steps = new Set(ast.steps.map((step) => step.id)); const faults = new Set(ast.faults.map((fault) => fault.id)); const barriers = new Set(ast.barriers.map((barrier) => barrier.id)); return controls.every((control) => (control.type !== "pin-interleaving" || steps.has(control.choice)) && (control.type !== "task-restart" || steps.has(control.step)) && (control.type !== "inject-fault" || faults.has(control.fault)) && (control.type !== "release-barrier" || barriers.has(control.barrier)) && (control.type !== "resolve-effect" || steps.has(control.effect.split(":", 1)[0]))); };
const removeStep = (ast: ScenarioAst, id: string): ScenarioAst => {
  // Only remove a leaf that is not a barrier party. Rewriting dependencies or
  // barriers produces a different scenario while pretending it is a shrink.
  const referenced = new Set(ast.steps.flatMap((step) => step.dependsOn));
  if (referenced.has(id) || ast.barriers.some((barrier) => barrier.parties.includes(id))) return ast;
  return { ...ast, steps: ast.steps.filter((step) => step.id !== id) };
};
export const shrink = async (ast: ScenarioAst, controls: readonly ControlMessage[], failure: (ast: ScenarioAst, controls: readonly ControlMessage[]) => boolean | Promise<boolean>, options: { maxCandidates?: number } = {}) => { const max = Math.max(0, options.maxCandidates ?? 100); let tried = 0; let current = ast; let currentControls = [...controls]; let changed = true; while (changed && tried < max) { changed = false; for (const step of [...current.steps]) { if (tried >= max || current.steps.length <= 1) break; const candidate = removeStep(current, step.id); const candidateControls = currentControls.filter((control) => (control.type !== "pin-interleaving" || control.choice !== step.id) && (control.type !== "task-restart" || control.step !== step.id)); tried++; if (!compileScenario(candidate).ok || !controlsValid(candidate, candidateControls)) continue; if (await failure(candidate, candidateControls)) { current = candidate; currentControls = candidateControls; changed = true; break; } } } for (let i = 0; i < currentControls.length && tried < max; i++) { const candidateControls = currentControls.filter((_, index) => index !== i); tried++; if (!controlsValid(current, candidateControls)) continue; if (await failure(current, candidateControls)) { currentControls = candidateControls; i = -1; } } return { ast: current, controls: currentControls, candidatesTried: tried }; };
