/**
 * Alchemy infrastructure-as-code for create-app.smithers.sh, the @smthrs/create-app docs site.
 * Generated by apps/docs/shared/gen-sites.mjs from apps/docs/shared/manifest.mjs. Edit the generator, then rerun it: node apps/docs/shared/gen-sites.mjs
 *
 * Deploy:   CLOUDFLARE_API_TOKEN=... ALCHEMY_PASSWORD=... pnpm -C apps/docs/create-app deploy
 * Destroy:  pnpm -C apps/docs/create-app destroy
 *
 * Optional env: CREATE_APP_SITE_DOMAIN (preview deploys, default create-app.smithers.sh),
 * CLOUDFLARE_SMITHERS_ZONE_ID (alchemy resolves the zone from the domain when
 * omitted).
 */
import { deployDocsSite } from "@smithers/docs-shared/alchemy-site"

export const site = await deployDocsSite({ slug: "create-app" })
