#!/usr/bin/env node
/** Projects package-owned jj documentation into the repository site. */
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { Package } from "../Package.ts"

const check = process.argv.includes("--check")
const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const repoRoot = join(packageRoot, "..", "..")
const read = (path) => readFileSync(path, "utf8")

const ungutter = (block) => block.split("\n").map((line) => line.replace(/^\s*\* ?/, "")).join("\n")

const description = (body) => {
  const lines = []
  for (const line of body.split("\n")) {
    if (/^@\w+/.test(line)) break
    lines.push(line)
  }
  return lines.join("\n").trim()
}

const delink = (value) => value.replace(/\{@link\s+([^}]+)\}/g, "`$1`")

/**
 * Paragraph blocks joined onto one line each, EXCEPT inside a fenced code
 * block, where the lines are the content. The module header of this package's
 * barrel carries the three-import example, and reflowing it would run the
 * example onto a single line.
 */
const paragraphs = (value) => {
  const blocks = []
  let current = []
  let fenced = false
  for (const line of value.split("\n")) {
    if (line.trim().startsWith("```")) {
      if (fenced) {
        current.push(line.trim())
        blocks.push(current.join("\n"))
        current = []
        fenced = false
      } else {
        if (current.length > 0) blocks.push(current.join(" "))
        current = [line.trim()]
        fenced = true
      }
      continue
    }
    if (fenced) {
      current.push(line)
      continue
    }
    if (line.trim() === "") {
      if (current.length > 0) blocks.push(current.join(" "))
      current = []
    } else current.push(line.trim())
  }
  if (current.length > 0) blocks.push(fenced ? current.join("\n") : current.join(" "))
  return blocks.join("\n\n")
}

const firstSentence = (value) => {
  const flat = delink(value).split("\n\n")[0].split("\n").join(" ")
  return (/^[\s\S]*?\.(?=\s|$)/.exec(flat)?.[0] ?? flat).trim()
}

const moduleDoc = (source, label) => {
  const match = /\/\*\*([\s\S]*?)\*\//.exec(source)
  if (match === null) throw new Error(`jj docs: no module JSDoc block in ${label}`)
  return delink(description(ungutter(match[1])))
}

const exportedDocs = (source) => {
  const entries = []
  const pattern = /\/\*\*((?:[^*]|\*(?!\/))*)\*\/\s*\nexport (type|const|class|interface|function) (\w+)/g
  for (let match = pattern.exec(source); match !== null; match = pattern.exec(source)) {
    const body = ungutter(match[1])
    const category = /@category (\S+)/.exec(body)?.[1]
    if (category === undefined) continue
    entries.push({
      name: match[3],
      declaration: match[2],
      category,
      summary: firstSentence(description(body))
    })
  }
  return entries
}

const manifest = JSON.parse(read(join(packageRoot, "package.json")))
if (manifest.name !== Package.name) throw new Error("jj docs: Package.ts and package.json names differ")

const sourcesOf = (entry) => {
  const absolute = join(packageRoot, entry.source)
  if (entry.barrel !== true) return [absolute]
  const barrel = read(absolute)
  return [...barrel.matchAll(/export \* from "\.\/(\w+)\.ts"/g)].map((match) =>
    join(packageRoot, "src", `${match[1]}.ts`)
  )
}

const table = (entries) =>
  [
    "| Export | Kind | Summary |",
    "| --- | --- | --- |",
    ...entries.map((entry) => `| \`${entry.name}\` (${entry.declaration}) | ${entry.category} | ${entry.summary} |`)
  ].join("\n")

const barrelEntry = Package.entryPoints.find((entry) => entry.barrel === true)
if (barrelEntry === undefined) throw new Error("jj docs: no barrel entry point declared")

const entryPointTable = [
  "| Import | Source | Platform |",
  "| --- | --- | --- |",
  ...Package.entryPoints.map((entry) =>
    `| \`${entry.import}\` | [${entry.source}](https://github.com/smithersai/smithers/blob/main/packages/jj/${entry.source}) | ${entry.platform} |`
  )
].join("\n")

const sections = Package.entryPoints.map((entry) => {
  const entries = sourcesOf(entry).flatMap((source) => exportedDocs(read(source)))
  if (entries.length === 0) throw new Error(`jj docs: ${entry.import} documents no exports with @category`)
  return `### \`${entry.import}\`\n\n${table(entries)}`
}).join("\n\n")

const apiPage = `---
description: "${manifest.description}."
---

{/* Generated by \`node packages/jj/scripts/docs.mjs\` from packages/jj. Edit package sources, never this file. */}

# @smthrs/jj

${paragraphs(moduleDoc(read(join(packageRoot, barrelEntry.source)), barrelEntry.source))}

${read(join(packageRoot, Package.api.source)).trim()}

## Entry points

The wildcard \`./*\` export over \`src/\` is the public API, so every module below
is an entry point a consumer may import.

${entryPointTable}

## Exports

${sections}
`

const outputs = new Map([[Package.api.target, apiPage]])

const failures = []
for (const path of Package.references) {
  const content = read(join(repoRoot, path))
  if (!content.includes(Package.name) || !content.includes("/api/jj")) {
    failures.push(`${path}: must reference ${Package.name} and /api/jj`)
  }
}
for (const [path, content] of outputs) {
  if (content.includes("—")) failures.push(`${path}: generated content contains an em-dash`)
}

let drifted = false
for (const [path, content] of outputs) {
  const absolute = join(repoRoot, path)
  if (read(absolute) === content) continue
  drifted = true
  if (check) failures.push(`${path}: drifted; run node packages/jj/scripts/docs.mjs`)
  else {
    writeFileSync(absolute, content)
    console.log(`wrote ${path}`)
  }
}

if (failures.length > 0) {
  for (const failure of failures) console.error(`✗ ${failure}`)
  process.exit(1)
}

console.log(
  check
    ? "✓ the jj package documentation is current"
    : drifted
    ? "✓ jj package documentation regenerated"
    : "✓ jj package documentation already current"
)
