function safeJson(value) {
  return JSON.stringify(value).replaceAll("<", "\\u003c").replaceAll(">", "\\u003e").replaceAll("&", "\\u0026");
}

function validOrigin(value) {
  if (!value) return "";
  try { const url = new URL(value); return (url.protocol === "http:" || url.protocol === "https:") && url.origin === value ? value : ""; } catch { return ""; }
}

/** Render the credential-free stationary browser viewer. */
export function renderBrowserViewer(sessionId, query = new URLSearchParams()) {
  const theme = query.get("theme") === "light" ? "light" : query.get("theme") === "dark" ? "dark" : "system";
  const hostOrigin = validOrigin(query.get("hostOrigin") || "");
  const embed = query.get("embed") === "1" || query.get("embed") === "true";
  return `<!doctype html><html lang="en" data-theme="${theme}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Browser viewer</title><style>:root{color-scheme:light;background:#f7f7f8;color:#171717}html[data-theme=dark]{color-scheme:dark;background:#111;color:#eee}@media(prefers-color-scheme:dark){html[data-theme=system]{color-scheme:dark;background:#111;color:#eee}}html,body{margin:0;width:100%;height:100%;font:14px system-ui}body{display:grid;grid-template-rows:1fr auto}main{display:grid;place-items:center;overflow:hidden}canvas{max-width:100%;max-height:100%;object-fit:contain;background:#ddd;touch-action:none}footer{display:flex;gap:6px;padding:8px;background:color-mix(in srgb,currentColor 8%,transparent)}button{color:inherit;background:color-mix(in srgb,currentColor 12%,transparent);border:1px solid color-mix(in srgb,currentColor 35%,transparent);border-radius:4px;padding:5px 9px}body[data-embed=true] footer{display:none}</style></head><body data-embed="${embed}"><main><canvas tabindex="0"></canvas></main><footer><button data-action="back">Back</button><button data-action="forward">Forward</button><button data-action="reload">Reload</button><button data-action="stop">Stop</button></footer><script>
const sessionId=${safeJson(sessionId)},hostOrigin=${safeJson(hostOrigin)};const canvas=document.querySelector('canvas'),ctx=canvas.getContext('2d');let socket,revision=0,requestedSeq=0,paintedSeq=0,actionQueue=Promise.resolve(),socketGeneration=0,reconnectTimer,readyPromise,readyResolve,pageActive=true;
const pending=new Map();
function request(method,params,target=socket){const current=target,generation=socketGeneration;if(!current||current.readyState!==WebSocket.OPEN)return Promise.reject(Object.assign(new Error('Gateway WebSocket is not ready'),{code:'SOCKET_CLOSED'}));return new Promise((resolve,reject)=>{const id=crypto.randomUUID();pending.set(id,{socket:current,generation,resolve,reject});try{current.send(JSON.stringify({type:'req',id,method,params}))}catch(error){pending.delete(id);reject(Object.assign(error instanceof Error?error:new Error(String(error)),{code:'SOCKET_CLOSED'}))}})}
function modifiers(e){return ['Control','Shift','Alt','Meta'].filter(k=>e[{Control:'ctrlKey',Shift:'shiftKey',Alt:'altKey',Meta:'metaKey'}[k]])}
function notify(message){if(hostOrigin&&window.parent!==window)window.parent.postMessage({source:'smithers-browser-viewer',...message},hostOrigin)}
function rejectSocket(current,generation){for(const [id,entry] of pending){if(entry.socket===current&&entry.generation===generation){pending.delete(id);entry.reject(Object.assign(new Error('Gateway WebSocket closed'),{code:'SOCKET_CLOSED'}))}}}
function scheduleReconnect(){if(!pageActive||reconnectTimer)return;reconnectTimer=setTimeout(()=>{reconnectTimer=undefined;connect()},100)}
function markReady(){readyResolve?.();readyResolve=undefined;readyPromise=undefined}
function waitReady(){if(ready) return Promise.resolve();return readyPromise??(readyPromise=new Promise(resolve=>{readyResolve=resolve}))}
function resync(target=socket){return request('browserContext',{sessionId,include:[]},target).then(context=>{revision=context.snapshot.revision;notify({type:'revision',revision})})}
async function executeAction(action,actionId){let conflictRetried=false;for(;;){await waitReady();try{const result=await request('browserAct',{sessionId,actionId,expectedRevision:revision,action});revision=result.revision;notify({type:'activity',revision,result});return}catch(error){if(error?.code==='REVISION_CONFLICT'&&!conflictRetried){conflictRetried=true;try{await resync()}catch(resyncError){if(resyncError?.code==='SOCKET_CLOSED')continue;throw resyncError}continue}if(error?.code==='SOCKET_CLOSED'){continue}throw error}}}
function act(action){const actionId='viewer-'+crypto.randomUUID();actionQueue=actionQueue.catch(()=>{}).then(()=>executeAction(action,actionId)).catch(error=>{notify({type:'error',error:{code:error?.code||'ACTION_FAILED',message:error?.message||String(error)}})});return actionQueue}
function draw(frame){if(frame.seq<=requestedSeq)return;requestedSeq=frame.seq;const image=new Image();image.onload=()=>{if(frame.seq!==requestedSeq||frame.seq<=paintedSeq)return;canvas.width=frame.viewport.width;canvas.height=frame.viewport.height;ctx.drawImage(image,0,0,canvas.width,canvas.height);paintedSeq=frame.seq};image.src='data:image/jpeg;base64,'+frame.jpegBase64}
let ready=false;function connect(){if(!pageActive||socket?.readyState===WebSocket.CONNECTING)return;const current=socket=new WebSocket((location.protocol==='https:'?'wss:':'ws:')+'//'+location.host),generation=++socketGeneration;ready=false;current.addEventListener('open',async()=>{try{await request('connect',{minProtocol:1,maxProtocol:1,client:{id:'browser-viewer',version:'1',platform:'browser'},subscribe:['browser:'+sessionId]},current);await resync(current);if(socket!==current)return;ready=true;markReady();canvas.focus()}catch(error){notify({type:'error',error:{code:error?.code||'CONNECT_FAILED',message:error?.message||String(error)}});current.close()}});current.addEventListener('message',e=>{let frame;try{frame=JSON.parse(e.data)}catch{return}if(frame.type==='res'&&pending.get(frame.id)?.socket===current){const entry=pending.get(frame.id);pending.delete(frame.id);frame.ok?entry.resolve(frame.payload):entry.reject(frame.error);return}if(frame.type==='event'&&frame.event==='browser.frame'&&frame.payload.sessionId===sessionId)draw(frame.payload);if(frame.type==='event'&&frame.event==='browser.activity'&&frame.payload.sessionId===sessionId){revision=Math.max(revision,frame.payload.revision);notify({type:'activity',payload:frame.payload})}});current.addEventListener('close',()=>{if(socket===current){ready=false;rejectSocket(current,generation);scheduleReconnect()}});current.addEventListener('error',()=>{if(socket===current)rejectSocket(current,generation)})}connect();
canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect();act({kind:'click',point:{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height},button:e.button===2?'right':e.button===1?'middle':'left',modifiers:modifiers(e)})});canvas.addEventListener('wheel',e=>{e.preventDefault();act({kind:'scroll',deltaX:e.deltaX,deltaY:e.deltaY})},{passive:false});canvas.addEventListener('keydown',e=>{e.preventDefault();act({kind:'press',key:e.key,modifiers:modifiers(e)})});document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>act({kind:b.dataset.action})));addEventListener('beforeunload',()=>{pageActive=false;socket?.close()});
</script></body></html>`;
}
