export const BASE_CLI_AGENT_OPTION_KEYS = [
  "id",
  "model",
  "systemPrompt",
  "instructions",
  "cwd",
  "env",
  "inheritEnv",
  "yolo",
  "timeoutMs",
  "idleTimeoutMs",
  "maxOutputBytes",
  "extraArgs",
  "onQuotaExceeded",
  "effort",
];

export const CLI_AGENT_OPTION_KEYS = {
  AmpAgent: [
    "resume",
    "visibility",
    "mcpConfig",
    "settingsFile",
    "logLevel",
    "logFile",
    "dangerouslyAllowAll",
    "ide",
    "jetbrains",
  ],
  AntigravityAgent: [
    "sandbox",
    "dangerouslySkipPermissions",
    "allowedMcpServerNames",
    "allowedTools",
    "extensions",
    "listExtensions",
    "conversation",
    "continue",
    "resume",
    "listSessions",
    "deleteSession",
    "includeDirectories",
    "screenReader",
    "outputFormat",
    "debug",
    "binary",
    "configDir",
    "geminiDir",
    "apiKey",
  ],
  ClaudeCodeAgent: [
    "addDir",
    "agent",
    "agents",
    "allowDangerouslySkipPermissions",
    "allowedTools",
    "appendSystemPrompt",
    "configDir",
    "apiKey",
    "betas",
    "chrome",
    "continue",
    "dangerouslySkipPermissions",
    "debug",
    "debugFile",
    "disableSlashCommands",
    "disallowedTools",
    "fallbackModel",
    "file",
    "forkSession",
    "fromPr",
    "ide",
    "includePartialMessages",
    "inputFormat",
    "jsonSchema",
    "maxBudgetUsd",
    "mcpConfig",
    "mcpDebug",
    "noChrome",
    "noSessionPersistence",
    "outputFormat",
    "permissionMode",
    "pluginDir",
    "replayUserMessages",
    "resume",
    "sessionId",
    "settingSources",
    "settings",
    "strictMcpConfig",
    "tools",
    "verbose",
  ],
  CodexAgent: [
    "config",
    "enable",
    "disable",
    "image",
    "oss",
    "localProvider",
    "sandbox",
    "profile",
    "fullAuto",
    "dangerouslyBypassApprovalsAndSandbox",
    "cd",
    "skipGitRepoCheck",
    "addDir",
    "outputSchema",
    "nativeStructuredOutput",
    "color",
    "json",
    "outputLastMessage",
    "configDir",
    "apiKey",
  ],
  CursorAgent: [
    "apiKey",
    "header",
    "mode",
    "plan",
    "resume",
    "continueSession",
    "force",
    "autoReview",
    "sandbox",
    "approveMcps",
    "trust",
    "workspace",
    "pluginDir",
    "worktree",
    "worktreeBase",
    "skipWorktreeSetup",
    "streamPartialOutput",
  ],
  ForgeAgent: [
    "directory",
    "provider",
    "agent",
    "conversationId",
    "sandbox",
    "restricted",
    "verbose",
    "workflow",
    "event",
    "conversation",
  ],
  GeminiAgent: [
    "debug",
    "sandbox",
    "approvalMode",
    "experimentalAcp",
    "allowedMcpServerNames",
    "allowedTools",
    "extensions",
    "listExtensions",
    "resume",
    "listSessions",
    "deleteSession",
    "includeDirectories",
    "screenReader",
    "outputFormat",
    "configDir",
    "apiKey",
  ],
  HermesCliAgent: ["provider", "continueSession"],
  GrokAgent: [
    "apiKey",
    "configDir",
    "disableWebSearch",
    "disallowedTools",
    "maxTurns",
    "noMemory",
    "noPlan",
    "noSubagents",
    "rules",
    "sandbox",
    "tools",
  ],
  KimiAgent: [
    "cliVersion",
    "workDir",
    "session",
    "continue",
    "thinking",
    "addDir",
    "outputFormat",
    "finalMessageOnly",
    "quiet",
    "agent",
    "agentFile",
    "mcpConfigFile",
    "mcpConfig",
    "skillsDir",
    "maxStepsPerTurn",
    "maxRetriesPerStep",
    "maxRalphIterations",
    "verbose",
    "debug",
    "configDir",
  ],
  OmpAgent: [
    "provider",
    "apiKey",
    "appendSystemPrompt",
    "mode",
    "print",
    "continueSession",
    "resume",
    "sessionDir",
    "noSession",
    "tools",
    "noTools",
    "extensions",
    "noExtensions",
    "skills",
    "noSkills",
    "thinking",
    "hideThinking",
    "printThoughts",
    "hooks",
    "maxTime",
    "autoApprove",
    "approvalMode",
  ],
  OpenClawAgent: ["agent", "sessionId", "session", "workspace", "json", "continueSession"],
  OpenCodeAgent: ["agentName", "attachFiles", "continueSession", "sessionId", "variant"],
  PiAgent: [
    "provider",
    "apiKey",
    "appendSystemPrompt",
    "mode",
    "print",
    "continue",
    "resume",
    "session",
    "sessionDir",
    "noSession",
    "models",
    "listModels",
    "tools",
    "noTools",
    "extension",
    "noExtensions",
    "skill",
    "noSkills",
    "promptTemplate",
    "noPromptTemplates",
    "theme",
    "noThemes",
    "thinking",
    "export",
    "files",
    "verbose",
    "onExtensionUiRequest",
  ],
  PoolAgent: ["agentName", "sandbox", "continue", "resume", "resumeSession"],
  VibeAgent: ["agent", "maxTurns", "maxPrice", "maxTokens", "enabledTools", "sessionId", "continueSession"],
};

/** @param {Record<string, unknown>} opts @param {string} agentName */
export function assertKnownCliAgentOptions(opts, agentName) {
  if (!opts || typeof opts !== "object" || Array.isArray(opts)) {
    throw new TypeError(`${agentName} options must be an object.`);
  }
  const allowed = new Set([...BASE_CLI_AGENT_OPTION_KEYS, ...(CLI_AGENT_OPTION_KEYS[agentName] ?? [])]);
  const unknown = Object.keys(opts).filter((key) => !allowed.has(key));
  if (unknown.length > 0) {
    throw new TypeError(
      `${agentName} received unknown option${unknown.length === 1 ? "" : "s"}: ${unknown.join(", ")}. ` +
        "Unknown options are rejected because they would otherwise be silently ignored.",
    );
  }
}
