/**
 * Targets for platform-bun.smithers.sh, the @smthrs/platform-bun documentation site.
 * Generated by apps/docs/shared/gen-sites.mjs from apps/docs/shared/manifest.mjs. Edit the generator, then rerun it: node apps/docs/shared/gen-sites.mjs
 *
 * The content edge is the source package's docsFiles filegroup, imported by
 * label: input globs are package scoped, so a glob declared here could never
 * reach packages/smithers/flows/platform-bun.
 */
import { Smithers } from "@smthrs/targets"
import { Package as platformBunPackage } from "../../../packages/smithers/flows/platform-bun/PACKAGE.ts"

const cwd = "apps/docs/platform-bun"

/** The site's config, content, styles, and scripts. */
const sources = [
  Smithers.glob("//apps/docs/platform-bun/src/**/*"),
  Smithers.file("//apps/docs/platform-bun/astro.config.mjs"),
  Smithers.file("//apps/docs/platform-bun/package.json")
]

/** `astro check`: the site typechecks against its package tsconfig. */
const check = Smithers.ToolRun({
  command: "pnpm",
  args: ["run", "check"],
  inputs: sources,
  deps: [],
  cwd
})

/** `astro build`: the static site into `apps/docs/platform-bun/dist`. */
const build = Smithers.ToolBuild({
  tool: "astro",
  command: "pnpm",
  args: ["run", "build"],
  inputs: sources,
  outputs: ["dist"],
  deps: [],
  env: {},
  cache: true,
  cwd
})

/**
 * The committed content tree, stitched from @smthrs/platform-bun's colocated docs by
 * apps/docs/shared/sync-content.mjs. The committed copy is the cache:
 * `smithers-build lint //apps/docs/platform-bun:contentSync` fails on drift,
 * `smithers-build run //apps/docs/platform-bun:contentSync` applies.
 */
const contentSync = Smithers.Generate({
  summary: "Sync @smthrs/platform-bun's colocated docs into the site content tree; check drift under lint.",
  script: Smithers.file("//apps/docs/shared/sync-content.mjs"),
  env: { SMITHERS_DOCS_SLUG: "platform-bun" },
  data: [platformBunPackage.docsFiles],
  changes: ["src/content/docs/**"]
})

export const Package = Smithers.Package({
  targets: { check, build, contentSync }
})
