#!/usr/bin/env node
/** Projects package-owned Core documentation into the repository site. */
import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { Manifest } from "../docs/Manifest.ts"

const check = process.argv.includes("--check")
const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const repoRoot = join(packageRoot, "..", "..")
const read = (path) => readFileSync(path, "utf8")

const ungutter = (block) => block.split("\n").map((line) => line.replace(/^\s*\* ?/, "")).join("\n")

const description = (body) => {
  const lines = []
  for (const line of body.split("\n")) {
    if (/^@\w+/.test(line)) break
    lines.push(line)
  }
  return lines.join("\n").trim()
}

const delink = (value) => value.replace(/\{@link\s+([^}]+)\}/g, "`$1`")

const paragraphs = (value) => {
  const blocks = []
  let current = []
  for (const line of value.split("\n")) {
    if (line.trim() === "") {
      if (current.length > 0) blocks.push(current.join(" "))
      current = []
    } else current.push(line.trim())
  }
  if (current.length > 0) blocks.push(current.join(" "))
  return blocks.join("\n\n")
}

const firstSentence = (value) => {
  const flat = delink(value).split("\n\n")[0].split("\n").join(" ")
  return (/^[\s\S]*?\.(?=\s|$)/.exec(flat)?.[0] ?? flat).trim()
}

/**
 * The header's `Governing contract:` paragraph points a source reader at this
 * page, so republishing it here would be circular. Every other paragraph is
 * published.
 */
const withoutContractPointer = (value) =>
  value.split("\n\n").filter((block) => !block.startsWith("Governing contract")).join("\n\n").trim()

const moduleDoc = (source) => {
  const match = /\/\*\*([\s\S]*?)\*\//.exec(source)
  if (match === null) throw new Error("core docs: no module JSDoc block")
  return withoutContractPointer(delink(description(ungutter(match[1]))))
}

// Both patterns anchor the opening `/**` to the start of a line so a `/**`
// inside a string literal (for example `endsWith("/**")` in Effects.covers)
// can never open a phantom doc block that swallows the next real one.
const declared = /^[ \t]*\/\*\*((?:[^*]|\*(?!\/))*)\*\/\s*\nexport (type|const|class|function|interface) (\w+)/gm
const renamed = /^[ \t]*\/\*\*((?:[^*]|\*(?!\/))*)\*\/\s*\n\s+(?:\w+) as (\w+)/gm

const collect = (source, pattern, nameIndex, kindOf) => {
  const entries = []
  pattern.lastIndex = 0
  for (let match = pattern.exec(source); match !== null; match = pattern.exec(source)) {
    const body = ungutter(match[1])
    const category = /@category (\S+)/.exec(body)?.[1]
    if (category === undefined) continue
    entries.push({
      name: match[nameIndex],
      declaration: kindOf(match),
      category,
      summary: firstSentence(description(body))
    })
  }
  return entries
}

const exportedDocs = (source) => {
  const entries = [
    ...collect(source, declared, 3, (match) => match[2]),
    ...collect(source, renamed, 2, () => "const")
  ]
  const seen = new Set()
  return entries.filter((entry) => {
    const identity = `${entry.name} ${entry.declaration}`
    if (seen.has(identity)) return false
    seen.add(identity)
    return true
  }).sort((left, right) => left.name.localeCompare(right.name))
}

const manifest = JSON.parse(read(join(packageRoot, "package.json")))
if (manifest.name !== Manifest.name) throw new Error("core docs: Manifest.ts and package.json names differ")

const barrel = read(join(packageRoot, "src", "index.ts"))
const modules = [...barrel.matchAll(/export \* as (\w+) from "\.\/(\w+)\.ts"/g)].map((match) => ({
  namespace: match[1],
  file: match[2]
}))
if (modules.length === 0) throw new Error("core docs: the barrel exports no namespaces")

const sections = modules.map((module) => {
  const source = read(join(packageRoot, "src", `${module.file}.ts`))
  const exports = exportedDocs(source)
  if (exports.length === 0) throw new Error(`core docs: ${module.file}.ts documents no exports`)
  const rows = exports.map((entry) => `| \`${entry.name}\` (${entry.declaration}) | ${entry.category} | ${entry.summary} |`)
  return [
    `### ${module.namespace}`,
    "",
    paragraphs(moduleDoc(source)),
    "",
    "| Export | Kind | Summary |",
    "| --- | --- | --- |",
    ...rows
  ].join("\n")
})

const apiPage = `---
description: "${manifest.description}."
---

{/* Generated by \`node packages/core/scripts/docs.mjs\` from packages/core. Edit package sources, never this file. */}

# @smthrs/core

${paragraphs(moduleDoc(barrel))}

${read(join(packageRoot, Manifest.api.source)).trim()}

## Exports

Every namespace below is reachable from the root entry point and from
\`@smthrs/core/<Module>\`. \`internal/*\` and nested \`*/index\` subpaths are not
public.

${sections.join("\n\n")}
`

const outputs = new Map([[Manifest.api.target, apiPage]])

const failures = []
for (const path of Manifest.references) {
  const content = read(join(repoRoot, path))
  if (!content.includes(Manifest.name) || !content.includes("/api/core")) {
    failures.push(`${path}: must reference ${Manifest.name} and /api/core`)
  }
}
for (const [path, content] of outputs) {
  if (content.includes("—")) failures.push(`${path}: generated content contains an em-dash`)
}

let drifted = false
for (const [path, content] of outputs) {
  const absolute = join(repoRoot, path)
  if (existsSync(absolute) && read(absolute) === content) continue
  drifted = true
  if (check) failures.push(`${path}: drifted; run node packages/core/scripts/docs.mjs`)
  else {
    writeFileSync(absolute, content)
    console.log(`wrote ${path}`)
  }
}

if (failures.length > 0) {
  for (const failure of failures) console.error(`✗ ${failure}`)
  process.exit(1)
}

console.log(
  check
    ? "✓ the core package documentation is current"
    : drifted
    ? "✓ core package documentation regenerated"
    : "✓ core package documentation already current"
)
