#!/usr/bin/env node
/**
 * Projects package-owned Control documentation into the repository site.
 *
 * The barrel re-exports namespaces (`export * as Control from "./Control.ts"`)
 * rather than flat symbols, so the exports table is grouped by module: a reader
 * importing `@smthrs/control/ControlLive` needs to know which module owns a
 * name before the name is useful.
 */
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { Package } from "../Package.ts"

const check = process.argv.includes("--check")
const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const repoRoot = join(packageRoot, "..", "..")
const read = (path) => readFileSync(path, "utf8")

const ungutter = (block) => block.split("\n").map((line) => line.replace(/^\s*\* ?/, "")).join("\n")

const description = (body) => {
  const lines = []
  for (const line of body.split("\n")) {
    if (/^@\w+/.test(line)) break
    lines.push(line)
  }
  return lines.join("\n").trim()
}

const delink = (value) => value.replace(/\{@link\s+([^}]+)\}/g, "`$1`")

const paragraphs = (value) => {
  const blocks = []
  let current = []
  for (const line of value.split("\n")) {
    if (line.trim() === "") {
      if (current.length > 0) blocks.push(current.join(" "))
      current = []
    } else current.push(line.trim())
  }
  if (current.length > 0) blocks.push(current.join(" "))
  return blocks.join("\n\n")
}

const firstSentence = (value) => {
  const flat = delink(value).split("\n\n")[0].split("\n").join(" ")
  return (/^[\s\S]*?\.(?=\s|$)/.exec(flat)?.[0] ?? flat).trim()
}

const moduleDoc = (source) => {
  const match = /\/\*\*([\s\S]*?)\*\//.exec(source)
  if (match === null) throw new Error("control docs: no module JSDoc block")
  return delink(description(ungutter(match[1])))
}

const exportedDocs = (source) => {
  const entries = []
  // The body pattern must not span two comment blocks, so it matches anything
  // that is not a `*` plus a `*` that is not followed by a `/`.
  const pattern = /\/\*\*((?:[^*]|\*(?!\/))*)\*\/\s*\nexport (?:declare )?(type|const|class|interface|function) (\w+)/g
  for (let match = pattern.exec(source); match !== null; match = pattern.exec(source)) {
    const body = ungutter(match[1])
    const category = /@category (\S+)/.exec(body)?.[1]
    if (category === undefined) continue
    entries.push({
      name: match[3],
      declaration: match[1] === undefined ? "const" : match[2],
      category,
      summary: firstSentence(description(body))
    })
  }
  return entries
}

const regionStart = (name) => `{/* generated:${name} start */}`
const regionEnd = (name) => `{/* generated:${name} end */}`
const replaceRegion = (source, name, body) => {
  const start = source.indexOf(regionStart(name))
  const end = source.indexOf(regionEnd(name))
  if (start < 0 || end < 0 || end < start) throw new Error(`control docs: region ${name} is missing`)
  return `${source.slice(0, start)}${regionStart(name)}\n\n${body.trim()}\n\n${source.slice(end)}`
}

const manifest = JSON.parse(read(join(packageRoot, "package.json")))
if (manifest.name !== Package.name) throw new Error("control docs: Package.ts and package.json names differ")

const barrel = read(join(packageRoot, "src", "index.ts"))
const modules = [...barrel.matchAll(/export \* as (\w+) from "\.\/([\w/]+)\.ts"/g)]
  .map((match) => ({ namespace: match[1], path: match[2] }))
if (modules.length === 0) throw new Error("control docs: the barrel re-exports no namespaces")

const rows = []
for (const module of modules) {
  const documented = exportedDocs(read(join(packageRoot, "src", `${module.path}.ts`)))
  if (documented.length === 0) throw new Error(`control docs: ${module.path}.ts documents no exports`)
  for (const entry of documented) {
    rows.push([
      `\`${module.namespace}\``,
      `\`${entry.name}\` (${entry.declaration})`,
      entry.category,
      entry.summary
    ])
  }
}
if (rows.length === 0) throw new Error("control docs: no documented exports found")

const headings = ["Module", "Export", "Kind", "Summary"]
const widths = headings.map((heading, index) =>
  Math.max(heading.length, ...rows.map((row) => row[index].length))
)
const tableRow = (cells) => `| ${cells.map((cell, index) => cell.padEnd(widths[index])).join(" | ")} |`
const table = [
  tableRow(headings),
  tableRow(widths.map((width) => "-".repeat(width))),
  ...rows.map(tableRow)
].join("\n")

const apiPage = `---
description: "${manifest.description}."
---

{/* Generated by \`node packages/control/scripts/docs.mjs\` from packages/control. Edit package sources, never this file. */}

# @smthrs/control

${paragraphs(moduleDoc(barrel))}

${read(join(packageRoot, Package.api.source)).trim()}

## Exports

Each module is importable as \`@smthrs/control/<Module>\` and re-exported as a
namespace from the package root.

${table}
`

// The README's module table is the same projection of the same barrel, so it
// is generated rather than kept by hand. The hand-written one had drifted:
// five exported modules were missing from it entirely.
const readmePath = "packages/control/README.md"
const outputs = new Map([
  [Package.api.target, apiPage],
  [readmePath, replaceRegion(read(join(repoRoot, readmePath)), "control-modules", table)]
])
for (const snippet of Package.snippets) {
  const current = outputs.get(snippet.target) ?? read(join(repoRoot, snippet.target))
  outputs.set(snippet.target, replaceRegion(current, snippet.region, read(join(packageRoot, snippet.source))))
}

const failures = []
for (const path of Package.references) {
  const content = read(join(repoRoot, path))
  if (!content.includes(Package.name) || !content.includes("/api/control")) {
    failures.push(`${path}: must reference ${Package.name} and /api/control`)
  }
}
for (const [path, content] of outputs) {
  if (content.includes("—")) failures.push(`${path}: generated content contains an em-dash`)
}

let drifted = false
for (const [path, content] of outputs) {
  const absolute = join(repoRoot, path)
  if (read(absolute) === content) continue
  drifted = true
  if (check) failures.push(`${path}: drifted; run node packages/control/scripts/docs.mjs`)
  else {
    writeFileSync(absolute, content)
    console.log(`wrote ${path}`)
  }
}

if (failures.length > 0) {
  for (const failure of failures) console.error(`✗ ${failure}`)
  process.exit(1)
}

console.log(
  check
    ? "✓ the control package documentation is current"
    : drifted
    ? "✓ control package documentation regenerated"
    : "✓ control package documentation already current"
)
