#!/usr/bin/env node
/** Generates the categorized export index owned by `@smthrs/scorers`. */
import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { Manifest } from "../docs/Manifest.ts"

const check = process.argv.includes("--check")
const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const repoRoot = join(packageRoot, "..", "..")
const read = (...parts) => readFileSync(join(packageRoot, ...parts), "utf8")

const manifest = JSON.parse(read("package.json"))
if (manifest.name !== Manifest.name) throw new Error("scorers docs: Manifest.ts and package.json names differ")

const ungutter = (block) =>
  block.split("\n").map((line) => line.replace(/^\s*\* ?/, "")).join("\n")

const description = (body) => {
  const lines = []
  for (const line of body.split("\n")) {
    if (/^@\w+/.test(line)) break
    lines.push(line)
  }
  return lines.join("\n").trim()
}

const firstSentence = (value) => {
  const flat = value
    .replace(/\{@link\s+([^}]+)\}/g, "`$1`")
    .replaceAll("—", "-")
    .split("\n\n")[0]
    .split("\n")
    .join(" ")
    .replaceAll(/\s+/g, " ")
    .trim()
  return (/^[\s\S]*?\.(?=\s|$)/.exec(flat)?.[0] ?? flat).trim()
}

const documented = /\/\*\*((?:[^*]|\*(?!\/))*)\*\/\s*\nexport (?:declare )?(const|type|interface|class|function) (\w+)/g

const exportedDocs = (source) => {
  const entries = []
  for (let match = documented.exec(source); match !== null; match = documented.exec(source)) {
    const body = ungutter(match[1])
    const category = /@category (\S+)/.exec(body)?.[1]
    if (category === undefined) continue
    entries.push({
      category,
      kind: match[2],
      name: match[3],
      since: /@since (\S+)/.exec(body)?.[1],
      summary: firstSentence(description(body))
    })
  }
  return entries
}

const barrel = read("src", "index.ts")
const namespaces = [...barrel.matchAll(/export \* as (\w+) from "\.\/([^\"]+)\.ts"/g)].map(
  (match) => ({ namespace: match[1], file: match[2] })
)
if (namespaces.length === 0) throw new Error("scorers docs: no namespace re-exports found")

const failures = []
const exports = namespaces.flatMap((module) => {
  const entries = exportedDocs(read("src", `${module.file}.ts`))
  if (entries.length === 0) failures.push(`src/${module.file}.ts: no export carries an @category tag`)
  return entries.map((entry) => ({ ...entry, namespace: module.namespace, file: module.file }))
})

for (const entry of exports) {
  if (entry.since === undefined) failures.push(`src/${entry.file}.ts: ${entry.name} has no @since tag`)
  if (entry.summary === "") failures.push(`src/${entry.file}.ts: ${entry.name} has no JSDoc summary`)
}

const rows = [
  ["Export", "Kind", "Category", "Summary"],
  ...exports.map((entry) => [
    `\`${entry.namespace}.${entry.name}\``,
    entry.kind,
    entry.category,
    entry.summary
  ])
]
const widths = rows[0].map((_, index) => Math.max(...rows.map((row) => row[index].length)))
const row = (cells) => `| ${cells.map((cell, index) => cell.padEnd(widths[index])).join(" | ")} |`
const table = [
  row(rows[0]),
  `| ${widths.map((width) => "-".repeat(width)).join(" | ")} |`,
  ...rows.slice(1).map(row)
].join("\n")

const page = `<!-- Generated by \`node ${Manifest.generator}\` from packages/scorers/src. Edit the JSDoc, never this file. -->

# Exported members

Every categorized member reachable through the root namespaces. The package
target \`//packages/scorers:docsPages\` regenerates this file and drift-checks
it under the \`lint\` verb.

${namespaces.length} namespaces, ${exports.length} documented members.

${table}
`

if (page.includes("—")) failures.push(`${Manifest.exports.target}: generated content contains an em-dash`)

const absolute = join(repoRoot, Manifest.exports.target)
const current = existsSync(absolute) ? readFileSync(absolute, "utf8") : undefined
if (current !== page) {
  if (check) failures.push(`${Manifest.exports.target}: drifted; run node ${Manifest.generator}`)
  else {
    writeFileSync(absolute, page)
    console.log(`wrote ${Manifest.exports.target}`)
  }
}

if (failures.length > 0) {
  for (const failure of failures) console.error(`✗ ${failure}`)
  process.exit(1)
}

console.log(check ? "✓ the scorers package documentation is current" : "✓ scorers documentation regenerated")
