/**
 * Alchemy infrastructure-as-code for smithers-patterns.smithers.sh, the @smthrs/patterns docs site.
 * Generated by apps/docs/shared/gen-sites.mjs from apps/docs/shared/manifest.mjs. Edit the generator, then rerun it: node apps/docs/shared/gen-sites.mjs
 *
 * Deploy:   CLOUDFLARE_API_TOKEN=... ALCHEMY_PASSWORD=... pnpm -C apps/docs/smithers-patterns deploy
 * Destroy:  pnpm -C apps/docs/smithers-patterns destroy
 *
 * Optional env: SMITHERS_PATTERNS_SITE_DOMAIN (preview deploys, default smithers-patterns.smithers.sh),
 * CLOUDFLARE_SMITHERS_ZONE_ID (alchemy resolves the zone from the domain when
 * omitted).
 */
import { deployDocsSite } from "@smithers/docs-shared/alchemy-site"

export const site = await deployDocsSite({ slug: "smithers-patterns" })
