#!/usr/bin/env node
/** Projects package-owned error documentation into the repository site. */
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { DocsManifest } from "../DocsManifest.ts"
import {
  ERROR_REFERENCE_URL,
  smithersErrorCodes,
  smithersErrorDefinitions
} from "../src/ErrorCode.ts"
import {
  barrelExports,
  exportedDocs,
  exportNames,
  markdownTable,
  moduleDoc,
  paragraphs,
  replaceRegion,
  unsupportedExports
} from "./docs-lib.ts"

const check = process.argv.includes("--check")
const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const repoRoot = join(packageRoot, "..", "..")
const read = (path) => readFileSync(path, "utf8")

const manifest = JSON.parse(read(join(packageRoot, "package.json")))
if (manifest.name !== DocsManifest.name) throw new Error("errors docs: DocsManifest.ts and package.json names differ")
const route = new URL(ERROR_REFERENCE_URL).pathname
if (DocsManifest.api.target !== `docs/pages${route}.md`) {
  throw new Error("errors docs: ERROR_REFERENCE_URL and DocsManifest.api.target differ")
}

const codeRows = smithersErrorCodes.map((code) => {
  const definition = smithersErrorDefinitions[code]
  if (definition.when.trim() === "") throw new Error(`errors docs: ${code} has an empty when definition`)
  const details = "details" in definition
    ? definition.details.includes("`") ? definition.details : `\`${definition.details}\``
    : "none"
  return [`\`${code}\``, definition.when, details]
})
const codesTable = markdownTable(["Code", "Raised when", "`details`"], codeRows)

const barrel = read(join(packageRoot, "src", "index.ts"))
const entries = barrelExports(barrel)
const modules = [...new Set(entries.map((entry) => entry.module))]
if (paragraphs(moduleDoc(barrel)) === "") throw new Error("errors docs: empty module JSDoc block")
const unsupportedBarrel = unsupportedExports(barrel)
if (unsupportedBarrel.length > 0) {
  throw new Error(`errors docs: src/index.ts has unsupported export: ${unsupportedBarrel[0]}`)
}
const aliased = entries.find((entry) => entry.exported !== entry.name)
if (aliased !== undefined) {
  throw new Error(`errors docs: aliased re-exports are unsupported: ${aliased.name} as ${aliased.exported}`)
}

const exports = []
const documentedNames = new Set()
for (const module of modules) {
  const path = `src/${module}.ts`
  const source = read(join(packageRoot, path))
  const unsupported = unsupportedExports(source)
  if (unsupported.length > 0) {
    throw new Error(`errors docs: ${path} has unsupported export: ${unsupported[0]}`)
  }
  const documented = exportedDocs(source)
  const categorizedNames = new Set(documented.map((entry) => entry.name))
  for (const name of exportNames(source)) {
    if (!categorizedNames.has(name)) {
      throw new Error(`errors docs: ${path} export ${name} lacks a categorized JSDoc block`)
    }
  }
  exports.push(...documented)
  for (const name of categorizedNames) documentedNames.add(name)
}
for (const entry of entries) {
  if (!documentedNames.has(entry.name)) {
    throw new Error(`errors docs: src/index.ts re-exports undocumented name ${entry.name}`)
  }
}
if (exports.length === 0) throw new Error("errors docs: no documented exports found")
const exportsTable = markdownTable(
  ["Export", "Kind", "Summary"],
  exports.map((entry) => [
    `\`${entry.name}\` (${entry.declaration})`,
    entry.category,
    entry.summary
  ])
)

let reference = read(join(packageRoot, DocsManifest.api.source)).trim()
reference = replaceRegion(reference, "error-codes", codesTable, DocsManifest.api.target)
reference = replaceRegion(reference, "error-exports", exportsTable, DocsManifest.api.target)
reference = reference.replace(/^<!-- dprint-ignore-(?:start|end) -->\n?/gm, "")
const apiPage = `---
description: "${manifest.description}."
---

{/* Generated by \`node packages/errors/scripts/docs.mjs\` from packages/errors. Edit package sources, never this file. */}

# Error codes

${reference.trim()}
`

const outputs = new Map([[DocsManifest.api.target, apiPage]])
for (const snippet of DocsManifest.snippets) {
  const path = snippet.target.startsWith("docs/pages/") ? snippet.target : `packages/errors/${snippet.target}`
  const current = outputs.get(path) ?? read(join(repoRoot, path))
  const body = snippet.region === "error-codes" ? codesTable : snippet.region === "error-exports" ? exportsTable : undefined
  if (body === undefined) throw new Error(`errors docs: no generated body for region ${snippet.region}`)
  outputs.set(path, replaceRegion(current, snippet.region, body, path))
}

const failures = []
for (const path of DocsManifest.references) {
  const content = read(join(repoRoot, path))
  if (!content.includes(route)) failures.push(`${path}: must reference ${route}`)
}
for (const [path, content] of outputs) {
  if (content.includes("—")) failures.push(`${path}: generated content contains an em-dash`)
}

let drifted = false
for (const [path, content] of outputs) {
  const absolute = join(repoRoot, path)
  if (read(absolute) === content) continue
  drifted = true
  if (check) failures.push(`${path}: drifted; run node packages/errors/scripts/docs.mjs`)
  else {
    writeFileSync(absolute, content)
    console.log(`wrote ${path}`)
  }
}

if (failures.length > 0) {
  for (const failure of failures) console.error(`✗ ${failure}`)
  process.exit(1)
}

console.log(
  check
    ? "✓ the errors package documentation is current"
    : drifted
    ? "✓ errors package documentation regenerated"
    : "✓ errors package documentation already current"
)
