#!/usr/bin/env node
/** Projects package-owned plugin documentation into published files. */
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { Package } from "../Package.ts"

const check = process.argv.includes("--check")
const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const repoRoot = join(packageRoot, "..", "..")
const read = (path) => readFileSync(path, "utf8")
const ungutter = (block) => block.split("\n").map((line) => line.replace(/^\s*\* ?/, "")).join("\n")

const description = (body) => {
  const lines = []
  for (const line of body.split("\n")) {
    if (/^@\w+/.test(line)) break
    lines.push(line)
  }
  return lines.join("\n").trim()
}

const delink = (value) =>
  value
    .replace(/\{@link\s+(https?:\/\/\S+)\s*\|\s*([^}]+)\}/g, (_, url, label) => `[${label.trim()}](${url})`)
    .replace(/\{@link\s+(https?:\/\/\S+?)\s*\}/g, (_, url) => `<${url}>`)
    .replace(/\{@link\s+([^}|]+)\|([^}]+)\}/g, (_, __, label) => `\`${label.trim()}\``)
    .replace(/\{@link\s+([^}]+)\}/g, (_, symbol) => `\`${symbol.trim()}\``)

const paragraphs = (value) => {
  const blocks = []
  let current = []
  for (const line of value.split("\n")) {
    if (line.trim() === "") {
      if (current.length > 0) blocks.push(current.join(" "))
      current = []
    } else current.push(line.trim())
  }
  if (current.length > 0) blocks.push(current.join(" "))
  return blocks.join("\n\n")
}

const firstSentence = (value) => {
  const flat = delink(value).split("\n\n")[0].split("\n").join(" ")
  return (/^[\s\S]*?\.(?=\s|$)/.exec(flat)?.[0] ?? flat).trim()
}

const moduleDoc = (source) => {
  const match = /\/\*\*([\s\S]*?)\*\//.exec(source)
  if (match === null) throw new Error("plugin docs: module JSDoc is missing")
  return paragraphs(delink(description(ungutter(match[1]))))
}

const exportedDocs = (source) => {
  const entries = []
  const pattern = /\/\*\*((?:[^*]|\*(?!\/))*)\*\/\s*\nexport (type|const|class|interface|function) (\w+)/g
  for (let match = pattern.exec(source); match !== null; match = pattern.exec(source)) {
    const body = ungutter(match[1])
    const category = /@category (\S+)/.exec(body)?.[1]
    if (category === undefined) continue
    entries.push({
      name: match[3],
      declaration: match[2],
      category,
      summary: firstSentence(description(body))
    })
  }
  return entries
}

const manifest = JSON.parse(read(join(packageRoot, "package.json")))
if (manifest.name !== Package.name) throw new Error("plugin docs: Package.ts and package.json names differ")

const table = (exports) => [
  "| Export | Kind | Summary |",
  "| --- | --- | --- |",
  ...exports.map((entry) => `| \`${entry.name}\` (${entry.declaration}) | ${entry.category} | ${entry.summary} |`)
].join("\n")

const sections = Package.modules.map((entry) => {
  const source = read(join(packageRoot, entry.source))
  const exports = exportedDocs(source)
  if (exports.length === 0) throw new Error(`plugin docs: ${entry.source} documents no exports`)
  return `### ${entry.namespace}

\`${entry.specifier}\`, [${entry.source}](https://github.com/smithersai/smithers/blob/main/packages/plugin/${entry.source}).

${table(exports)}`
}).join("\n\n")

const rootDoc = moduleDoc(read(join(packageRoot, "src", "index.ts")))
const readme = `<!-- Generated by \`node packages/plugin/scripts/docs.mjs\`. Edit package docs and JSDoc, never this file. -->

# \`@smthrs/plugin\`

${rootDoc}

${read(join(packageRoot, Package.readme.source)).trim()}
`
const apiPage = `---
description: "${manifest.description}."
---

{/* Generated by \`node packages/plugin/scripts/docs.mjs\` from packages/plugin. Edit package sources, never this file. */}

# @smthrs/plugin

${rootDoc}

${read(join(packageRoot, Package.api.source)).trim()}

## Exports

Hook, plugin, and error declarations are flat root exports. Every module also
has the matching named subpath.

${sections}
`

const outputs = new Map([[Package.readme.target, readme], [Package.api.target, apiPage]])
const failures = []
for (const path of Package.references) {
  const content = read(join(repoRoot, path))
  if (!content.includes(Package.name) || !content.includes("/api/plugin")) {
    failures.push(`${path}: must reference ${Package.name} and /api/plugin`)
  }
}
for (const [path, content] of outputs) {
  if (content.includes("—")) failures.push(`${path}: generated content contains an em-dash`)
  for (const module of Package.modules) {
    if (!content.includes(module.specifier)) failures.push(`${path}: missing ${module.specifier}`)
  }
}

let drifted = false
for (const [path, content] of outputs) {
  const absolute = join(repoRoot, path)
  let existing = ""
  try {
    existing = read(absolute)
  } catch {}
  if (existing === content) continue
  drifted = true
  if (check) failures.push(`${path}: drifted; run node packages/plugin/scripts/docs.mjs`)
  else {
    writeFileSync(absolute, content)
    console.log(`wrote ${path}`)
  }
}

if (failures.length > 0) {
  for (const failure of failures) console.error(`✗ ${failure}`)
  process.exit(1)
}
console.log(check
  ? "✓ the plugin package documentation is current"
  : drifted
  ? "✓ plugin package documentation regenerated"
  : "✓ plugin package documentation already current")
