#!/usr/bin/env node
/**
 * Projects package-owned integrations documentation into the repository site.
 *
 * The shape differs from the canonical and crypto pilots in one way: this
 * package's barrel is two levels deep. `src/index.ts` re-exports a namespace
 * per provider, and each provider barrel re-exports a namespace per module, so
 * the walk follows both and the export table names each entry the way a reader
 * imports it (`GitHub.Actions.CommentOnIssue`).
 */
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { Package } from "../Package.ts"

const check = process.argv.includes("--check")
const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const repoRoot = join(packageRoot, "..", "..")
const read = (path) => readFileSync(path, "utf8")

const ungutter = (block) => block.split("\n").map((line) => line.replace(/^\s*\* ?/, "")).join("\n")

const description = (body) => {
  const lines = []
  for (const line of body.split("\n")) {
    if (/^@\w+/.test(line)) break
    lines.push(line)
  }
  return lines.join("\n").trim()
}

const delink = (value) => value.replace(/\{@link\s+([^}]+)\}/g, "`$1`")

const paragraphs = (value) => {
  const blocks = []
  let current = []
  for (const line of value.split("\n")) {
    if (line.trim() === "") {
      if (current.length > 0) blocks.push(current.join(" "))
      current = []
    } else current.push(line.trim())
  }
  if (current.length > 0) blocks.push(current.join(" "))
  return blocks.join("\n\n")
}

const firstSentence = (value) => {
  const flat = delink(value).split("\n\n")[0].split("\n").join(" ")
  return (/^[\s\S]*?\.(?=\s|$)/.exec(flat)?.[0] ?? flat).trim()
}

const moduleDoc = (source) => {
  const match = /\/\*\*([\s\S]*?)\*\//.exec(source)
  if (match === null) throw new Error("integrations docs: no module JSDoc block")
  return delink(description(ungutter(match[1])))
}

/** `export * as Ns from "./path.ts"` re-exports, in barrel order. */
const namespaces = (source) =>
  [...source.matchAll(/export \* as (\w+) from "\.\/([\w/]+)\.ts"/g)]
    .map((match) => ({ name: match[1], path: match[2] }))

/**
 * Exports carrying an `@category`, with their first-sentence summaries.
 *
 * The comment pattern must not span two blocks, hence `(?:[^*]|\*(?!\/))*`:
 * a greedy `[\s\S]*?` would swallow everything between one export's JSDoc and
 * the next one's.
 */
const exportedDocs = (source) => {
  const entries = []
  const pattern = /\/\*\*((?:[^*]|\*(?!\/))*)\*\/\s*\nexport (type|const|class|interface) (\w+)/g
  for (let match = pattern.exec(source); match !== null; match = pattern.exec(source)) {
    const body = ungutter(match[1])
    const category = /@category (\S+)/.exec(body)?.[1]
    if (category === undefined) continue
    entries.push({
      name: match[3],
      declaration: match[2],
      category,
      summary: firstSentence(description(body))
    })
  }
  return entries
}

const manifest = JSON.parse(read(join(packageRoot, "package.json")))
if (manifest.name !== Package.name) throw new Error("integrations docs: Package.ts and package.json names differ")

const barrel = read(join(packageRoot, "src", "index.ts"))
const providers = namespaces(barrel)
if (providers.length === 0) throw new Error("integrations docs: the entry point re-exports no namespace")

const sections = []
for (const provider of providers) {
  const providerSource = read(join(packageRoot, "src", `${provider.path}.ts`))
  const rows = []
  for (const module of namespaces(providerSource)) {
    for (const entry of exportedDocs(read(join(packageRoot, "src", `${module.path}.ts`)))) {
      rows.push(
        `| \`${provider.name}.${module.name}.${entry.name}\` (${entry.declaration}) | ${entry.category} | ${entry.summary} |`
      )
    }
  }
  if (rows.length === 0) throw new Error(`integrations docs: ${provider.name} documents no export`)
  sections.push(
    [
      `### ${provider.name}`,
      "",
      paragraphs(moduleDoc(providerSource)),
      "",
      "| Export | Kind | Summary |",
      "| --- | --- | --- |",
      ...rows
    ].join("\n")
  )
}

const apiPage = `---
description: "${manifest.description}."
---

{/* Generated by \`node packages/integrations/scripts/docs.mjs\` from packages/integrations. Edit package sources, never this file. */}

# @smthrs/integrations

${paragraphs(moduleDoc(barrel))}

${read(join(packageRoot, Package.api.source)).trim()}

## Exports

${sections.join("\n\n")}
`

const regionStart = (name) => `{/* generated:${name} start */}`
const regionEnd = (name) => `{/* generated:${name} end */}`
const replaceRegion = (source, name, body) => {
  const start = source.indexOf(regionStart(name))
  const end = source.indexOf(regionEnd(name))
  if (start < 0 || end < 0 || end < start) throw new Error(`integrations docs: region ${name} is missing`)
  return `${source.slice(0, start)}${regionStart(name)}\n\n${body.trim()}\n\n${source.slice(end)}`
}

const outputs = new Map([[Package.api.target, apiPage]])
for (const snippet of Package.snippets) {
  const current = outputs.get(snippet.target) ?? read(join(repoRoot, snippet.target))
  outputs.set(snippet.target, replaceRegion(current, snippet.region, read(join(packageRoot, snippet.source))))
}

const failures = []
for (const path of Package.references) {
  const content = read(join(repoRoot, path))
  if (!content.includes(Package.name) || !content.includes("/api/integrations")) {
    failures.push(`${path}: must reference ${Package.name} and /api/integrations`)
  }
}
for (const [path, content] of outputs) {
  if (content.includes("—")) failures.push(`${path}: generated content contains an em-dash`)
}

let drifted = false
for (const [path, content] of outputs) {
  const absolute = join(repoRoot, path)
  if (read(absolute) === content) continue
  drifted = true
  if (check) failures.push(`${path}: drifted; run node packages/integrations/scripts/docs.mjs`)
  else {
    writeFileSync(absolute, content)
    console.log(`wrote ${path}`)
  }
}

if (failures.length > 0) {
  for (const failure of failures) console.error(`✗ ${failure}`)
  process.exit(1)
}

console.log(
  check
    ? "✓ the integrations package documentation is current"
    : drifted
    ? "✓ integrations package documentation regenerated"
    : "✓ integrations package documentation already current"
)
