const lightTokens = [
  "color-scheme:light",
  "font-family:var(--font-sans)",
  // Font stacks. Sans carries the UI; mono is reserved for code, ids, and
  // tabular data. Never set body copy in mono.
  "--font-sans:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif",
  "--font-mono:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace",
  // Neutrals (zinc ramp). bg is one step below surface so cards read as
  // raised without heavy shadows.
  "--bg:#fafafa",
  "--text:#18181b",
  "--text-muted:#52525b",
  "--text-faint:#71717a",
  "--text-placeholder:#9f9fa8",
  // Elevation ramp: bg < surface (cards) < surface-2 (inset/hover) <
  // surface-3 (overlays, popovers).
  "--surface:#ffffff",
  "--surface-2:#f4f4f5",
  "--surface-3:#ffffff",
  "--surface-glass:rgba(255,255,255,0.72)",
  "--surface-glass-strong:rgba(255,255,255,0.85)",
  "--border:rgba(24,24,27,0.08)",
  "--border-strong:rgba(24,24,27,0.14)",
  "--border-solid:#e4e4e7",
  "--hover:#f4f4f5",
  "--hover-subtle:rgba(24,24,27,0.04)",
  "--inverse-bg:#18181b",
  "--inverse-text:#fafafa",
  "--code-bg:#18181b",
  "--code-text:#f4f4f5",
  "--inline-code-bg:rgba(24,24,27,0.06)",
  // Semantic colors. brand = action/active, info = neutral-highlight,
  // success = done, warning = needs-attention/waiting, danger = failed.
  "--brand:#6d56d8",
  "--success:#0f8f78",
  "--danger:#e5484d",
  "--warning:#bf7100",
  "--info:#2f6fde",
  "--shadow-rgb:24 24 27",
  // Elevation shadows, weakest to strongest (card, raised, overlay).
  "--shadow-1:0 1px 2px rgb(24 24 27 / 0.05)",
  "--shadow-2:0 1px 2px rgb(24 24 27 / 0.04), 0 8px 24px rgb(24 24 27 / 0.07)",
  "--shadow-3:0 4px 12px rgb(24 24 27 / 0.10), 0 16px 48px rgb(24 24 27 / 0.14)",
].join("; ");

const darkTokens = [
  "color-scheme:dark",
  "--bg:#09090b",
  "--text:#f4f4f5",
  "--text-muted:#a1a1aa",
  "--text-faint:#71717a",
  "--text-placeholder:#63636b",
  "--surface:#141417",
  "--surface-2:#1b1b20",
  "--surface-3:#232329",
  "--surface-glass:rgba(20,20,23,0.72)",
  "--surface-glass-strong:rgba(20,20,23,0.85)",
  "--border:rgba(255,255,255,0.09)",
  "--border-strong:rgba(255,255,255,0.16)",
  "--border-solid:#2a2a30",
  "--hover:#1f1f24",
  "--hover-subtle:rgba(255,255,255,0.05)",
  "--inverse-bg:#f4f4f5",
  "--inverse-text:#18181b",
  "--code-bg:#0c0c0e",
  "--code-text:#e4e4e7",
  "--inline-code-bg:rgba(255,255,255,0.08)",
  "--brand:#8b78e6",
  "--success:#2ec9a8",
  "--danger:#f2555a",
  "--warning:#e0a23a",
  "--info:#6aa5f8",
  "--shadow-rgb:0 0 0",
  "--shadow-1:0 1px 2px rgb(0 0 0 / 0.35)",
  "--shadow-2:0 1px 2px rgb(0 0 0 / 0.30), 0 8px 24px rgb(0 0 0 / 0.40)",
  "--shadow-3:0 4px 12px rgb(0 0 0 / 0.45), 0 16px 48px rgb(0 0 0 / 0.50)",
].join("; ");

// Theme-invariant tokens: aliases, soft tints (self-adapting color-mix over
// the semantic colors, correct in both themes), geometry, and type scale.
const sharedTokens = [
  // Legacy aliases (do not remove; workflow UIs rely on them).
  "--panel:var(--surface)",
  "--card:var(--surface)",
  "--line:var(--border-solid)",
  "--muted:var(--text-muted)",
  "--primary:var(--brand)",
  "--accent:var(--brand)",
  "--ok:var(--success)",
  "--warn:var(--warning)",
  "--warning-color:var(--warning)",
  "--bad:var(--danger)",
  "--err:var(--danger)",
  "--error:var(--danger)",
  "--blue:var(--info)",
  "--run:var(--brand)",
  "--crit:var(--danger)",
  "--major:var(--warning)",
  "--minor:var(--warning)",
  "--nit:var(--muted)",
  "--me:color-mix(in srgb,var(--brand) 12%,var(--surface))",
  "--ink:var(--inverse-bg)",
  // Soft tints + tint borders for the semantic colors. Use these instead of
  // hand-rolling color-mix percentages so every tinted surface matches.
  "--brand-soft:color-mix(in srgb, var(--brand) 10%, var(--surface))",
  "--brand-soft-strong:color-mix(in srgb, var(--brand) 16%, var(--surface))",
  "--brand-border:color-mix(in srgb, var(--brand) 40%, transparent)",
  "--success-soft:color-mix(in srgb, var(--success) 12%, var(--surface))",
  "--success-border:color-mix(in srgb, var(--success) 40%, transparent)",
  "--danger-soft:color-mix(in srgb, var(--danger) 10%, var(--surface))",
  "--danger-border:color-mix(in srgb, var(--danger) 40%, transparent)",
  "--warning-soft:color-mix(in srgb, var(--warning) 12%, var(--surface))",
  "--warning-border:color-mix(in srgb, var(--warning) 40%, transparent)",
  "--info-soft:color-mix(in srgb, var(--info) 10%, var(--surface))",
  "--info-border:color-mix(in srgb, var(--info) 40%, transparent)",
  "--ring:color-mix(in srgb, var(--brand) 22%, transparent)",
  "--ring-border:color-mix(in srgb, var(--brand) 50%, transparent)",
  // Geometry: 4px spacing scale, type scale, radii, and shared control
  // heights. Use these instead of bare pixel values in workflow-UI CSS.
  "--sp-1:4px",
  "--sp-2:8px",
  "--sp-3:12px",
  "--sp-4:16px",
  "--sp-5:20px",
  "--sp-6:24px",
  "--sp-7:28px",
  "--sp-8:32px",
  "--fs-1:11px",
  "--fs-2:12px",
  "--fs-3:13px",
  "--fs-4:15px",
  "--fs-5:17px",
  "--fs-6:20px",
  "--fs-7:24px",
  "--lh-tight:1.35",
  "--lh-body:1.5",
  "--r-1:6px",
  "--r-2:10px",
  "--r-3:12px",
  "--r-4:16px",
  "--r-full:999px",
  "--ctl-h:32px",
  "--ctl-h-sm:26px",
  "--ctl-h-lg:38px",
].join("; ");

export const workflowUiThemeCss = [
  `:root { ${lightTokens}; ${sharedTokens}; }`,
  `@media (prefers-color-scheme: dark) { :root:not([data-theme='light']) { ${darkTokens}; } }`,
  `:root[data-theme='dark'] { ${darkTokens}; }`,
  "* { box-sizing:border-box; }",
  "body { min-width:320px; min-height:100vh; margin:0; background:var(--bg); color:var(--text); font-size:var(--fs-3); line-height:var(--lh-body); font-synthesis:none; text-rendering:optimizeLegibility; -webkit-font-smoothing:antialiased; -moz-osx-font-smoothing:grayscale; }",
  "::selection { background:color-mix(in srgb, var(--brand) 24%, transparent); }",
  "button,input,textarea,select { font:inherit; }",
  "button { color:inherit; cursor:pointer; }",
  "button:disabled { cursor:not-allowed; }",
  "pre { margin:0; max-width:100%; overflow:auto; }",
  "h1,h2,h3,p { margin:0; }",
  "h1 { color:var(--text); font-size:var(--fs-5); font-weight:650; letter-spacing:-0.01em; line-height:var(--lh-tight); }",
  "h2 { color:var(--text); font-size:var(--fs-4); font-weight:650; letter-spacing:-0.005em; line-height:var(--lh-tight); }",
  "h3 { color:var(--text); font-size:var(--fs-3); font-weight:600; line-height:var(--lh-tight); }",
  "p { color:var(--muted); line-height:1.45; }",
  "code,.mono { font-family:var(--font-mono); }",
  ".muted,.meta { color:var(--muted); }",
  ".top,.topbar { min-width:0; display:flex; align-items:center; justify-content:space-between; gap:16px; padding:12px 18px; border-bottom:1px solid var(--border); background:var(--surface-glass-strong); -webkit-backdrop-filter:blur(18px) saturate(180%); backdrop-filter:blur(18px) saturate(180%); }",
  ".title,.title-group { min-width:0; display:flex; align-items:center; gap:10px; }",
  ".toolbar,.actions { display:flex; align-items:center; justify-content:flex-end; gap:8px; min-width:0; flex-wrap:wrap; }",
  ".button,.primary,.secondary { min-height:var(--ctl-h); display:inline-flex; align-items:center; justify-content:center; gap:6px; padding:0 12px; border:1px solid var(--line); border-radius:var(--r-1); background:var(--panel); color:var(--text); text-decoration:none; cursor:pointer; white-space:nowrap; box-shadow:var(--shadow-1); }",
  ".button:hover,.primary:hover,.secondary:hover { background:var(--hover); }",
  ".button:focus-visible,.primary:focus-visible,.secondary:focus-visible,.icon-button:focus-visible,.tab:focus-visible,.run-row:focus-visible,.doc-link:focus-visible,.segmented:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible { outline:none; border-color:var(--ring-border); box-shadow:0 0 0 3px var(--ring); }",
  ".button:disabled,.primary:disabled,.secondary:disabled { cursor:not-allowed; opacity:.45; }",
  ".button.primary,.primary { border-color:var(--brand-border); background:var(--brand-soft); color:var(--brand); font-weight:650; }",
  ".button.primary:hover,.primary:hover { background:var(--brand-soft-strong); }",
  ".button.danger,.danger { border-color:var(--danger-border); color:var(--danger); }",
  ".button.danger:hover,.danger:hover { background:var(--danger-soft); }",
  ".input,.textarea,.prompt,textarea.prompt,input[type='text'],input[type='search'],input[type='number'],select { min-width:0; border:1px solid var(--line); border-radius:var(--r-1); background:var(--panel); color:var(--text); outline:none; }",
  ".input,.prompt,input[type='text'],input[type='search'],input[type='number'],select { min-height:var(--ctl-h); padding:0 10px; }",
  ".textarea,textarea.prompt,textarea.input,textarea { padding:10px 12px; min-height:88px; resize:vertical; line-height:1.45; }",
  ".input::placeholder,.textarea::placeholder,.prompt::placeholder,textarea::placeholder,input::placeholder { color:var(--text-placeholder); }",
  ".pill,.badge,.chip { display:inline-flex; align-items:center; gap:6px; min-width:0; max-width:100%; min-height:22px; padding:1px 10px; border:1px solid var(--border); border-radius:999px; color:var(--text-muted); font-family:var(--font-mono); font-size:11px; white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }",
  ".pill { border-color:color-mix(in srgb,var(--brand) 22%,transparent); background:color-mix(in srgb,var(--brand) 14%,transparent); color:var(--brand); }",
  ".pill.muted,.badge.muted,.chip { border-color:var(--border); background:var(--hover-subtle); color:var(--text-muted); }",
  ".badge { font-family:inherit; font-weight:650; text-transform:uppercase; }",
  ".badge.ok,.badge.finished,.badge.success { color:var(--success); border-color:var(--success-border); background:var(--success-soft); }",
  ".badge.warn,.badge.pending,.badge.waiting { color:var(--warning); border-color:var(--warning-border); background:var(--warning-soft); }",
  ".badge.running,.badge.run { color:var(--brand); border-color:var(--brand-border); background:var(--brand-soft); }",
  ".badge.info { color:var(--info); border-color:var(--info-border); background:var(--info-soft); }",
  ".badge.bad,.badge.failed { color:var(--danger); border-color:var(--danger-border); background:var(--danger-soft); }",
  ".badge.cancelled,.badge.canceled,.badge.skipped { color:var(--muted); border-color:var(--border); background:var(--hover-subtle); }",
  ".card,.panel,.kpi,.stat,.slot { min-width:0; border:1px solid var(--border); border-radius:var(--r-2); background:var(--surface); box-shadow:var(--shadow-2); }",
  ".card,.panel,.slot { padding:14px; }",
  ".card-head,.panel-title,.section-head { min-width:0; display:flex; align-items:center; justify-content:space-between; gap:10px; }",
  ".section-head,.label,.field label,.field span { color:var(--muted); font-size:11px; font-weight:650; text-transform:uppercase; letter-spacing:.05em; }",
  ".field { min-width:0; display:grid; gap:5px; }",
  ".empty { padding:24px; color:var(--muted); text-align:center; }",
  ".alert { border:1px solid var(--border); border-radius:var(--r-2); padding:12px; background:var(--surface); color:var(--muted); }",
  ".alert.err,.error-text { color:var(--danger); border-color:var(--danger-border); }",
  ".run-row { border-color:var(--border); color:var(--text); transition:border-color .12s ease, background .12s ease; }",
  ".run-row:hover,.run-row.active,.run-row.is-active { background:var(--hover); }",
  ".run-row.active,.run-row.is-active { border-color:var(--brand-border); box-shadow:inset 2px 0 0 var(--brand); }",
  ".table { width:100%; border-collapse:collapse; }",
  ".table th,.table td { padding:8px 9px; border-bottom:1px solid var(--border); text-align:left; vertical-align:top; }",
  ".table th { color:var(--muted); font-size:11px; text-transform:uppercase; letter-spacing:.04em; font-weight:700; }",
  ".code,.source,pre.code { display:block; min-width:0; overflow:auto; white-space:pre-wrap; font-family:var(--font-mono); font-size:11px; line-height:1.55; color:var(--code-text); background:var(--code-bg); border:1px solid var(--border); border-radius:var(--r-2); padding:10px; }",
  ".plus { color:var(--success); } .minus { color:var(--danger); }",
  ".livelog { overflow:auto; background:var(--code-bg); border:1px solid var(--border); border-radius:var(--r-2); padding:8px; font-family:var(--font-mono); font-size:11px; line-height:1.55; }",
  ".livelog-line { display:flex; gap:8px; padding:1px 0; white-space:pre-wrap; word-break:break-word; }",
  ".livelog-event { color:var(--brand); flex:none; }",
  ".livelog-node { color:var(--warning); flex:none; }",
  ".livelog-detail { color:var(--code-text); min-width:0; }",
  "* { scrollbar-width:thin; scrollbar-color:color-mix(in srgb,var(--text-muted) 35%,transparent) transparent; }",
  "@media (max-width: 760px) { .top,.topbar { align-items:flex-start; flex-direction:column; padding:10px 12px; } .toolbar,.actions { width:100%; justify-content:flex-start; } .button,.primary,.secondary { min-width:0; } }",
].join("\n");

export const workflowUiLayoutCss = [
  ".workflow-shell { height:100vh; width:100%; max-width:100vw; overflow:hidden; display:grid; grid-template-rows:auto 1fr; background:var(--bg); color:var(--text); }",
  ".workflow-content { min-width:0; min-height:0; overflow:auto; padding:16px 18px; display:grid; align-content:start; gap:14px; }",
  ".workflow-launch { display:grid; grid-template-columns:minmax(0,1fr) auto; gap:8px; align-items:start; }",
  ".workflow-dashboard { min-width:0; min-height:0; display:grid; grid-template-columns:minmax(240px,320px) minmax(0,1fr); gap:14px; align-items:start; }",
  ".workflow-runs { display:grid; align-content:start; gap:8px; }",
  ".workflow-run-row { min-width:0; display:flex; align-items:center; justify-content:space-between; gap:12px; width:100%; padding:10px 12px; border:1px solid var(--border); border-radius:var(--r-2); background:var(--surface); color:var(--text); text-align:left; cursor:pointer; box-shadow:var(--shadow-1); }",
  ".workflow-run-row:hover,.workflow-run-row.active { background:var(--hover); border-color:var(--brand-border); }",
  ".workflow-run-row.active { box-shadow:inset 2px 0 0 var(--brand), var(--shadow-1); }",
  ".workflow-run-main { min-width:0; display:grid; gap:3px; }",
  ".workflow-run-id { min-width:0; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; font-family:var(--font-mono); font-size:12px; }",
  ".workflow-run-meta { color:var(--muted); font-size:11px; }",
  ".workflow-detail { min-width:0; display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:14px; }",
  ".workflow-detail .panel { display:grid; gap:10px; }",
  ".workflow-tree,.workflow-events { min-height:220px; max-height:52vh; }",
  "@media (max-width: 980px) { .workflow-dashboard,.workflow-detail { grid-template-columns:1fr; } .workflow-tree,.workflow-events { max-height:360px; } }",
  "@media (max-width: 620px) { .workflow-content { padding:12px; } .workflow-launch { grid-template-columns:1fr; } .workflow-launch .button { width:100%; } }",
].join("\n");

export const workflowUiStyles = [workflowUiThemeCss, workflowUiLayoutCss].join("\n");
