/**
 * One document-wide motion policy for every house stylesheet and consumer CSS.
 * Keeping this selector global means late-injected adapter styles, monitor
 * animations, and component transitions inherit the same preference without
 * component-specific media queries.
 */
export const reducedMotionCss = `@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after { animation-delay:0ms !important; animation-duration:0.001ms !important; animation-iteration-count:1 !important; scroll-behavior:auto !important; transition-delay:0ms !important; transition-duration:0.001ms !important; }
}`;

const lightTokens = [
  "color-scheme:light",
  "--font-sans:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif",
  "--font-mono:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace",
  "--bg:#fafafa",
  "--text:#18181b",
  "--text-muted:#52525b",
  "--text-faint:#6d6d75",
  "--text-placeholder:#8a8a93",
  "--surface:#ffffff",
  "--surface-2:#f4f4f5",
  "--surface-3:#ffffff",
  "--border:rgba(24,24,27,0.08)",
  "--border-strong:rgba(24,24,27,0.14)",
  "--border-solid:#e4e4e7",
  "--hover:#f4f4f5",
  "--hover-subtle:rgba(24,24,27,0.04)",
  "--inverse-bg:#18181b",
  "--inverse-text:#fafafa",
  "--code-bg:#18181b",
  "--code-text:#f4f4f5",
  "--inline-code-bg:rgba(24,24,27,0.06)",
  "--brand:#6d56d8",
  "--success:#087461",
  "--danger:#c5343f",
  "--warning:#916000",
  "--info:#2a63c9",
  "--shadow-rgb:24 24 27",
  "--shadow-1:0 1px 2px rgb(24 24 27 / 0.05)",
  "--shadow-2:0 1px 2px rgb(24 24 27 / 0.04),0 8px 24px rgb(24 24 27 / 0.07)",
].join("; ");

const darkTokens = [
  "color-scheme:dark",
  "--bg:#09090b",
  "--text:#f4f4f5",
  "--text-muted:#a1a1aa",
  "--text-faint:#8c8c95",
  "--text-placeholder:#75757e",
  "--surface:#141417",
  "--surface-2:#1b1b20",
  "--surface-3:#232329",
  "--border:rgba(255,255,255,0.09)",
  "--border-strong:rgba(255,255,255,0.16)",
  "--border-solid:#2a2a30",
  "--hover:#1f1f24",
  "--hover-subtle:rgba(255,255,255,0.05)",
  "--inverse-bg:#f4f4f5",
  "--inverse-text:#18181b",
  "--code-bg:#0c0c0e",
  "--code-text:#e4e4e7",
  "--inline-code-bg:rgba(255,255,255,0.08)",
  "--brand:#8b78e6",
  "--success:#2ec9a8",
  "--danger:#f2555a",
  "--warning:#e0a23a",
  "--info:#6aa5f8",
  "--shadow-rgb:0 0 0",
  "--shadow-1:0 1px 2px rgb(0 0 0 / 0.35)",
  "--shadow-2:0 1px 2px rgb(0 0 0 / 0.30),0 8px 24px rgb(0 0 0 / 0.40)",
].join("; ");

const sharedTokens = [
  "--panel:var(--surface)",
  "--card:var(--surface)",
  "--line:var(--border-solid)",
  "--muted:var(--text-muted)",
  "--primary:var(--brand)",
  "--accent:var(--brand)",
  "--ok:var(--success)",
  "--warn:var(--warning)",
  "--bad:var(--danger)",
  "--err:var(--danger)",
  "--error:var(--danger)",
  "--blue:var(--info)",
  "--brand-soft:color-mix(in srgb,var(--brand) 10%,var(--surface))",
  "--brand-soft-strong:color-mix(in srgb,var(--brand) 16%,var(--surface))",
  "--brand-border:color-mix(in srgb,var(--brand) 40%,transparent)",
  "--success-soft:color-mix(in srgb,var(--success) 12%,var(--surface))",
  "--success-border:color-mix(in srgb,var(--success) 40%,transparent)",
  "--danger-soft:color-mix(in srgb,var(--danger) 10%,var(--surface))",
  "--danger-border:color-mix(in srgb,var(--danger) 40%,transparent)",
  "--warning-soft:color-mix(in srgb,var(--warning) 12%,var(--surface))",
  "--warning-border:color-mix(in srgb,var(--warning) 40%,transparent)",
  "--info-soft:color-mix(in srgb,var(--info) 10%,var(--surface))",
  "--info-border:color-mix(in srgb,var(--info) 40%,transparent)",
  "--ring:color-mix(in srgb,var(--brand) 22%,transparent)",
  "--ring-border:color-mix(in srgb,var(--brand) 50%,transparent)",
  "--sp-1:4px",
  "--sp-2:8px",
  "--sp-3:12px",
  "--sp-4:16px",
  "--sp-5:20px",
  "--sp-6:24px",
  "--sp-7:28px",
  "--sp-8:32px",
  "--fs-1:11px",
  "--fs-2:12px",
  "--fs-3:13px",
  "--fs-4:15px",
  "--fs-5:17px",
  "--fs-6:20px",
  "--fs-7:24px",
  "--lh-tight:1.35",
  "--lh-body:1.5",
  "--r-1:6px",
  "--r-2:10px",
  "--r-3:12px",
  "--r-4:16px",
  "--r-bubble:18px",
  "--r-full:999px",
  "--ctl-h:32px",
  "--ctl-h-sm:28px",
  "--ctl-h-lg:38px",
].join("; ");

/** A complete theme for HTML that is rendered outside a Smithers UI shell. */
export function standaloneThemeCss(): string {
  return [
    `:root { ${lightTokens}; ${sharedTokens}; }`,
    `@media (prefers-color-scheme: dark) { :root:not([data-theme="light"]) { ${darkTokens}; } }`,
    `:root[data-theme="dark"] { ${darkTokens}; }`,
    `* { box-sizing:border-box; } body { min-width:320px; min-height:100vh; margin:0; font-family:var(--font-sans); background:var(--bg); color:var(--text); line-height:1.5; } h1,h2,h3 { color:var(--text); line-height:1.25; } a { color:var(--brand); } code:not(:where(.pierre-diff *)) { font-family:var(--font-mono); background:var(--inline-code-bg); color:var(--text); padding:.1em .3em; border-radius:4px; } pre:not(:where(.pierre-diff *)) { overflow:auto; background:var(--code-bg); color:var(--code-text); padding:1em; border-radius:6px; } pre:not(:where(.pierre-diff *)) code:not(:where(.pierre-diff *)) { padding:0; background:var(--code-bg); color:var(--code-text); } table { width:100%; border-collapse:collapse; } th,td { border-bottom:1px solid var(--border); padding:.5em; text-align:left; } hr { border:0; border-top:1px solid var(--border); }`,
    reducedMotionCss,
  ].join("\n");
}
