// Build the deployable site assets.
//
// 1. Assembles site/index.html from page/index.template.html by lifting the
//    <style> and <main> of the tab-1 reference document verbatim.
// 2. Copies page/demo.js to site/.
// 3. Serializes project/ into site/project-files.js as a WebContainer
//    FileSystemTree, which the page mounts into the container.
//
// site/webcontainer-api.js is produced separately by esbuild; see README.md.
//
// Run: node apps/stereos-site/build.mjs
import { copyFile, readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const projectDir = join(here, "project");
const siteDir = join(here, "site");

/**
 * Read a directory into a WebContainer FileSystemTree.
 * @param {string} dir
 * @returns {Promise<Record<string, unknown>>}
 */
async function readTree(dir) {
  const tree = {};
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name.startsWith(".")) {
      continue;
    }
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      tree[entry.name] = { directory: await readTree(full) };
    } else {
      tree[entry.name] = { file: { contents: await readFile(full, "utf8") } };
    }
  }
  return tree;
}

await mkdir(siteDir, { recursive: true });
const tree = await readTree(projectDir);
await writeFile(
  join(siteDir, "project-files.js"),
  `// Generated by apps/stereos-site/build.mjs. Do not edit.\nexport const projectFiles = ${JSON.stringify(tree, null, 2)};\n`,
);

// Tab 1 is the reference document, unedited. Lift its styles and its <main>
// so the prose and the Shiki markup stay byte-identical to the source.
const reference = await readFile(join(here, "tab1-source/stereos-sandbox-provider.html"), "utf8");
const styleMatch = reference.match(/<style>([\s\S]*?)<\/style>/);
const mainMatch = reference.match(/<main>[\s\S]*?<\/main>/);
if (!styleMatch || !mainMatch) {
  throw new Error("reference document is missing its <style> or <main>");
}
const template = await readFile(join(here, "page/index.template.html"), "utf8");
await writeFile(
  join(siteDir, "index.html"),
  template.replace("__REFERENCE_STYLE__", styleMatch[1].trim()).replace("__REFERENCE_MAIN__", mainMatch[0]),
);
await copyFile(join(here, "page/demo.js"), join(siteDir, "demo.js"));

let count = 0;
const walk = (node) => {
  for (const value of Object.values(node)) {
    if (value.directory) {
      walk(value.directory);
    } else {
      count += 1;
    }
  }
};
walk(tree);
console.log(`project-files.js: ${count} files`);
