/**
 * The generated theme files, against the generator that writes them.
 *
 * `src/themes/*.ts` (fucory excepted) are emitted by
 * `packages/smithers/ui/ui-styleguide/scripts/generate-theme-registry.ts`. Two things can drift, and a reader of
 * the files alone cannot see either:
 *
 * 1. A hand edit to a generated file survives until the next regeneration
 *    silently reverts it. The extension on the emitted import specifier is
 *    exactly that case: `apps/review` loads this package under Node ESM, where
 *    a relative specifier without `.ts` does not resolve, and a fix applied to
 *    the files instead of to the generator lasts until someone re-runs it.
 * 2. The upstream themes move and the checked-in registry stops matching what
 *    the generator would write from them.
 *
 * The generator's `--check` mode compares its own output to the files byte for
 * byte and writes nothing, so this test is that comparison.
 */
import { describe, expect, test } from "bun:test";
import { createRequire } from "node:module";
import { spawnSync } from "node:child_process";
import { cpSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, symlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { nodeExecutable } from "./nodeBinary.ts";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repositoryRoot = resolve(packageRoot, "../../../..");
const themesDir = join(packageRoot, "src/themes");

describe("the generated theme registry", () => {
  test("declares and resolves its own pinned Shiki input", () => {
    const manifest = JSON.parse(readFileSync(join(packageRoot, "package.json"), "utf8"));
    expect(manifest.devDependencies?.["@shikijs/themes"]).toBe("4.4.3");
    const local = createRequire(join(packageRoot, "package.json"));
    const upstream = JSON.parse(readFileSync(resolve(dirname(local.resolve("@shikijs/themes")), "../package.json"), "utf8"));
    expect(upstream.version).toBe(manifest.devDependencies["@shikijs/themes"]);
    expect(local.resolve("@shikijs/themes/night-owl")).toContain("night-owl");
  });

  test("records the resolved Shiki version in every generated banner and the source docs", () => {
    const local = createRequire(join(packageRoot, "package.json"));
    const { version } = JSON.parse(readFileSync(resolve(dirname(local.resolve("@shikijs/themes")), "../package.json"), "utf8"));
    const generated = readdirSync(themesDir).filter((file) => file.endsWith(".ts") && file !== "fucory.ts");
    expect(generated).toHaveLength(7);
    for (const file of generated) {
      expect(readFileSync(join(themesDir, file), "utf8").split("\n")[0])
        .toBe(`// Generated by packages/smithers/ui/ui-styleguide/scripts/generate-theme-registry.ts from @shikijs/themes ${version}. Do not edit.`);
    }
    expect(readFileSync(join(packageRoot, "docs/concepts/palette-sources.md"), "utf8"))
      .toContain(`reads \`@shikijs/themes\` ${version}`);
  });

  test("matches what the generator writes today, byte for byte", () => {
    // Node, not the Bun that runs this suite: the generator is a Node script,
    // and running it under a different runtime would compare this package
    // against output nobody regenerates it with.
    const result = spawnSync(
      nodeExecutable,
      ["--experimental-strip-types", "packages/smithers/ui/ui-styleguide/scripts/generate-theme-registry.ts", "--check"],
      { cwd: repositoryRoot, encoding: "utf8" },
    );
    expect(`${result.stdout ?? ""}${result.stderr ?? ""}`.trim()).toBe("");
    expect(result.status).toBe(0);
  }, 120_000);

  test("checks generation with only this package and its declared Shiki dependency", () => {
    const isolatedRoot = mkdtempSync(join(tmpdir(), "ui-styleguide-generation-"));
    try {
      const isolatedPackage = join(isolatedRoot, "packages/smithers/ui/ui-styleguide");
      mkdirSync(isolatedPackage, { recursive: true });
      for (const entry of ["src", "scripts", "package.json"]) {
        cpSync(join(packageRoot, entry), join(isolatedPackage, entry), { recursive: true });
      }
      const local = createRequire(join(packageRoot, "package.json"));
      const upstreamRoot = resolve(dirname(local.resolve("@shikijs/themes")), "..");
      const scope = join(isolatedPackage, "node_modules/@shikijs");
      mkdirSync(scope, { recursive: true });
      symlinkSync(upstreamRoot, join(scope, "themes"), "junction");
      const result = spawnSync(nodeExecutable, [
        "--experimental-strip-types", join(isolatedPackage, "scripts/generate-theme-registry.ts"), "--check",
      ], { cwd: isolatedRoot, encoding: "utf8" });
      expect(`${result.stdout ?? ""}${result.stderr ?? ""}`.trim()).toBe("");
      expect(result.status).toBe(0);
    } finally {
      rmSync(isolatedRoot, { recursive: true, force: true });
    }
  }, 120_000);

  test("imports the theme type with the extension Node ESM resolves", () => {
    // Generated files only. A hand-written theme's specifiers are that file's
    // own; only these are rewritten by a regeneration.
    const generated = readdirSync(themesDir)
      .filter((file) => file.endsWith(".ts"))
      .map((file) => [file, readFileSync(join(themesDir, file), "utf8")] as const)
      .filter(([, source]) => source.startsWith("// Generated by packages/smithers/ui/ui-styleguide/scripts/generate-theme-registry.ts"));
    expect(generated.length).toBe(7);
    expect(generated.filter(([, source]) => source.includes('from "../SmithersTheme"')).map(([file]) => file))
      .toEqual([]);
  });
});
