/**
 * `smithers docs`, which prints what shipped rather than what is online.
 */
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { afterEach, describe, expect, it } from "vitest"
import * as Docs from "../src/Docs.ts"

const staged: Array<string> = []

const bundleDirectory = (): string => {
  const root = mkdtempSync(join(tmpdir(), "smithers-docs-"))
  staged.push(root)
  return root
}

afterEach(() => {
  while (staged.length > 0) rmSync(staged.pop()!, { recursive: true, force: true })
})

describe("the shipped bundles", () => {
  it("names the index and the full bundle", () => {
    expect(Docs.bundles).toEqual({ index: "llms.txt", full: "llms-full.txt" })
  })

  it("resolves the bundle directory from the installed module, not the working directory", () => {
    // `smithers docs` run inside a user's project must print this release's
    // documentation, not look for a `docs/` beside their code.
    expect(Docs.directory("file:///opt/smithers/src/Docs.ts")).toBe(join("/opt/smithers", "docs"))
    expect(Docs.file(false, "/opt/docs")).toBe(join("/opt/docs", "llms.txt"))
    expect(Docs.file(true, "/opt/docs")).toBe(join("/opt/docs", "llms-full.txt"))
  })

  it("resolves to the same directory from the built entry as from the source entry", () => {
    // `package.json` ships `docs/**` at the package root and `dist/**` beside
    // it, so a published install runs `dist/esm/Docs.js` and must still find
    // `<package>/docs`. Counting one `..` sent it to `<package>/dist/docs`,
    // where nothing is published, and `smithers docs` reported the bundle
    // missing on every install that was not a source checkout.
    expect(Docs.directory("file:///opt/smithers/dist/esm/Docs.js")).toBe(join("/opt/smithers", "docs"))
    expect(Docs.packageRoot("file:///opt/smithers/dist/esm/Docs.js")).toBe("/opt/smithers")
    expect(Docs.packageRoot("file:///opt/smithers/src/Docs.ts")).toBe("/opt/smithers")
  })

  it("reads the index and the full bundle", () => {
    const root = bundleDirectory()
    writeFileSync(join(root, "llms.txt"), "# index\n")
    writeFileSync(join(root, "llms-full.txt"), "# everything\n")

    expect(Docs.read(false, root)).toEqual({ text: "# index\n", found: true })
    expect(Docs.read(true, root)).toEqual({ text: "# everything\n", found: true })
  })

  it("names the command that produces a missing bundle", () => {
    const root = bundleDirectory()

    const missing = Docs.read(false, root)

    // A source checkout before `pnpm docs:llms` is the ordinary case, not a
    // defect, so the message is instructions rather than an error.
    expect(missing.found).toBe(false)
    expect(missing.text).toContain("pnpm docs:llms")
    expect(missing.text).toContain(join(root, "llms.txt"))
    expect(missing.text).toContain("https://smithers.sh")
  })

  it("resolves against the real package by default", () => {
    // The bundle is generated by the docs lane, so its presence is not
    // asserted here; the path it would be read from is.
    expect(Docs.file(false)).toMatch(/docs[/\\]llms\.txt$/)
    mkdirSync(bundleDirectory(), { recursive: true })
  })
})
