#!/usr/bin/env node
/**
 * Generates this package's own reference material from its sources.
 *
 * `@smthrs/targets` is private and has no page on the documentation site, so
 * its generated output stays inside the package: `docs/rules.md` is the
 * inventory of every catalog rule, read straight out of the `Target.make`
 * declarations in `src/`, and `docs/README.md` and `docs/api.md` are the
 * hand-written prose it sits beside.
 *
 * Default run writes; `--check` reports drift and exits 1, which is what the
 * `//packages/targets:docsPages` target and `scripts/check-docs.mjs` run.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const packageRoot = dirname(dirname(fileURLToPath(import.meta.url)))
const sourceDirectory = join(packageRoot, "src")
const generated = join(packageRoot, "docs", "rules.md")

/** One `Target.make("<id>", { ... kinds: [...] })` declaration. */
const declarations = () => {
  const found = []
  for (const entry of readdirSync(sourceDirectory).sort()) {
    if (!entry.endsWith(".ts")) continue
    const text = readFileSync(join(sourceDirectory, entry), "utf8")
    // The declaration head plus everything up to the first `kinds:` line. The
    // scan is deliberately shallow: a rule that does not spell its kinds as a
    // literal array is a rule whose verbs are not readable here, and that is
    // reported rather than guessed at.
    const pattern = /Target\.make\(\s*"([^"]+)"\s*,\s*\{([^]*?)\n\}\)/g
    for (const match of text.matchAll(pattern)) {
      const id = match[1]
      const body = match[2]
      // `Alias` and `Materialize` mirror the verbs of the target they wrap,
      // so their kinds are a variable rather than a literal and the table says
      // so instead of inventing a list.
      const literalKinds = /kinds:\s*\[([^\]]*)\]/.exec(body)
      const mirroredKinds = /\n\s{4}kinds,/.test(body)
      const cached = /\n\s{2}cache:\s*(true|false|\()/.exec(body)
      const outputs = /\n\s{2}outputs:/.test(body)
      const notImplemented = body.includes("Target.notImplemented")
      found.push({
        id,
        module: entry.replace(/\.ts$/, ""),
        kinds: literalKinds !== null
          ? literalKinds[1].split(",").map((kind) => kind.trim().replaceAll("\"", "")).filter(Boolean).join(", ") ||
            "none"
          : mirroredKinds
          ? "mirrors its target"
          : "unreadable",
        cache: cached === null ? "no" : cached[1] === "true" ? "yes" : cached[1] === "false" ? "no" : "by attrs",
        outputs: outputs ? "yes" : "no",
        route: notImplemented ? "package executor" : "flow body"
      })
    }
  }
  return found.sort((left, right) => left.id.localeCompare(right.id))
}

const render = (rules) => {
  const rows = rules.map((rule) =>
    `| \`${rule.id}\` | ${rule.module} | ${rule.kinds} | ${rule.cache} | ${rule.outputs} | ${rule.route} |`
  )
  return [
    "<!-- Generated by packages/targets/scripts/docs.mjs. Edit the sources, never this file. -->",
    "",
    "# Catalog rules",
    "",
    "Every rule `Target.make` declares in this package, with the verbs it",
    "participates in, whether its results may be replayed from the cache,",
    "whether it declares an output tree, and which route executes it. A",
    "`package executor` rule plans `Target.notImplemented` as its Flow body, so",
    "running one under a bare Flow runtime fails loudly instead of doing nothing.",
    "",
    "| Rule | Module | Verbs | Cacheable | Declares outputs | Route |",
    "| --- | --- | --- | --- | --- | --- |",
    ...rows,
    "",
    `${rules.length} rules.`,
    ""
  ].join("\n")
}

const rules = declarations()
if (rules.length === 0) throw new Error("packages/targets/scripts/docs.mjs found no Target.make declarations")
const unreadable = rules.filter((rule) => rule.kinds === "unreadable")
if (unreadable.length > 0) {
  throw new Error(`rules with unreadable kinds: ${unreadable.map((rule) => rule.id).join(", ")}`)
}
const next = render(rules)
if (next.includes("—")) throw new Error("generated documentation must not contain em-dashes")

if (process.argv.includes("--check")) {
  let current
  try {
    current = readFileSync(generated, "utf8")
  } catch {
    current = undefined
  }
  if (current !== next) {
    console.error("packages/targets/docs/rules.md is out of date; run node packages/targets/scripts/docs.mjs")
    process.exit(1)
  }
} else {
  writeFileSync(generated, next)
}
