#!/usr/bin/env node
/** Projects package-owned trigger documentation into the package README. */
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { Package } from "../Package.ts"

const check = process.argv.includes("--check")
const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const repoRoot = join(packageRoot, "..", "..")
const read = (path) => readFileSync(path, "utf8")

const ungutter = (block) =>
  block.split("\n").map((line) => line.replace(/^\s*\* ?/, "")).join("\n")

const description = (body) => {
  const lines = []
  for (const line of body.split("\n")) {
    if (/^@\w+/.test(line)) break
    lines.push(line)
  }
  return lines.join("\n").trim()
}

const delink = (value) =>
  value.replace(/\{@link\s+([^}]+)\}/g, "`$1`").replaceAll(" — ", ", ").replaceAll("—", "-")

const paragraphs = (value) => {
  const blocks = []
  let current = []
  for (const line of value.split("\n")) {
    if (line.trim() === "") {
      if (current.length > 0) blocks.push(current.join(" "))
      current = []
    } else current.push(line.trim())
  }
  if (current.length > 0) blocks.push(current.join(" "))
  return blocks.join("\n\n")
}

const firstSentence = (value) => {
  const flat = delink(value).split("\n\n")[0].split("\n").join(" ")
  return (/^[\s\S]*?\.(?=\s|$)/.exec(flat)?.[0] ?? flat).trim()
}

const moduleDoc = (source) => {
  const match = /\/\*\*((?:[^*]|\*(?!\/))*)\*\//.exec(source)
  if (match === null) throw new Error("triggers docs: no module JSDoc block")
  return delink(description(ungutter(match[1])))
}

/**
 * The comment pattern must not span two blocks, hence
 * `(?:[^*]|\*(?!\/))*`. A lazy wildcard can pair one block's opening with a
 * later block's close and attach the wrong summary to an export.
 */
const exportedDocs = (source) => {
  const entries = []
  const pattern =
    /\/\*\*((?:[^*]|\*(?!\/))*)\*\/\s*\nexport (type|const|class|interface|function) (\w+)/g
  for (let match = pattern.exec(source); match !== null; match = pattern.exec(source)) {
    const body = ungutter(match[1])
    const category = /@category (\S+)/.exec(body)?.[1]
    if (category === undefined) continue
    entries.push({
      name: match[3],
      declaration: match[2],
      category,
      summary: firstSentence(description(body))
    })
  }
  return entries
}

const manifest = JSON.parse(read(join(packageRoot, "package.json")))
if (manifest.name !== Package.name) {
  throw new Error("triggers docs: Package.ts and package.json names differ")
}

const barrel = read(join(packageRoot, "src", "index.ts"))
const summary = paragraphs(moduleDoc(barrel))
const modules = [...barrel.matchAll(/export \* as (\w+) from "\.\/([^\"]+)\.ts"/g)].map(
  (match) => ({ namespace: match[1], file: match[2] })
)
if (modules.length === 0) {
  throw new Error("triggers docs: no namespace re-exports found in src/index.ts")
}

const exports = modules.flatMap((module) =>
  exportedDocs(read(join(packageRoot, "src", `${module.file}.ts`))).map((entry) => ({
    ...entry,
    namespace: module.namespace
  }))
)
if (exports.length === 0) throw new Error("triggers docs: no documented exports found")

const tableRows = [
  ["Export", "Kind", "Category", "Summary"],
  ...exports.map((entry) => [
    `\`${entry.namespace}.${entry.name}\``,
    entry.declaration,
    entry.category,
    entry.summary
  ])
]
const tableWidths = tableRows[0].map((_, index) =>
  Math.max(...tableRows.map((row) => row[index].length))
)
const tableRow = (row) =>
  `| ${row.map((cell, index) => cell.padEnd(tableWidths[index])).join(" | ")} |`
const table = [
  tableRow(tableRows[0]),
  `| ${tableWidths.map((width) => "-".repeat(width)).join(" | ")} |`,
  ...tableRows.slice(1).map(tableRow)
].join("\n")

const content = `# @smthrs/triggers

${manifest.description}

{/* Generated by packages/triggers/scripts/docs.mjs. Edit package sources, never this file. */}

${read(join(packageRoot, Package.api.source)).trim()}

## Public API

${summary}

${table}
`

const failures = []
if (content.includes("—")) {
  failures.push(`${Package.api.target}: generated content contains an em-dash`)
}

const target = join(repoRoot, Package.api.target)
const drifted = read(target) !== content
if (drifted) {
  if (check) {
    failures.push(
      `${Package.api.target}: drifted; run node packages/triggers/scripts/docs.mjs`
    )
  } else {
    writeFileSync(target, content)
    console.log(`wrote ${Package.api.target}`)
  }
}

if (failures.length > 0) {
  for (const failure of failures) console.error(`✗ ${failure}`)
  process.exit(1)
}

console.log(
  check
    ? "✓ the triggers package documentation is current"
    : drifted
    ? "✓ triggers package documentation regenerated"
    : "✓ triggers package documentation already current"
)
