#!/usr/bin/env node
/**
 * Projects package-owned step-cache documentation into the repository site.
 *
 * The published page is the package's own JSDoc plus `docs/api.md`. Every
 * export carrying an `@category` tag reaches the reference table, so a new
 * public name is documented by tagging it and a renamed one cannot leave a
 * stale row behind.
 */
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { Manifest } from "../docs/Manifest.ts"

const check = process.argv.includes("--check")
const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const repoRoot = join(packageRoot, "..", "..")
const read = (path) => readFileSync(path, "utf8")

const ungutter = (block) => block.split("\n").map((line) => line.replace(/^\s*\* ?/, "")).join("\n")

const description = (body) => {
  const lines = []
  for (const line of body.split("\n")) {
    if (/^@\w+/.test(line)) break
    lines.push(line)
  }
  return lines.join("\n").trim()
}

// `{@link https://… | text}` is a real link on the page; every other form names
// a symbol, which the page renders as code rather than as a dead link.
const delink = (value) =>
  value
    .replace(/\{@link\s+(https?:\/\/\S+)\s*\|\s*([^}]+)\}/g, (_, url, text) => `[${text.trim()}](${url})`)
    .replace(/\{@link\s+(https?:\/\/\S+?)\s*\}/g, (_, url) => `<${url}>`)
    .replace(/\{@link\s+([^}|]+)\|([^}]+)\}/g, (_, __, text) => `\`${text.trim()}\``)
    .replace(/\{@link\s+([^}]+)\}/g, (_, symbol) => `\`${symbol.trim()}\``)

const firstSentence = (value) => {
  const flat = delink(value).split("\n\n")[0].split("\n").join(" ")
  return (/^[\s\S]*?\.(?=\s|$)/.exec(flat)?.[0] ?? flat).trim()
}

const moduleDoc = (source) => {
  const match = /\/\*\*([\s\S]*?)\*\//.exec(source)
  if (match === null) throw new Error("step-cache docs: no module JSDoc block")
  return delink(description(ungutter(match[1])))
}

const exportedDocs = (source) => {
  const entries = []
  const pattern = /\/\*\*((?:[^*]|\*(?!\/))*)\*\/\s*\nexport (type|const|class|interface) (\w+)/g
  for (let match = pattern.exec(source); match !== null; match = pattern.exec(source)) {
    const body = ungutter(match[1])
    const category = /@category (\S+)/.exec(body)?.[1]
    if (category === undefined) continue
    entries.push({
      name: match[3],
      declaration: match[2],
      category,
      summary: firstSentence(description(body))
    })
  }
  return entries
}

const manifest = JSON.parse(read(join(packageRoot, "package.json")))
if (manifest.name !== Manifest.name) throw new Error("step-cache docs: Manifest.ts and package.json names differ")

const barrel = read(join(packageRoot, "src", "index.ts"))
const namespaces = [...barrel.matchAll(/export \* as (\w+) from "\.\/(\w+)\.ts"/g)].map((match) => ({
  namespace: match[1],
  source: `src/${match[2]}.ts`,
  specifier: `${Manifest.name}/${match[2]}`,
  platform: "any"
}))

const table = (exports) =>
  [
    "| Export | Kind | Summary |",
    "| --- | --- | --- |",
    ...exports.map((entry) => `| \`${entry.name}\` (${entry.declaration}) | ${entry.category} | ${entry.summary} |`)
  ].join("\n")

const section = (entry) => {
  const exports = exportedDocs(read(join(packageRoot, entry.source)))
  if (exports.length === 0) throw new Error(`step-cache docs: ${entry.source} documents no exports`)
  const platform = entry.platform === "any" ? "" : ` ${entry.platform} only.`
  return `### ${entry.namespace}

\`${entry.specifier}\`, [${entry.source}](https://github.com/smithersai/smithers/blob/main/packages/step-cache/${entry.source}).${platform}

${table(exports)}`
}

const sections = [...namespaces, ...Manifest.subpaths].map(section).join("\n\n")

const apiPage = `---
description: "${manifest.description}."
---

{/* Generated by \`node packages/step-cache/scripts/docs.mjs\` from packages/step-cache. Edit package sources, never this file. */}

# @smthrs/step-cache

${moduleDoc(barrel)}

${read(join(packageRoot, Manifest.api.source)).trim()}

## Exports

Each namespace below is reachable from the root barrel and from its own
subpath, except the Node-only test layer, which has only its subpath.

${sections}
`

const outputs = new Map([[Manifest.api.target, apiPage]])

const failures = []
for (const path of Manifest.references) {
  const content = read(join(repoRoot, path))
  if (!content.includes(Manifest.name) || !content.includes("/api/step-cache")) {
    failures.push(`${path}: must reference ${Manifest.name} and /api/step-cache`)
  }
}
for (const [path, content] of outputs) {
  if (content.includes("—")) failures.push(`${path}: generated content contains an em-dash`)
}

let drifted = false
for (const [path, content] of outputs) {
  const absolute = join(repoRoot, path)
  if (read(absolute) === content) continue
  drifted = true
  if (check) failures.push(`${path}: drifted; run node packages/step-cache/scripts/docs.mjs`)
  else {
    writeFileSync(absolute, content)
    console.log(`wrote ${path}`)
  }
}

if (failures.length > 0) {
  for (const failure of failures) console.error(`✗ ${failure}`)
  process.exit(1)
}

console.log(
  check
    ? "✓ the step-cache package documentation is current"
    : drifted
    ? "✓ step-cache package documentation regenerated"
    : "✓ step-cache package documentation already current"
)
