/**
 * <TweetThread> — Post a pre-generated countdown tweet thread to X/Twitter.
 *
 * Set these env vars:
 *   X_API_KEY, X_API_SECRET, X_ACCESS_TOKEN, X_ACCESS_SECRET
 */
import { Sequence, Timer } from "smithers-orchestrator";
import { createExampleSmithers } from "./_example-kit.js";
import { z } from "zod";

const tweetPostSchema = z.object({
  tweetId: z.string(),
  posted: z.boolean(),
  error: z.string().optional(),
});

const { Workflow, Task, smithers, outputs } = createExampleSmithers({
  tweetPost: tweetPostSchema,
});

const tweets = [
  "Smithers is open-source AI workflow orchestration—think GitHub Actions meets AI agents. Write JSX workflows that coordinate multiple AI to solve real problems.\n\nWe ranked our 88 favorite examples. This countdown was generated BY Smithers itself 🤖\n\nLet's go 🧵",
  "🏅 Honorable mention: tweet-thread\n\nThe meta flex—this very countdown was produced by a Smithers workflow that read all examples, ranked them with AI, and drafted this thread. Self-referential engineering at its finest 💪",
  "#88. Ransomware Isolation Coordinator\n\nCoordinates detection, containment & reporting with human approval for disruptive actions. When your infrastructure is under attack, you want AI agents handling the playbook—fast, precise, with human oversight 🛡️",
  "#87. supervisor\n\nBoss agent that dynamically plans projects, delegates to specialists, iteratively reviews and re-delegates failures. Like having an AI project manager that never sleeps and learns from every mistake 🎯",
  "#86. gastown\n\nDecomposes large tasks into parallel work items, assigns to isolated worker agents, manages full lifecycle. Your AI assembly line—taking massive problems and coordinating specialist agents to solve them efficiently 🏭",
  "#85. Prompt Optimizer Harness\n\nAutomatically discovers best-performing prompts through iterative testing. No more guessing what works—this workflow scientifically finds optimal prompt variations. AI optimizing AI prompts 🔬",
  "#84. Memory Support Agent\n\nHandles customer support with durable, customer-specific memory that persists and improves over time. Unlike chatbots that forget you, this agent builds real relationships and gets smarter with every interaction 🧠",
  "#83-80: The orchestrators 🎼\n\nmilestone: sequential progression with AI validation\nkanban: AI-powered kanban flow\nwaterfall: topic → outline → draft → edit → publish\npr-lifecycle: complete PR automation\n\nMulti-step coordination at scale.",
  "#79-75: Parallel processing powerhouses ⚡\n\nfan-out-fan-in: splits tasks, processes parallel, merges output\ntriage: classifies & routes to specialized handlers\npanel: specialist AI review with moderator synthesis\nmeeting-briefer: parallel context gathering",
  "#74-70: Sales & customer intelligence 💰\n\nfriday-bot: weekly status from GitHub/Linear/Slack\ndebate: structured AI debates with judge decisions\nRevenue Scout: finds hidden sales opportunities\nlead-enricher: transforms raw leads into structured profiles",
  "#69-65: Smart routing & classification 🎯\n\nLead Router: intake → scoring → approval → CRM routing\nSupport Deflector: triages tickets, drafts responses\nservice-desk-dispatcher: classifies, routes to specialists\nsocial-inbox-router: triages social messages",
  "#64-60: Data processing pipelines 📊\n\nfinancial-inbox-guard: monitors finance emails, extracts data\nInvoice Approval Watch: automates accounts payable\nForm Filler Assistant: extracts fields, collects missing info\nETL & Blog Analyzer: structured transformation",
  "#59-55: Specialized extraction tools 🔧\n\nDynamic Schema Enricher: selects schemas by document type\nTyped Extractor Stage: messy text → clean typed objects\nExtract Anything Workbench: tests approaches, recommends best\nrunbook-executor: automates safe steps",
  "#54-50: Code intelligence & planning 🧠\n\nscaffold: generates project structure from patterns\nplan: requirements → structured implementation plans\nDiscovery: systematically scans for bugs/debt/security\naudit: scans, categorizes by severity, investigates",
  "#49-45: Repository management automation 🛠️\n\nrefactor: analyzes patterns, applies changes, verifies results\nMigration: large-scale transformations with parallel batching\nmerge-conflict-mediator: semantic analysis, intelligent proposals\nrepo-janitor & dependency-update",
  "#44-40: Quality assurance workflows ✅\n\nPR Shepherd: gathers diffs, runs tests, structured comments\nreview-cycle: AI implementer & reviewer iterate until approval\nCoverage Loop: measures gaps, writes tests until target hit\ncompliance-evidence-collector",
  "#39-35: Operations & monitoring 📡\n\nthreat-intel-enricher: enriches security alerts with external feeds\nerror-clusterer: clusters similar errors, analyzes root causes\nlog-digest: verbose logs → structured root-cause analysis\nslo-breach-explainer",
  "#34-30: Documentation automation 📚\n\nContract Drift Sentinel: compares API versions, flags breaking changes\ndoc-sync: detects discrepancies, fixes them, opens PRs\ndocs-patcher: detects API changes, patches stale docs\nBranchDoctor: diagnoses git disasters",
  "#29-25: CI/CD & testing workflows 🚀\n\nrepro-harness-builder: builds minimal Docker environments from bug reports\nRollback Advisor: analyzes failed deployments, recommends actions\ncanary-judge: compares telemetry, decides promote/hold/rollback",
  "#24-20: Validation & review systems 🔍\n\npatch-plausibility-gate: analyzes patches with parallel verification\nTrust Safety Moderator: screens user content through AI moderation\nOpenAPI Contract Agent: specs to strongly-typed TypeScript\nConfig Diff Explainer",
  "#19-15: Error handling & reliability 🛡️\n\nStandards Reviewer: reviews PR diffs against repo-local standards\nSmoketest: parallel health checks with comprehensive reporting\nfail-only-report: generates reports only on failures\nRetry Budget Manager",
  "#14-10: Testing & quality gates 🧪\n\nFlake Hunter: reruns failing tests, detects flakiness, AI analysis\nBisectGuide: orchestrates git bisect with AI interpreting outcomes\nfailing-test-author: bug reports → minimal failing tests\nBenchmark Sheriff",
  "#9-5: Monitoring & probing systems 📊\n\nMCP Health Probe: monitors servers, reports only material changes\ncollector-probe: monitors AI agent performance, alerts on drift\nGate: blocks execution until external condition met\nkimi-analysis & pi-tools-workflow",
  "#4-1: The fundamentals 🌱\n\nralph-loop: continuously monitors target systems in infinite loop\nsimple-example: takes topic, researches key points, writes article\npi-hello-world: returns structured 'hello world' JSON with validation\n\nEvery journey starts somewhere.",
  "From hello world to ransomware response—88 workflows showing what's possible when you coordinate AI agents with code.\n\nCheck out examples: github.com/smithers-ai/smithers\nTry it yourself: smithers.sh\n\nBuild something incredible 🚀",
];

async function postTweet(text, replyToId) {
  const apiKey = process.env.X_API_KEY;
  const apiSecret = process.env.X_API_SECRET;
  const accessToken = process.env.X_ACCESS_TOKEN;
  const accessSecret = process.env.X_ACCESS_SECRET;
  if (!apiKey || !apiSecret || !accessToken || !accessSecret) {
    return {
      tweetId: "",
      posted: false,
      error: "Missing X_API_KEY, X_API_SECRET, X_ACCESS_TOKEN, or X_ACCESS_SECRET env vars.",
    };
  }
  const { TwitterApi } = await import("twitter-api-v2");
  const client = new TwitterApi({ appKey: apiKey, appSecret: apiSecret, accessToken, accessSecret });
  const params = replyToId ? { text, reply: { in_reply_to_tweet_id: replyToId } } : { text };
  const { data } = await client.v2.tweet(params);
  return { tweetId: data.id, posted: true };
}

export default smithers((ctx) => {
  return (
    <Workflow name="tweet-thread">
      <Sequence>
        {tweets.map((text, i) => {
          const prev = i > 0
            ? ctx.outputMaybe("tweetPost", { nodeId: `post-${i - 1}` })
            : null;
          return (
            <Sequence key={i}>
              {i > 0 && <Timer id={`delay-${i}`} duration="3s" />}
              <Task id={`post-${i}`} output={outputs.tweetPost}>
                {() => postTweet(text, prev?.tweetId)}
              </Task>
            </Sequence>
          );
        })}
      </Sequence>
    </Workflow>
  );
});
