import {
  NanocodexAgent,
  type AgentCheckpoint,
  type AgentCheckpointResult,
  type AgentLike,
  type NanocodexAgentOptions,
  type NanocodexAuth,
  type NanocodexGenerateOptions,
} from "@smthrs/agents";
import type { GenerateTextResult } from "../../src/GenerateResult";
import type { NanocodexGenerateOptions as SourceNanocodexGenerateOptions } from "../../src/NanocodexAgentOptions";

const auth: NanocodexAuth = {
  mode: "api-key-env",
  environmentVariable: "OPENAI_API_KEY",
};

const options: NanocodexAgentOptions = {
  binary: "/opt/smithers/bin/smithers-nanocodex",
  cwd: "/workspace",
  auth,
  thinking: "xhigh",
  reasoningMode: "pro",
  fastMode: true,
  maxCheckpointBytes: 1024 * 1024,
};

const nanocodex = new NanocodexAgent(options);
const agent: AgentLike = nanocodex;
declare const checkpoint: AgentCheckpoint;
const plainGenerateOptions: NanocodexGenerateOptions = { prompt: "plain" };
const resumeGenerateOptions: NanocodexGenerateOptions = {
  prompt: "resume",
  resumeCheckpoint: checkpoint,
  checkpointMode: "resume",
};
void nanocodex.generate(resumeGenerateOptions);

// Test the source type directly so this suite remains runnable before the
// committed package declaration bundle is regenerated by its owning stage.
// @ts-expect-error Nanocodex always uses its stock native tool set
const tools: SourceNanocodexGenerateOptions = { prompt: "tools", tools: {} };
void tools;
// @ts-expect-error Nanocodex provider options are configured on the agent
const providerOptions: SourceNanocodexGenerateOptions = { prompt: "provider-options", options: { openai: {} } };
void providerOptions;
// @ts-expect-error Nanocodex protocol v1 does not support checkpoint fork
void nanocodex.generate({ prompt: "fork", resumeCheckpoint: checkpoint, checkpointMode: "fork" });
// @ts-expect-error Nanocodex continuation does not use provider session identifiers
void nanocodex.generate({ prompt: "session", resumeSession: "provider-session" });

type ExpectedResult = GenerateTextResult & AgentCheckpointResult;
declare const generated: Awaited<ReturnType<typeof nanocodex.generate>>;
const expectedResult: ExpectedResult = generated;
void agent;
void plainGenerateOptions;
void expectedResult;

// @ts-expect-error protocol v1 does not expose custom endpoint configuration
const customEndpoint: NanocodexAgentOptions = { endpoint: "https://example.test" };
void customEndpoint;
