/**
 * @param {import("./ClaudeWorkflowGeneratorOptions.ts").ClaudeWorkflowGeneratorOptions} options
 * @returns {string}
 */
export function claudeWorkflowTemplate(options) {
    const meta = {
        name: `${slug(options.workflowName)}-mirror`,
        description: "Live mirror a detached Smithers run into Claude Code workflows",
        phases: options.phasePlan.phases.map((phase) => ({ title: phase.title, ...(phase.detail ? { detail: phase.detail } : {}) })),
    };
    const phaseMap = Object.fromEntries(options.phasePlan.nodes.map((node) => [logicalNodeId(node.nodeId), node.phase]));
    const kindMap = Object.fromEntries(options.phasePlan.nodes.map((node) => [logicalNodeId(node.nodeId), node.kind]));
    const lines = [
        `export const meta = ${literal(meta)};`,
        "",
        `const PHASE_MAP = ${literal(phaseMap)};`,
        `const KIND_MAP = ${literal(kindMap)};`,
        `const MIRROR_ALL_NODES = ${options.mirrorAllNodes ? "true" : "false"};`,
        `const COLLAPSE_PHASES = ${options.collapsePhases ? "true" : "false"};`,
        "const WATCHER_BUDGET = 950;",
        "const MAX_FRAMES = 5000;",
        "const TERMINAL_RUN_STATES = new Set(['finished', 'failed', 'cancelled']);",
        "",
        "const DISCOVERY_SCHEMA = {",
        "  type: 'object',",
        "  required: ['runStatus', 'nodes'],",
        "  properties: {",
        "    runStatus: { type: 'string' },",
        "    nodes: {",
        "      type: 'array',",
        "      items: {",
        "        type: 'object',",
        "        required: ['nodeId', 'label', 'state'],",
        "        properties: {",
        "          nodeId: { type: 'string' },",
        "          label: { type: 'string' },",
        "          state: { type: 'string' },",
        "        },",
        "      },",
        "    },",
        "  },",
        "};",
        "",
        "const FRAME_SCHEMA = {",
        "  type: 'object',",
        "  required: ['next'],",
        "  properties: {",
        "    next: { type: 'string' },",
        "    frameNo: { type: 'number' },",
        "  },",
        "};",
        "",
        "function logicalId(nodeId) {",
        "  return String(nodeId).split('@@')[0];",
        "}",
        "",
        "function phaseFor(nodeId) {",
        "  return PHASE_MAP[logicalId(nodeId)] || 'main';",
        "}",
        "",
        "function kindFor(nodeId) {",
        "  return KIND_MAP[logicalId(nodeId)] || 'unknown';",
        "}",
        "",
        "function shellQuote(value) {",
        "  return `'${String(value).replaceAll(\"'\", \"'\\\\''\")}'`;",
        "}",
        "",
        "if (!args || !args.runId) {",
        "  throw new Error('args.runId is required');",
        "}",
        "",
        "const runId = String(args.runId);",
        "const cwdPrefix = args.cwd ? `cd ${shellQuote(args.cwd)} && ` : '';",
        "const mirroredNodeIds = new Set();",
        "const knownPhases = new Set(meta.phases.map((entry) => entry.title));",
        "const spawnedPhaseWatchers = new Set();",
        "let watcherCount = 0;",
        "let frameCount = 0;",
        "let lastFrameNo = -1;",
        "let capLogged = false;",
        "",
        "async function discover() {",
        "  return await agent(",
        "    `Run this command once and return structured output only: ${cwdPrefix}smithers inspect ${shellQuote(runId)} --format json\\nExtract run.status as runStatus. Extract steps as nodes with id as nodeId, label as label or id, and state as state. Include pending, running, finished, failed, skipped, and cancelled nodes. Do not assign phases or kinds.`,",
        "    { label: 'Discover Smithers nodes', phase: 'Discovery', schema: DISCOVERY_SCHEMA, effort: 'low', model: 'haiku' }",
        "  );",
        "}",
        "",
        "function normalizeNodes(nodes) {",
        "  return nodes.map((node) => ({",
        "    nodeId: String(node.nodeId),",
        "    label: node.label || String(node.nodeId),",
        "    state: String(node.state || ''),",
        "    phase: phaseFor(node.nodeId),",
        "    kind: kindFor(node.nodeId),",
        "  }));",
        "}",
        "",
        "function shouldMirror(node) {",
        "  // Mirror agent nodes plus runtime-discovered nodes absent from the baked",
        "  // map (kind 'unknown'): those are the dynamic fan-out/loop nodes the mirror",
        "  // exists to surface. Known compute/static nodes stay filtered unless",
        "  // MIRROR_ALL_NODES is set.",
        "  return MIRROR_ALL_NODES || node.kind === 'agent' || node.kind === 'unknown';",
        "}",
        "",
        "function watcherPrompt(node) {",
        "  return `Watch exactly one Smithers node and return only its final result text. Poll this command: ${cwdPrefix}smithers node ${shellQuote(node.nodeId)} --run-id ${shellQuote(runId)} --format json\\nIf it is not terminal, inspect the run with: ${cwdPrefix}smithers inspect ${shellQuote(runId)} --format json\\nTerminal node states are finished, failed, skipped, and cancelled. If the node is no longer present in inspect output, return [skipped]. Use a finite poll budget of 300 polls. For finished nodes, return the output text or JSON. For skipped nodes return [skipped]. For failed or cancelled nodes return [failed: <message>]. Do not perform the node work. Only observe.`;",
        "}",
        "",
        "async function spawnNodeWatchers(nodes) {",
        "  const fresh = nodes.filter((node) => !mirroredNodeIds.has(node.nodeId) && shouldMirror(node));",
        "  if (!fresh.length) return;",
        "  const remaining = WATCHER_BUDGET - watcherCount;",
        "  if (remaining <= 0) {",
        "    if (!capLogged) {",
        "      log(`Reached watcher cap (${WATCHER_BUDGET}); not mirroring further nodes for run ${runId}.`);",
        "      capLogged = true;",
        "    }",
        "    return;",
        "  }",
        "  const selected = fresh.slice(0, remaining);",
        "  if (selected.length < fresh.length && !capLogged) {",
        "    log(`Reached watcher cap (${WATCHER_BUDGET}); ${fresh.length - selected.length} newly discovered nodes are not mirrored.`);",
        "    capLogged = true;",
        "  }",
        "  await parallel(selected.map((node) => () => {",
        "    mirroredNodeIds.add(node.nodeId);",
        "    watcherCount += 1;",
        "    if (!knownPhases.has(node.phase)) {",
        "      knownPhases.add(node.phase);",
        "      phase(node.phase);",
        "    }",
        "    return agent(watcherPrompt(node), { label: node.label || node.nodeId, phase: node.phase, effort: 'low', model: 'haiku' });",
        "  }));",
        "}",
        "",
        "async function spawnPhaseWatchers(nodes) {",
        "  const phases = Array.from(new Set(nodes.map((node) => node.phase)));",
        "  const fresh = phases.filter((title) => !spawnedPhaseWatchers.has(title));",
        "  if (!fresh.length) return;",
        "  const remaining = WATCHER_BUDGET - watcherCount;",
        "  if (remaining <= 0) {",
        "    if (!capLogged) {",
        "      log(`Reached watcher cap (${WATCHER_BUDGET}); not mirroring further phases for run ${runId}.`);",
        "      capLogged = true;",
        "    }",
        "    return;",
        "  }",
        "  const selected = fresh.slice(0, remaining);",
        "  if (selected.length < fresh.length && !capLogged) {",
        "    log(`Reached watcher cap (${WATCHER_BUDGET}); ${fresh.length - selected.length} newly discovered phases are not mirrored.`);",
        "    capLogged = true;",
        "  }",
        "  await parallel(selected.map((title) => () => {",
        "    const phaseNodeIds = nodes.filter((node) => node.phase === title && shouldMirror(node)).map((node) => node.nodeId);",
        "    spawnedPhaseWatchers.add(title);",
        "    mirroredNodeIds.add(`phase:${title}`);",
        "    watcherCount += 1;",
        "    if (!knownPhases.has(title)) {",
        "      knownPhases.add(title);",
        "      phase(title);",
        "    }",
        "    return agent(`Summarize exactly these Smithers node ids for phase ${shellQuote(title)} until the run is terminal: ${JSON.stringify(phaseNodeIds)}. Repeatedly run: ${cwdPrefix}smithers inspect ${shellQuote(runId)} --format json\\nInclude only nodes whose id is in the explicit list above. Return a concise final summary when run.status is finished, failed, or cancelled. If run.status is continued, report that continue-as-new is not followed.`, { label: `Phase ${title}`, phase: title, effort: 'low', model: 'haiku' });",
        "  }));",
        "}",
        "",
        "async function waitForFrame(previousFrameNo) {",
        "  return await agent(",
        "    `Wait for the Smithers run to commit a newer frame, then return structured output. Run: ${cwdPrefix}smithers events ${shellQuote(runId)} --type frame --json --watch\\nIgnore any FrameCommitted with frameNo <= ${previousFrameNo}. Return {\\\"next\\\":\\\"frame\\\",\\\"frameNo\\\":N} for the first FrameCommitted whose frameNo > ${previousFrameNo}. Return {\\\"next\\\":\\\"done\\\"} if the watch stream ends or the run reaches finished, failed, or cancelled.`,",
        "    { label: 'Await Smithers frame', phase: 'Discovery', schema: FRAME_SCHEMA, effort: 'low', model: 'haiku' }",
        "  );",
        "}",
        "",
        "phase('Discovery');",
        "while (frameCount < MAX_FRAMES) {",
        "  frameCount += 1;",
        "  const snapshot = await discover();",
        "  if (!snapshot) break;",
        "  const nodes = normalizeNodes(snapshot.nodes || []);",
        "  if (COLLAPSE_PHASES) {",
        "    await spawnPhaseWatchers(nodes);",
        "  } else {",
        "    await spawnNodeWatchers(nodes);",
        "  }",
        "  if (TERMINAL_RUN_STATES.has(String(snapshot.runStatus))) {",
        "    break;",
        "  }",
        "  if (String(snapshot.runStatus) === 'continued') {",
        "    log(`Run ${runId} continued as new; this mirror stops at the original run id.`);",
        "    break;",
        "  }",
        "  const tick = await waitForFrame(lastFrameNo);",
        "  if (!tick || tick.next === 'done') {",
        "    const finalSnapshot = await discover();",
        "    if (finalSnapshot && String(finalSnapshot.runStatus) === 'continued') {",
        "      log(`Run ${runId} continued as new; this mirror stops at the original run id.`);",
        "    }",
        "    break;",
        "  }",
        "  if (tick.next === 'frame' && typeof tick.frameNo === 'number') {",
        "    lastFrameNo = Math.max(lastFrameNo, tick.frameNo);",
        "  }",
        "}",
        "",
        "if (frameCount >= MAX_FRAMES) {",
        "  log(`Reached frame backstop (${MAX_FRAMES}); mirror stopped discovering new nodes for run ${runId}.`);",
        "}",
        "",
        "log(`Mirror complete for run ${runId}: ${mirroredNodeIds.size} entries mirrored.`);",
        "return { runId, mirrored: Array.from(mirroredNodeIds) };",
        "",
    ];
    return `${lines.join("\n")}\n`;
}

/** @param {string} value */
function slug(value) {
    return value
        .replace(/\.[^.]+$/, "")
        .replace(/[^a-zA-Z0-9_-]+/g, "-")
        .replace(/^-+|-+$/g, "")
        .toLowerCase() || "smithers";
}

/** @param {string} nodeId */
function logicalNodeId(nodeId) {
    return String(nodeId).split("@@")[0];
}

/** @param {unknown} value */
function literal(value) {
    return JSON.stringify(value, null, 2);
}
