/**
 * Alchemy infrastructure-as-code for keys.smithers.sh, the @smthrs/keys docs site.
 * Generated by apps/docs/shared/gen-sites.mjs from apps/docs/shared/manifest.mjs. Edit the generator, then rerun it: node apps/docs/shared/gen-sites.mjs
 *
 * Deploy:   CLOUDFLARE_API_TOKEN=... KEYS_WORKER_NAME=... pnpm -C apps/docs/keys deploy
 * Destroy:  pnpm -C apps/docs/keys destroy
 *
 * Required: KEYS_WORKER_NAME, preserving the existing Worker name.
 * See apps/docs/README.md for Alchemy 1 state migration and explicit adoption.
 * Optional env: KEYS_SITE_DOMAIN (preview deploys, default keys.smithers.sh),
 * CLOUDFLARE_SMITHERS_ZONE_ID (alchemy resolves the zone from the domain when
 * omitted).
 */
import { makeDocsSiteStack } from "@smithers/docs-shared/alchemy-site"

export default makeDocsSiteStack({ slug: "keys" })
