export type RunRow = {
  runId: string;
  parentRunId: string | null;
  /** Exact tenant pair when ownership is enabled; both fields are present together. */
  owner?: string | null;
  app?: string | null;
  workflowName: string;
  workflowPath: string | null;
  workflowHash: string | null;
  status: string;
  createdAtMs: number;
  startedAtMs: number | null;
  finishedAtMs: number | null;
  heartbeatAtMs: number | null;
  runtimeOwnerId: string | null;
  cancelRequestedAtMs: number | null;
  cancelRequestId: string | null;
  cancelRequestSource: string | null;
  cancelRequestDetail: string | null;
  cancelRequestSignal: string | null;
  cancelRequestClientIdentity: string | null;
  cancelRequestClientPid: number | null;
  pauseRequestedAtMs?: number | null;
  hijackRequestedAtMs: number | null;
  hijackTarget: string | null;
  vcsType: string | null;
  vcsRoot: string | null;
  vcsRevision: string | null;
  errorJson: string | null;
  configJson: string | null;
};
