import type { BunSQLiteDatabase } from "drizzle-orm/bun-sqlite";
import { Effect } from "effect";
import type { SmithersError } from "@smithers/errors/SmithersError";
import { type OutputKey } from "../output";
import type { RunRow } from "./RunRow";
import type { StaleRunRecord } from "./StaleRunRecord";
import type { RunAncestryRow } from "./RunAncestryRow";
import type { EventHistoryQuery } from "./EventHistoryQuery";
import type { SignalQuery } from "./SignalQuery";
import type { HumanRequestRow } from "./HumanRequestRow";
import type { NodeRow } from "./NodeRow";
import type { AttemptRow } from "./AttemptRow";
import type { ApprovalRow } from "./ApprovalRow";
import type { CacheRow } from "./CacheRow";
import type { SignalRow } from "./SignalRow";
import type { PendingHumanRequestRow } from "./PendingHumanRequestRow";
import type { AlertStatus } from "./AlertStatus";
import type { AlertRow } from "./AlertRow";
type RunnableEffect<A, E = SmithersError> = Effect.Effect<A, E> & PromiseLike<A>;
export declare class SmithersDb {
    private db;
    private internalStorage;
    private reconstructedFrameXmlCache;
    private transactionDepth;
    private transactionOwnerThread;
    private transactionTail;
    constructor(db: BunSQLiteDatabase<any>);
    private frameCacheKey;
    private getCachedFrameXml;
    private rememberFrameXml;
    private clearFrameCacheForRun;
    rawQuery(queryString: string): RunnableEffect<any, SmithersError>;
    private ownsActiveTransaction;
    private read;
    private write;
    private getSqliteTransactionClient;
    private acquireTransactionTurn;
    withTransactionEffect<A>(writeGroup: string, operation: Effect.Effect<A, SmithersError>): RunnableEffect<A>;
    withTransaction<A>(writeGroup: string, operation: Effect.Effect<A, SmithersError>): Promise<A>;
    insertRun(row: any): RunnableEffect<void, SmithersError>;
    updateRun(runId: string, patch: any): RunnableEffect<void, SmithersError>;
    updateRunEffect(runId: string, patch: any): RunnableEffect<void, SmithersError>;
    heartbeatRun(runId: string, runtimeOwnerId: string, heartbeatAtMs: number): RunnableEffect<void, SmithersError>;
    requestRunCancel(runId: string, cancelRequestedAtMs: number): RunnableEffect<void, SmithersError>;
    requestRunHijack(runId: string, hijackRequestedAtMs: number, hijackTarget?: string | null): RunnableEffect<void, SmithersError>;
    clearRunHijack(runId: string): RunnableEffect<void, SmithersError>;
    getRun(runId: string): RunnableEffect<RunRow | undefined, SmithersError>;
    listRunAncestry(runId: string, limit?: number): RunnableEffect<RunAncestryRow[], SmithersError>;
    getLatestChildRun(parentRunId: string): RunnableEffect<RunRow | undefined, SmithersError>;
    listRuns(limit?: number, status?: string): RunnableEffect<RunRow[], SmithersError>;
    listStaleRunningRuns(staleBeforeMs: number, limit?: number): RunnableEffect<StaleRunRecord[], SmithersError>;
    claimRunForResume(params: {
        runId: string;
        expectedStatus?: string;
        expectedRuntimeOwnerId: string | null;
        expectedHeartbeatAtMs: number | null;
        staleBeforeMs: number;
        claimOwnerId: string;
        claimHeartbeatAtMs: number;
        requireStale?: boolean;
    }): RunnableEffect<boolean, SmithersError>;
    releaseRunResumeClaim(params: {
        runId: string;
        claimOwnerId: string;
        restoreRuntimeOwnerId: string | null;
        restoreHeartbeatAtMs: number | null;
    }): RunnableEffect<void, SmithersError>;
    updateClaimedRun(params: {
        runId: string;
        expectedRuntimeOwnerId: string;
        expectedHeartbeatAtMs: number | null;
        patch: any;
    }): RunnableEffect<boolean, SmithersError>;
    insertNode(row: any): RunnableEffect<void, SmithersError>;
    insertNodeEffect(row: any): RunnableEffect<void, SmithersError>;
    getNode(runId: string, nodeId: string, iteration: number): RunnableEffect<NodeRow | undefined, SmithersError>;
    listNodeIterations(runId: string, nodeId: string): RunnableEffect<NodeRow[], SmithersError>;
    listNodes(runId: string): RunnableEffect<NodeRow[], SmithersError>;
    upsertOutputRow(table: any, key: OutputKey, payload: Record<string, unknown>): RunnableEffect<void, SmithersError>;
    upsertOutputRowEffect(table: any, key: OutputKey, payload: Record<string, unknown>): RunnableEffect<void, SmithersError>;
    deleteOutputRow(tableName: string, key: OutputKey): RunnableEffect<undefined, SmithersError>;
    deleteOutputRowEffect(tableName: string, key: OutputKey): RunnableEffect<undefined, SmithersError>;
    getRawNodeOutput(tableName: string, runId: string, nodeId: string): RunnableEffect<{} | null, never>;
    getRawNodeOutputForIteration(tableName: string, runId: string, nodeId: string, iteration: number): RunnableEffect<any, never>;
    insertAttempt(row: any): RunnableEffect<void, SmithersError>;
    insertAttemptEffect(row: any): RunnableEffect<void, SmithersError>;
    updateAttempt(runId: string, nodeId: string, iteration: number, attempt: number, patch: any): RunnableEffect<void, SmithersError>;
    updateAttemptEffect(runId: string, nodeId: string, iteration: number, attempt: number, patch: any): RunnableEffect<void, SmithersError>;
    heartbeatAttempt(runId: string, nodeId: string, iteration: number, attempt: number, heartbeatAtMs: number, heartbeatDataJson: string | null): RunnableEffect<void, SmithersError>;
    listAttempts(runId: string, nodeId: string, iteration: number): RunnableEffect<AttemptRow[]>;
    listAttemptsForRun(runId: string): RunnableEffect<AttemptRow[]>;
    getAttempt(runId: string, nodeId: string, iteration: number, attempt: number): RunnableEffect<AttemptRow | undefined>;
    listInProgressAttempts(runId: string): RunnableEffect<AttemptRow[]>;
    listAllInProgressAttempts(): RunnableEffect<any[]>;
    private listFrameChainDesc;
    private reconstructFrameXml;
    private inflateFrameRow;
    insertFrame(row: any): RunnableEffect<void, SmithersError>;
    insertFrameEffect(row: any): RunnableEffect<void, SmithersError>;
    getLastFrame(runId: string): RunnableEffect<any, SmithersError>;
    insertOrUpdateApproval(row: any): RunnableEffect<void, SmithersError>;
    getApproval(runId: string, nodeId: string, iteration: number): RunnableEffect<ApprovalRow | undefined, SmithersError>;
    insertHumanRequest(row: HumanRequestRow): RunnableEffect<void, SmithersError>;
    getHumanRequest(requestId: string): RunnableEffect<HumanRequestRow | undefined, SmithersError>;
    reopenHumanRequest(requestId: string): RunnableEffect<void, SmithersError>;
    expireStaleHumanRequests(nowMs?: number): RunnableEffect<void, SmithersError>;
    listPendingHumanRequests(nowMs?: number): RunnableEffect<PendingHumanRequestRow[], SmithersError>;
    answerHumanRequest(requestId: string, responseJson: string, answeredAtMs: number, answeredBy?: string | null): RunnableEffect<void, SmithersError>;
    cancelHumanRequest(requestId: string): RunnableEffect<void, SmithersError>;
    insertAlert(row: AlertRow): Promise<AlertRow | undefined>;
    getAlert(alertId: string): RunnableEffect<AlertRow | undefined, SmithersError>;
    listAlerts(limit?: number, statuses?: readonly AlertStatus[]): RunnableEffect<AlertRow[], SmithersError>;
    acknowledgeAlert(alertId: string, acknowledgedAtMs?: number): Promise<AlertRow | undefined>;
    resolveAlert(alertId: string, resolvedAtMs?: number): Promise<AlertRow | undefined>;
    silenceAlert(alertId: string): Promise<AlertRow | undefined>;
    insertSignalWithNextSeq(row: {
        runId: string;
        signalName: string;
        correlationId: string | null;
        payloadJson: string;
        receivedAtMs: number;
        receivedBy?: string | null;
    }): RunnableEffect<number, SmithersError>;
    getLastSignalSeq(runId: string): RunnableEffect<number | undefined, SmithersError>;
    listSignals(runId: string, query?: SignalQuery): RunnableEffect<SignalRow[], SmithersError>;
    insertToolCall(row: any): RunnableEffect<void, SmithersError>;
    upsertSandbox(row: any): RunnableEffect<void, SmithersError>;
    getSandbox(runId: string, sandboxId: string): RunnableEffect<Record<string, unknown> | undefined, SmithersError>;
    listSandboxes(runId: string): RunnableEffect<Record<string, unknown>[], SmithersError>;
    listToolCalls(runId: string, nodeId: string, iteration: number): RunnableEffect<Record<string, unknown>[], SmithersError>;
    insertEvent(row: any): RunnableEffect<void, SmithersError>;
    insertEventWithNextSeq(row: {
        runId: string;
        timestampMs: number;
        type: string;
        payloadJson: string;
    }): RunnableEffect<number, SmithersError>;
    getLastEventSeq(runId: string): RunnableEffect<number | undefined, SmithersError>;
    private buildEventHistoryWhere;
    listEventHistory(runId: string, query?: EventHistoryQuery): RunnableEffect<Record<string, unknown>[], SmithersError>;
    countEventHistory(runId: string, query?: EventHistoryQuery): RunnableEffect<number, SmithersError>;
    listEvents(runId: string, afterSeq: number, limit?: number): RunnableEffect<Record<string, unknown>[], SmithersError>;
    listEventsByType(runId: string, type: string): RunnableEffect<Record<string, unknown>[], SmithersError>;
    insertOrUpdateRalph(row: any): RunnableEffect<void, SmithersError>;
    listRalph(runId: string): RunnableEffect<Record<string, unknown>[], SmithersError>;
    listPendingApprovals(runId: string): RunnableEffect<ApprovalRow[], SmithersError>;
    listAllPendingApprovals(): RunnableEffect<Record<string, unknown>[], SmithersError>;
    listApprovalHistoryForNode(workflowName: string, nodeId: string, limit?: number): RunnableEffect<Record<string, unknown>[], SmithersError>;
    getRalph(runId: string, ralphId: string): RunnableEffect<Record<string, unknown> | undefined, SmithersError>;
    insertCache(row: any): RunnableEffect<void, SmithersError>;
    insertCacheEffect(row: any): RunnableEffect<void, SmithersError>;
    getCache(cacheKey: string): RunnableEffect<CacheRow | undefined, SmithersError>;
    listCacheByNode(nodeId: string, outputTable?: string, limit?: number): RunnableEffect<Record<string, unknown>[], SmithersError>;
    deleteFramesAfter(runId: string, frameNo: number): RunnableEffect<void, SmithersError>;
    listFrames(runId: string, limit: number, afterFrameNo?: number): RunnableEffect<any[], SmithersError>;
    countNodesByState(runId: string): RunnableEffect<Record<string, unknown>[], SmithersError>;
    upsertCron(row: any): RunnableEffect<void, SmithersError>;
    listCrons(enabledOnly?: boolean): RunnableEffect<Record<string, unknown>[], SmithersError>;
    updateCronRunTime(cronId: string, lastRunAtMs: number, nextRunAtMs: number, errorJson?: string | null): RunnableEffect<void, SmithersError>;
    deleteCron(cronId: string): RunnableEffect<void, SmithersError>;
    insertScorerResult(row: any): RunnableEffect<void, SmithersError>;
    listScorerResults(runId: string, nodeId?: string): RunnableEffect<Record<string, unknown>[], SmithersError>;
    getRunEffect(runId: string): RunnableEffect<RunRow | undefined, SmithersError>;
    listRunsEffect(limit?: number, status?: string): RunnableEffect<RunRow[], SmithersError>;
    listStaleRunningRunsEffect(staleBeforeMs: number, limit?: number): RunnableEffect<StaleRunRecord[], SmithersError>;
    claimRunForResumeEffect(params: Parameters<SmithersDb["claimRunForResume"]>[0]): RunnableEffect<boolean, SmithersError>;
    releaseRunResumeClaimEffect(params: Parameters<SmithersDb["releaseRunResumeClaim"]>[0]): RunnableEffect<void, SmithersError>;
    listNodeIterationsEffect(runId: string, nodeId: string): RunnableEffect<NodeRow[], SmithersError>;
    listNodesEffect(runId: string): RunnableEffect<NodeRow[], SmithersError>;
    listAttemptsEffect(runId: string, nodeId: string, iteration: number): RunnableEffect<AttemptRow[], SmithersError>;
    listAttemptsForRunEffect(runId: string): RunnableEffect<AttemptRow[], SmithersError>;
    listToolCallsEffect(runId: string, nodeId: string, iteration: number): RunnableEffect<Record<string, unknown>[], SmithersError>;
    getRawNodeOutputForIterationEffect(tableName: string, runId: string, nodeId: string, iteration: number): RunnableEffect<any, never>;
    insertEventWithNextSeqEffect(row: Parameters<SmithersDb["insertEventWithNextSeq"]>[0]): RunnableEffect<number, SmithersError>;
    getLastEventSeqEffect(runId: string): RunnableEffect<number | undefined, SmithersError>;
    listEventHistoryEffect(runId: string, query?: EventHistoryQuery): RunnableEffect<Record<string, unknown>[], SmithersError>;
    countEventHistoryEffect(runId: string, query?: EventHistoryQuery): RunnableEffect<number, SmithersError>;
    listEventsByTypeEffect(runId: string, type: string): RunnableEffect<Record<string, unknown>[], SmithersError>;
    listPendingApprovalsEffect(runId: string): RunnableEffect<ApprovalRow[], SmithersError>;
    getLastFrameEffect(runId: string): RunnableEffect<any, SmithersError>;
    listCacheByNodeEffect(nodeId: string, outputTable?: string, limit?: number): RunnableEffect<Record<string, unknown>[], SmithersError>;
    listCronsEffect(enabledOnly?: boolean): RunnableEffect<Record<string, unknown>[], SmithersError>;
    updateCronRunTimeEffect(cronId: string, lastRunAtMs: number, nextRunAtMs: number, errorJson?: string | null): RunnableEffect<void, SmithersError>;
    listScorerResultsEffect(runId: string, nodeId?: string): RunnableEffect<Record<string, unknown>[], SmithersError>;
}
export {};
