/**
 * Alchemy infrastructure-as-code for step-cache.smithers.sh, the @smthrs/step-cache docs site.
 * Generated by apps/docs/shared/gen-sites.mjs from apps/docs/shared/manifest.mjs. Edit the generator, then rerun it: node apps/docs/shared/gen-sites.mjs
 *
 * Deploy:   CLOUDFLARE_API_TOKEN=... STEP_CACHE_WORKER_NAME=... pnpm -C apps/docs/step-cache deploy
 * Destroy:  pnpm -C apps/docs/step-cache destroy
 *
 * Required: STEP_CACHE_WORKER_NAME, preserving the existing Worker name.
 * See apps/docs/README.md for Alchemy 1 state migration and explicit adoption.
 * Optional env: STEP_CACHE_SITE_DOMAIN (preview deploys, default step-cache.smithers.sh),
 * CLOUDFLARE_SMITHERS_ZONE_ID (alchemy resolves the zone from the domain when
 * omitted).
 */
import { makeDocsSiteStack } from "@smithers/docs-shared/alchemy-site"

export default makeDocsSiteStack({ slug: "step-cache" })
