#!/usr/bin/env node
/** Projects package-owned agent documentation into the repository site. */
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join, posix } from "node:path"
import { fileURLToPath } from "node:url"
import { Package } from "../Package.ts"

const check = process.argv.includes("--check")
const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const repoRoot = join(packageRoot, "..", "..")
const read = (path) => readFileSync(path, "utf8")
const readModule = (relative) => read(join(packageRoot, "src", relative))

const ungutter = (block) => block.split("\n").map((line) => line.replace(/^\s*\* ?/, "")).join("\n")

const description = (body) => {
  const lines = []
  for (const line of body.split("\n")) {
    if (/^@\w+/.test(line)) break
    lines.push(line)
  }
  return lines.join("\n").trim()
}

const delink = (value) => value.replace(/\{@link\s+([^}]+)\}/g, "`$1`")

const paragraphs = (value) => {
  const blocks = []
  let current = []
  for (const line of value.split("\n")) {
    if (line.trim() === "") {
      if (current.length > 0) blocks.push(current.join(" "))
      current = []
    } else current.push(line.trim())
  }
  if (current.length > 0) blocks.push(current.join(" "))
  return blocks.join("\n\n")
}

const firstSentence = (value) => {
  const flat = delink(value).split("\n\n")[0].split("\n").join(" ")
  return (/^[\s\S]*?\.(?=\s|$)/.exec(flat)?.[0] ?? flat).trim()
}

const moduleDoc = (source) => {
  const match = /\/\*\*((?:[^*]|\*(?!\/))*)\*\//.exec(source)
  if (match === null) throw new Error("agent docs: no module JSDoc block")
  return delink(description(ungutter(match[1])))
}

/** Documented declarations of one module, in source order. */
const exportedDocs = (source, relative, prefix) => {
  const entries = []
  const pattern = /\/\*\*((?:[^*]|\*(?!\/))*)\*\/\s*\nexport (type|const|class|interface|function) (\w+)/g
  for (let match = pattern.exec(source); match !== null; match = pattern.exec(source)) {
    const body = ungutter(match[1])
    const category = /@category (\S+)/.exec(body)?.[1]
    if (category === undefined) continue
    entries.push({
      name: `${prefix}${match[3]}`,
      declaration: match[2],
      category,
      module: relative,
      summary: firstSentence(description(body))
    })
  }
  return entries
}

/**
 * Every documented export reachable from one module, following the barrel
 * re-exports the package publishes. A folder barrel contributes its members
 * under the namespace that re-exported it, so the rendered name is the one a
 * consumer writes.
 */
const collect = (relative, prefix, seen) => {
  if (seen.has(relative)) return []
  seen.add(relative)
  const source = readModule(relative)
  const directory = posix.dirname(relative)
  const resolve = (specifier) => posix.normalize(posix.join(directory, specifier))
  const entries = exportedDocs(source, relative, prefix)
  for (const match of source.matchAll(/export \* (?:as (\w+) )?from "(\.[\w./-]+)"/g)) {
    const nested = match[1] === undefined ? prefix : `${prefix}${match[1]}.`
    entries.push(...collect(resolve(match[2]), nested, seen))
  }
  return entries
}

const manifest = JSON.parse(read(join(packageRoot, "package.json")))
if (manifest.name !== Package.name) throw new Error("agent docs: Package.ts and package.json names differ")
// The agent projects no fragments into shared pages yet. Declaring one
// without teaching this generator to inject it would silently do nothing.
if (Package.snippets.length > 0) throw new Error("agent docs: snippet projection is not implemented")

const barrel = readModule("index.ts")
const exports = collect("index.ts", "", new Set())
if (exports.length === 0) throw new Error("agent docs: no documented exports found")

const table = [
  "| Export | Kind | Summary |",
  "| --- | --- | --- |",
  ...exports.map((entry) => `| \`${entry.name}\` (${entry.declaration}) | ${entry.category} | ${entry.summary} |`)
].join("\n")

const apiPage = `---
description: "${manifest.description}."
---

{/* Generated by \`node packages/agent/scripts/docs.mjs\` from packages/agent. Edit package sources, never this file. */}

# @smthrs/agent

${paragraphs(moduleDoc(barrel))}

${read(join(packageRoot, Package.api.source)).trim()}

## Exports

${table}
`

const outputs = new Map([[Package.api.target, apiPage]])

const failures = []
for (const path of Package.references) {
  const content = read(join(repoRoot, path))
  if (!/@smthrs\/agent(?![\w-])/.test(content) || !/\/api\/agent(?![\w-])/.test(content)) {
    failures.push(`${path}: must reference ${Package.name} and /api/agent`)
  }
}
for (const [path, content] of outputs) {
  if (content.includes("—")) failures.push(`${path}: generated content contains an em-dash`)
}

let drifted = false
for (const [path, content] of outputs) {
  const absolute = join(repoRoot, path)
  if (read(absolute) === content) continue
  drifted = true
  if (check) failures.push(`${path}: drifted; run node packages/agent/scripts/docs.mjs`)
  else {
    writeFileSync(absolute, content)
    console.log(`wrote ${path}`)
  }
}

if (failures.length > 0) {
  for (const failure of failures) console.error(`✗ ${failure}`)
  process.exit(1)
}

console.log(
  check
    ? "✓ the agent package documentation is current"
    : drifted
    ? "✓ agent package documentation regenerated"
    : "✓ agent package documentation already current"
)
