/**
 * Targets for ui-styleguide.smithers.sh, the @smthrs/ui-styleguide documentation site.
 * Generated by apps/docs/shared/gen-sites.mjs from apps/docs/shared/manifest.mjs. Edit the generator, then rerun it: node apps/docs/shared/gen-sites.mjs
 *
 * The content edge is the source package's docsFiles filegroup, imported by
 * label: input globs are package scoped, so a glob declared here could never
 * reach packages/smithers/ui/ui-styleguide.
 */
import { Smithers } from "@smthrs/targets"
import { Package as uiStyleguidePackage } from "../../../packages/smithers/ui/ui-styleguide/PACKAGE.ts"

const cwd = "apps/docs/ui-styleguide"

/** The site's config, content, styles, and scripts. */
const sources = [
  Smithers.glob("//apps/docs/ui-styleguide/src/**/*"),
  Smithers.file("//apps/docs/ui-styleguide/astro.config.mjs"),
  Smithers.file("//apps/docs/ui-styleguide/package.json")
]

/** `astro check`: the site typechecks against its package tsconfig. */
const check = Smithers.ToolRun({
  command: "pnpm",
  args: ["run", "check"],
  inputs: sources,
  deps: [],
  cwd
})

/** `astro build`: the static site into `apps/docs/ui-styleguide/dist`. */
const build = Smithers.ToolBuild({
  tool: "astro",
  command: "pnpm",
  args: ["run", "build"],
  inputs: sources,
  outputs: ["dist"],
  deps: [],
  env: {},
  cache: true,
  cwd
})

/**
 * The committed content tree, stitched from @smthrs/ui-styleguide's colocated docs by
 * apps/docs/shared/sync-content.mjs. The committed copy is the cache:
 * `smithers-build lint //apps/docs/ui-styleguide:contentSync` fails on drift,
 * `smithers-build run //apps/docs/ui-styleguide:contentSync` applies.
 */
const contentSync = Smithers.Generate({
  summary: "Sync @smthrs/ui-styleguide's colocated docs into the site content tree; check drift under lint.",
  script: Smithers.file("//apps/docs/shared/sync-content.mjs"),
  env: { SMITHERS_DOCS_SLUG: "ui-styleguide" },
  data: [uiStyleguidePackage.docsFiles],
  changes: ["src/content/docs/**"]
})

export const Package = Smithers.Package({
  targets: { check, build, contentSync }
})
