#!/usr/bin/env bun
/**
 * generate-workflow-pack.ts
 *
 * Single source of truth for the workflows that `smithers init` seeds.
 *
 * The legacy seeded pack is hand-embedded as escaped string arrays inside
 * `apps/cli/src/workflow-pack.js`. That duplicates the canonical dogfood files
 * in `.smithers/` and forces a manual, error-prone port every time a workflow
 * is added. This generator reads the canonical seeded files straight from
 * `.smithers/workflows/` (and the prompts they import from `.smithers/prompts/`)
 * and emits a generated module that `workflow-pack.js` splices into the init
 * pack verbatim — no escaping, no drift.
 *
 * Adding a workflow to `smithers init` is now:
 *   1. Author it in `.smithers/workflows/<id>.tsx` with the seeded header
 *      (`// smithers-source: seeded`, `// smithers-display-name: …`, …).
 *   2. Add its id to SEEDED_WORKFLOW_IDS below.
 *   3. `bun scripts/generate-workflow-pack.ts` and commit the regenerated module.
 *
 * `create-workflow`'s own scaffold step can run this for you so authoring a
 * workflow ships it to init automatically.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SMITHERS_DIR = resolve(REPO_ROOT, ".smithers");
const OUTPUT_FILE = resolve(REPO_ROOT, "apps/cli/src/seeded-workflow-pack.generated.js");

/**
 * Workflows whose canonical `.smithers/workflows/<id>.tsx` ships in `smithers
 * init`. Extend this list (and re-run the generator) to add a workflow to the
 * init pack. The legacy inline workflows in workflow-pack.js are NOT listed
 * here yet — they can be migrated incrementally.
 */
const SEEDED_WORKFLOW_IDS = [
  "create-workflow",
  // Concierge suite (generated from canonical .smithers sources).
  "context-engineer",
  "route-task",
  "create-skill",
  "extract-skill",
  "monitor-smithers",
  "monitor",
  "triage-run",
  "context-doctor",
  "backpressure-plan",
  "hodge-counterexample-search",
  "eval-author",
  "report-slideshow",
  // Fable-as-operator meta-workflow (authored in fable-smithers, moved here).
  "smithering",
];

type TemplateFile = { path: string; contents: string };

/** Prompts a workflow imports from `../prompts/<name>.mdx`. */
function promptImportsOf(source: string): string[] {
  const names = new Set<string>();
  const re = /from\s+["']\.\.\/prompts\/([^"']+\.mdx)["']/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(source)) !== null) names.add(m[1]);
  return [...names];
}

function readOrThrow(absPath: string, label: string): string {
  if (!existsSync(absPath)) {
    throw new Error(`Missing ${label}: ${absPath}`);
  }
  return readFileSync(absPath, "utf8");
}

function build(): TemplateFile[] {
  const files: TemplateFile[] = [];
  const seenPaths = new Set<string>();

  const push = (path: string, contents: string) => {
    if (seenPaths.has(path)) return; // dedup shared prompts across workflows
    seenPaths.add(path);
    files.push({ path, contents });
  };

  for (const id of SEEDED_WORKFLOW_IDS) {
    const workflowAbs = resolve(SMITHERS_DIR, "workflows", `${id}.tsx`);
    const workflowSource = readOrThrow(workflowAbs, `seeded workflow ${id}`);

    if (!/^\/\/\s*smithers-source:\s*seeded\b/m.test(workflowSource)) {
      throw new Error(
        `${id}.tsx is in SEEDED_WORKFLOW_IDS but is missing the "// smithers-source: seeded" header. ` +
          "Seeded workflows must carry the full seeded header so init ships them verbatim.",
      );
    }

    push(`.smithers/workflows/${id}.tsx`, workflowSource);

    for (const promptName of promptImportsOf(workflowSource)) {
      const promptAbs = resolve(SMITHERS_DIR, "prompts", promptName);
      const promptSource = readOrThrow(promptAbs, `prompt ${promptName} for workflow ${id}`);
      push(`.smithers/prompts/${promptName}`, promptSource);
    }
  }

  return files;
}

function emit(files: TemplateFile[]): string {
  const banner = [
    "// AUTO-GENERATED by scripts/generate-workflow-pack.ts — DO NOT EDIT BY HAND.",
    "// Edit the canonical sources in .smithers/workflows + .smithers/prompts and re-run the generator.",
    "//",
    "// Seeded workflow ids: " + SEEDED_WORKFLOW_IDS.join(", "),
    "",
    "/** @typedef {{ path: string; contents: string }} TemplateFile */",
    "",
    "/** @type {TemplateFile[]} */",
    "export const GENERATED_SEEDED_FILES = ",
  ].join("\n");
  return `${banner}${JSON.stringify(files, null, 2)};\n`;
}

function main() {
  const files = build();
  const output = emit(files);
  writeFileSync(OUTPUT_FILE, output, "utf8");
  const workflows = files.filter((f) => f.path.includes("/workflows/")).length;
  const prompts = files.filter((f) => f.path.includes("/prompts/")).length;
  process.stdout.write(
    `[generate-workflow-pack] wrote ${files.length} file(s) (${workflows} workflow, ${prompts} prompt) ` +
      `to ${OUTPUT_FILE.replace(REPO_ROOT + "/", "")}\n`,
  );
  for (const f of files) process.stdout.write(`  + ${f.path}\n`);
}

main();
