/**
 * The Smithers gateway bundles `.smithers/ui/*.tsx` with Bun.build and serves
 * only the JS output — CSS imports are dropped. The convention (mirrored from
 * the multi app) is to pre-bundle third-party component CSS into a TS string
 * that the UI injects via a `<style>` tag.
 *
 * This generates two modules used by `.smithers/ui/create-workflow.tsx`:
 *   - crepeTheme.generated.ts  — Milkdown Crepe theme (common + light/dark frame)
 *   - xyflowTheme.generated.ts — @xyflow/react base stylesheet
 *
 * Run: bun scripts/generate-ui-themes.ts
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const uiDir = resolve(root, ".smithers/ui");
const exampleUiDir = resolve(root, "examples/ui");

/**
 * Bundle a CSS entry (resolving @import + node_modules exports) into one string.
 * Fonts/icons referenced via url() are kept external (not inlined) so the
 * generated string stays small — mirrors the multi app's generator.
 */
async function bundleCss(entryCss: string): Promise<string> {
  const result = await build({
    stdin: { contents: entryCss, resolveDir: root, loader: "css" },
    bundle: true,
    write: false,
    minify: true,
    external: ["*.woff", "*.woff2", "*.ttf", "*.eot", "*.svg", "*.png"],
    logLevel: "silent",
  });
  const css = result.outputFiles?.[0]?.text?.trim() ?? "";
  if (!css) throw new Error(`empty CSS for "${entryCss}"`);
  return css;
}

function emitTo(dir: string, file: string, exportName: string, css: string, note: string) {
  const outPath = resolve(dir, file);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(
    outPath,
    `// Generated by scripts/generate-ui-themes.ts — do not edit.\n// ${note}\nexport const ${exportName} = ${JSON.stringify(css)};\n`,
  );
  console.log(`${file}: ${css.length} chars -> ${outPath}`);
}

function emit(file: string, exportName: string, css: string, note: string) {
  emitTo(uiDir, file, exportName, css, note);
}

// The shared @smthrs/ui markdown-editor adapter ships the same
// Crepe theme through its own <style> injector, so keep its pre-bundled copy in
// lockstep with the .smithers/ui one below.
const uiAdapterDir = resolve(root, "packages/ui/src/adapters/markdown-editor");

type CrepeHousePalette = {
  background: string;
  text: string;
  textMuted: string;
  textFaint: string;
  surface: string;
  surface2: string;
  hover: string;
  inverseBg: string;
  inverseText: string;
  inlineCodeBg: string;
  brand: string;
  success: string;
  danger: string;
  shadow1: string;
  shadow2: string;
};

function crepeHouseTokens(palette: CrepeHousePalette): string {
  const value = (token: string, fallback: string) => `var(--${token},${fallback})`;
  return [
    `--crepe-color-background:${value("bg", palette.background)}`,
    `--crepe-color-on-background:${value("text", palette.text)}`,
    `--crepe-color-surface:${value("surface", palette.surface)}`,
    `--crepe-color-surface-low:${value("surface-2", palette.surface2)}`,
    `--crepe-color-on-surface:${value("text", palette.text)}`,
    `--crepe-color-on-surface-variant:${value("text-muted", palette.textMuted)}`,
    `--crepe-color-outline:${value("text-faint", palette.textFaint)}`,
    `--crepe-color-primary:${value("brand", palette.brand)}`,
    `--crepe-color-secondary:${value("surface-2", palette.surface2)}`,
    `--crepe-color-on-secondary:${value("text", palette.text)}`,
    `--crepe-color-inverse:${value("inverse-bg", palette.inverseBg)}`,
    `--crepe-color-on-inverse:${value("inverse-text", palette.inverseText)}`,
    `--crepe-color-inline-code:${value("danger", palette.danger)}`,
    `--crepe-color-error:${value("danger", palette.danger)}`,
    `--crepe-color-hover:${value("hover", palette.hover)}`,
    `--crepe-color-selected:${value("brand-soft", `color-mix(in srgb,${palette.brand} 10%,${palette.surface})`)}`,
    `--crepe-color-inline-area:${value("inline-code-bg", palette.inlineCodeBg)}`,
    `--crepe-color-diff-added:${value("success", palette.success)}`,
    `--crepe-color-diff-added-bg:${value("success-soft", `color-mix(in srgb,${palette.success} 12%,${palette.surface})`)}`,
    `--crepe-color-diff-added-text:${value("success", palette.success)}`,
    `--crepe-color-diff-removed:${value("danger", palette.danger)}`,
    `--crepe-color-diff-removed-bg:${value("danger-soft", `color-mix(in srgb,${palette.danger} 10%,${palette.surface})`)}`,
    `--crepe-color-diff-removed-text:${value("danger", palette.danger)}`,
    `--crepe-font-title:var(--font-sans,Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif)`,
    `--crepe-font-default:var(--font-sans,Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif)`,
    `--crepe-font-code:var(--font-mono,ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace)`,
    `--crepe-shadow-1:${value("shadow-1", palette.shadow1)}`,
    `--crepe-shadow-2:${value("shadow-2", palette.shadow2)}`,
  ].join(";");
}

const crepeLightHouseTokens = crepeHouseTokens({
  background: "#FBFBFB",
  text: "#403f53",
  textMuted: "#676676",
  textFaint: "#6b6a7a",
  surface: "#fefefe",
  surface2: "#f4f3f5",
  hover: "#f4f3f5",
  inverseBg: "#403f53",
  inverseText: "#FBFBFB",
  inlineCodeBg: "rgba(64,63,83,0.06)",
  brand: "#9449bc",
  success: "#21766f",
  danger: "#ba3f3c",
  shadow1: "0 1px 2px rgb(64 63 83 / 0.05)",
  shadow2: "0 1px 2px rgb(64 63 83 / 0.04),0 8px 24px rgb(64 63 83 / 0.07)",
});
const crepeDarkHouseTokens = crepeHouseTokens({
  background: "#011627",
  text: "#d6deeb",
  textMuted: "#94a0ae",
  textFaint: "#909caa",
  surface: "#0d2132",
  surface2: "#15293a",
  hover: "#15293a",
  inverseBg: "#d6deeb",
  inverseText: "#011627",
  inlineCodeBg: "rgba(214,222,235,0.08)",
  brand: "#c792ea",
  success: "#addb67",
  danger: "#f16f6c",
  shadow1: "0 1px 2px rgb(0 0 0 / 0.35)",
  shadow2: "0 1px 2px rgb(0 0 0 / 0.30),0 8px 24px rgb(0 0 0 / 0.40)",
});

// ---- Crepe (Milkdown): structural common + house light/dark token bridge ----
const crepeCommon = await bundleCss(`@import "@milkdown/crepe/theme/common/style.css";`);
const crepeCss = [
  crepeCommon,
  `.milkdown{${crepeLightHouseTokens}}`,
  `@media (prefers-color-scheme: dark){:root:not([data-theme='light']) .milkdown{${crepeDarkHouseTokens}}}`,
  `:root[data-theme='dark'] .milkdown{${crepeDarkHouseTokens}}`,
  `.milkdown :focus-visible{outline:2px solid var(--ring-border,color-mix(in srgb,var(--brand,#9449bc) 50%,transparent))!important;outline-offset:2px}`,
  `@media (prefers-reduced-motion: reduce){.milkdown *,.milkdown *::before,.milkdown *::after{animation-delay:0ms!important;animation-duration:0.001ms!important;animation-iteration-count:1!important;scroll-behavior:auto!important;transition-delay:0ms!important;transition-duration:0.001ms!important}}`,
].join("\n");
emit(
  "crepeTheme.generated.ts",
  "crepeThemeCss",
  crepeCss,
  "Milkdown Crepe CSS (common + house light/dark token bridge), pre-bundled for the Smithers UI <style> injection.",
);
emitTo(
  uiAdapterDir,
  "crepeTheme.generated.ts",
  "crepeThemeCss",
  crepeCss,
  "Milkdown Crepe CSS (common + house light/dark token bridge), pre-bundled for the @smthrs/ui markdown-editor adapter <style> injection.",
);
emitTo(
  exampleUiDir,
  "crepeTheme.generated.ts",
  "crepeThemeCss",
  crepeCss,
  "Milkdown Crepe CSS (common + house light/dark token bridge), pre-bundled for the Smithers UI <style> injection.",
);

// ---- xyflow base stylesheet (required for canvas/edges/controls) ----
const xyflowCss = await bundleCss(`@import "@xyflow/react/dist/style.css";`);
emit(
  "xyflowTheme.generated.ts",
  "xyflowThemeCss",
  xyflowCss,
  "@xyflow/react base stylesheet, pre-bundled for the Smithers UI <style> injection.",
);
emitTo(
  exampleUiDir,
  "xyflowTheme.generated.ts",
  "xyflowThemeCss",
  xyflowCss,
  "@xyflow/react base stylesheet, pre-bundled for the Smithers UI <style> injection.",
);
