#!/usr/bin/env bun
/**
 * Embed the canonical `smithers init` pack templates into the CLI package.
 *
 * Edit files under apps/cli/templates/init-pack/, then run:
 *   bun scripts/generate-init-templates.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const INIT_TEMPLATE_ROOT = resolve(REPO_ROOT, "apps/cli/templates/init-pack");
export const INIT_TEMPLATE_OUTPUT = resolve(REPO_ROOT, "apps/cli/src/init-templates.generated.js");

export type InitTemplateSpec = {
  sourcePath: string;
  path: string;
  preserveExisting?: boolean;
};

export type InitTemplateFile = InitTemplateSpec & {
  contents: string;
};

export const INIT_TEMPLATE_SPECS: InitTemplateSpec[] = [
  { sourcePath: ".gitignore", path: ".smithers/.gitignore" },
  { sourcePath: "workflows/.gitignore", path: ".smithers/workflows/.gitignore" },
  { sourcePath: "tsconfig.json", path: ".smithers/tsconfig.json" },
  { sourcePath: "types/assets.d.ts.tmpl", path: ".smithers/types/assets.d.ts" },
  { sourcePath: "bunfig.toml", path: ".smithers/bunfig.toml" },
  { sourcePath: "preload.ts.tmpl", path: ".smithers/preload.ts" },
  { sourcePath: "gateway.ts.tmpl", path: ".smithers/gateway.ts" },
  { sourcePath: "agents/claude-code.ts.tmpl", path: ".smithers/agents/claude-code.ts", preserveExisting: true },
  { sourcePath: "agents/codex.ts.tmpl", path: ".smithers/agents/codex.ts", preserveExisting: true },
  { sourcePath: "agents/cursor.ts.tmpl", path: ".smithers/agents/cursor.ts", preserveExisting: true },
  { sourcePath: "agents/opencode.ts.tmpl", path: ".smithers/agents/opencode.ts", preserveExisting: true },
  { sourcePath: "agents/antigravity.ts.tmpl", path: ".smithers/agents/antigravity.ts", preserveExisting: true },
  { sourcePath: "agents/custom.ts.tmpl", path: ".smithers/agents/custom.ts", preserveExisting: true },
  { sourcePath: "agents/index.ts.tmpl", path: ".smithers/agents/index.ts", preserveExisting: true },
  { sourcePath: "agents/README.md", path: ".smithers/agents/README.md", preserveExisting: true },
  { sourcePath: "smithers.config.ts.tmpl", path: ".smithers/smithers.config.ts" },
  { sourcePath: "skills/.gitkeep", path: ".smithers/skills/.gitkeep" },
  { sourcePath: "tickets/.gitkeep", path: ".smithers/tickets/.gitkeep" },
];

export function buildInitTemplates(templateRoot = INIT_TEMPLATE_ROOT): InitTemplateFile[] {
  return INIT_TEMPLATE_SPECS.map((spec) => ({
    ...spec,
    contents: readFileSync(resolve(templateRoot, spec.sourcePath), "utf8"),
  }));
}

export function renderInitTemplatesModule(files: InitTemplateFile[]): string {
  const banner = [
    "// AUTO-GENERATED by scripts/generate-init-templates.ts — DO NOT EDIT BY HAND.",
    "// Edit apps/cli/templates/init-pack/ and re-run the generator.",
    "",
    "/** @typedef {{ sourcePath: string; path: string; contents: string; preserveExisting?: boolean }} InitTemplateFile */",
    "",
    "/** @type {InitTemplateFile[]} */",
    "export const GENERATED_INIT_TEMPLATES = ",
  ].join("\n");
  return `${banner}${JSON.stringify(files, null, 2)};\n`;
}

export function generateInitTemplates(options: { templateRoot?: string; outputFile?: string } = {}) {
  const files = buildInitTemplates(options.templateRoot);
  const output = renderInitTemplatesModule(files);
  const outputFile = options.outputFile ?? INIT_TEMPLATE_OUTPUT;
  writeFileSync(outputFile, output, "utf8");
  return { files, output, outputFile };
}

export function runInitTemplateGenerator(
  options: { templateRoot?: string; outputFile?: string } = {},
  log: (message: string) => void = process.stdout.write.bind(process.stdout),
) {
  const result = generateInitTemplates(options);
  log(
    `[generate-init-templates] wrote ${result.files.length} template(s) to ${result.outputFile.replace(REPO_ROOT + "/", "")}\n`,
  );
  return result;
}

/* c8 ignore next 3 */
if (import.meta.main) {
  runInitTemplateGenerator();
}
