/**
 * The Smithers gateway bundles `.smithers/ui/*.tsx` with Bun.build and serves
 * only the JS output — CSS imports are dropped. The convention (mirrored from
 * the multi app) is to pre-bundle third-party component CSS into a TS string
 * that the UI injects via a `<style>` tag.
 *
 * This generates two modules used by `.smithers/ui/create-workflow.tsx`:
 *   - crepeTheme.generated.ts  — Milkdown Crepe theme (common + light/dark frame)
 *   - xyflowTheme.generated.ts — @xyflow/react base stylesheet
 *
 * Run: bun scripts/generate-ui-themes.ts
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const uiDir = resolve(root, ".smithers/ui");

/**
 * Bundle a CSS entry (resolving @import + node_modules exports) into one string.
 * Fonts/icons referenced via url() are kept external (not inlined) so the
 * generated string stays small — mirrors the multi app's generator.
 */
async function bundleCss(entryCss: string): Promise<string> {
  const result = await build({
    stdin: { contents: entryCss, resolveDir: root, loader: "css" },
    bundle: true,
    write: false,
    minify: true,
    external: ["*.woff", "*.woff2", "*.ttf", "*.eot", "*.svg", "*.png"],
    logLevel: "silent",
  });
  const css = result.outputFiles?.[0]?.text?.trim() ?? "";
  if (!css) throw new Error(`empty CSS for "${entryCss}"`);
  return css;
}

function emit(file: string, exportName: string, css: string, note: string) {
  const outPath = resolve(uiDir, file);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(
    outPath,
    `// Generated by scripts/generate-ui-themes.ts — do not edit.\n// ${note}\nexport const ${exportName} = ${JSON.stringify(css)};\n`,
  );
  console.log(`${file}: ${css.length} chars -> ${outPath}`);
}

// ---- Crepe (Milkdown) theme: structural common + light/dark frame ----
const crepeCommon = await bundleCss(`@import "@milkdown/crepe/theme/common/style.css";`);
const crepeLight = await bundleCss(`@import "@milkdown/crepe/theme/frame.css";`);
const crepeDark = await bundleCss(`@import "@milkdown/crepe/theme/frame-dark.css";`);
const crepeCss = [
  crepeCommon,
  `@media (prefers-color-scheme: light){${crepeLight}}`,
  `@media (prefers-color-scheme: dark){${crepeDark}}`,
].join("\n");
emit(
  "crepeTheme.generated.ts",
  "crepeThemeCss",
  crepeCss,
  "Milkdown Crepe theme CSS (common + light/dark frame), pre-bundled for the Smithers UI <style> injection.",
);

// ---- xyflow base stylesheet (required for canvas/edges/controls) ----
const xyflowCss = await bundleCss(`@import "@xyflow/react/dist/style.css";`);
emit(
  "xyflowTheme.generated.ts",
  "xyflowThemeCss",
  xyflowCss,
  "@xyflow/react base stylesheet, pre-bundled for the Smithers UI <style> injection.",
);
