/**
 * Alchemy infrastructure-as-code for cli.smithers.sh, the @smthrs/cli docs site.
 * Generated by apps/docs/shared/gen-sites.mjs from apps/docs/shared/manifest.mjs. Edit the generator, then rerun it: node apps/docs/shared/gen-sites.mjs
 *
 * Deploy:   CLOUDFLARE_API_TOKEN=... CLI_WORKER_NAME=... pnpm -C apps/docs/cli deploy
 * Destroy:  pnpm -C apps/docs/cli destroy
 *
 * Required: CLI_WORKER_NAME, preserving the existing Worker name.
 * See apps/docs/README.md for Alchemy 1 state migration and explicit adoption.
 * Optional env: CLI_SITE_DOMAIN (preview deploys, default cli.smithers.sh),
 * CLOUDFLARE_SMITHERS_ZONE_ID (alchemy resolves the zone from the domain when
 * omitted).
 */
import { makeDocsSiteStack } from "@smithers/docs-shared/alchemy-site"

export default makeDocsSiteStack({ slug: "cli" })
