#!/usr/bin/env node
/** Projects package-owned Bun host documentation into the repository site. */
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { Package } from "../Package.ts"

const check = process.argv.includes("--check")
const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const repoRoot = join(packageRoot, "..", "..")
const read = (path) => readFileSync(path, "utf8")

const ungutter = (block) =>
  block.split("\n").map((line) => line.replace(/^\s*\* ?/, "")).join("\n")

const description = (body) => {
  const lines = []
  for (const line of body.split("\n")) {
    if (/^@\w+/.test(line)) break
    lines.push(line)
  }
  return lines.join("\n").trim()
}

const delink = (value) => value.replace(/\{@link\s+([^}]+)\}/g, "`$1`")

const paragraphs = (value) => {
  const blocks = []
  let current = []
  let fence = []
  let fenced = false
  for (const line of value.split("\n")) {
    if (/^```/.test(line)) {
      if (fenced) {
        fence.push(line)
        blocks.push(fence.join("\n"))
        fence = []
      } else {
        if (current.length > 0) blocks.push(current.join(" "))
        current = []
        fence = [line]
      }
      fenced = !fenced
      continue
    }
    if (fenced) {
      fence.push(line)
      continue
    }
    if (line.trim() === "") {
      if (current.length > 0) blocks.push(current.join(" "))
      current = []
    } else current.push(line.trim())
  }
  if (current.length > 0) blocks.push(current.join(" "))
  return blocks.join("\n\n")
}

const firstSentence = (value) => {
  const flat = delink(value).split("\n\n")[0].split("\n").join(" ")
  const sentence = (/^[\s\S]*?\.(?=\s|$)/.exec(flat)?.[0] ?? flat).trim()
  return sentence.replace(/\s+—\s+[\s\S]*$/, ".")
}

const moduleDoc = (source) => {
  const match = /\/\*\*([\s\S]*?)\*\//.exec(source)
  if (match === null) throw new Error("platform-bun docs: no module JSDoc block")
  return delink(description(ungutter(match[1])))
}

const exportedDocs = (source) => {
  const entries = []
  const pattern = /\/\*\*((?:[^*]|\*(?!\/))*)\*\/\s*\nexport (type|const|class|interface|function) (\w+)/g
  for (let match = pattern.exec(source); match !== null; match = pattern.exec(source)) {
    const body = ungutter(match[1])
    const category = /@category (\S+)/.exec(body)?.[1]
    if (category === undefined) continue
    entries.push({
      name: match[3],
      declaration: match[2],
      category,
      summary: firstSentence(description(body))
    })
  }
  return entries
}

const manifest = JSON.parse(read(join(packageRoot, "package.json")))
if (manifest.name !== Package.name) throw new Error("platform-bun docs: Package.ts and package.json names differ")

const barrel = read(join(packageRoot, "src", "index.ts"))
const modules = [...barrel.matchAll(/export \* as (\w+) from "\.\/(\w+)\.ts"/g)].map((match) => ({
  namespace: match[1],
  file: match[2]
}))
const rows = new Map()
for (const module of modules) {
  for (const entry of exportedDocs(read(join(packageRoot, "src", `${module.file}.ts`)))) {
    const name = `${module.namespace}.${entry.name}`
    const seen = rows.get(name)
    if (seen === undefined) rows.set(name, { ...entry, declarations: [entry.declaration] })
    else if (!seen.declarations.includes(entry.declaration)) seen.declarations.push(entry.declaration)
  }
}
if (rows.size === 0) throw new Error("platform-bun docs: no documented exports found")

const tableRows = [
  ["Export", "Kind", "Category", "Summary"],
  ...[...rows].map(([name, entry]) => [
    `\`${name}\``,
    entry.declarations.join(" + "),
    entry.category,
    entry.summary
  ])
]
const tableWidths = tableRows[0].map((_, index) =>
  Math.max(3, ...tableRows.map((row) => row[index].length))
)
const tableRow = (row) => `| ${row.map((cell, index) => cell.padEnd(tableWidths[index])).join(" | ")} |`
const table = [
  tableRow(tableRows[0]),
  tableRow(tableWidths.map((width) => "-".repeat(width))),
  ...tableRows.slice(1).map(tableRow)
].join("\n")

const apiPage = `---
description: "${manifest.description}."
---

{/* Generated by \`node packages/platform-bun/scripts/docs.mjs\` from packages/platform-bun. Edit package sources, never this file. */}

# @smthrs/platform-bun

${paragraphs(moduleDoc(barrel))}

${read(join(packageRoot, Package.api.source)).trim()}

## Exports

${table}
`

const outputs = new Map([[Package.api.target, apiPage]])

const failures = []
for (const path of Package.references) {
  const content = read(join(repoRoot, path))
  if (!content.includes(Package.name) || !content.includes("/api/platform-bun")) {
    failures.push(`${path}: must reference ${Package.name} and /api/platform-bun`)
  }
}
for (const [path, content] of outputs) {
  if (content.includes("—")) failures.push(`${path}: generated content contains an em-dash`)
}

let drifted = false
for (const [path, content] of outputs) {
  const absolute = join(repoRoot, path)
  if (read(absolute) === content) continue
  drifted = true
  if (check) failures.push(`${path}: drifted; run node packages/platform-bun/scripts/docs.mjs`)
  else {
    writeFileSync(absolute, content)
    console.log(`wrote ${path}`)
  }
}

if (failures.length > 0) {
  for (const failure of failures) console.error(`✗ ${failure}`)
  process.exit(1)
}

console.log(
  check
    ? "✓ the platform-bun package documentation is current"
    : drifted
    ? "✓ platform-bun package documentation regenerated"
    : "✓ platform-bun package documentation already current"
)
