import type { ReviewRunOutput } from "smithers-workflows/lib/open-code-review";
import type { Story } from "../walkthrough/storySchema";

type Finding = ReviewRunOutput["comments"][number];

export type PullRequestReviewPayload = {
  commit_id: string;
  event: "COMMENT";
  body: string;
  comments: Array<{
    path: string;
    line: number;
    side: "RIGHT";
    start_line?: number;
    start_side?: "RIGHT";
    body: string;
  }>;
};

const MAX_BODY_CHARS = 60_000;
const MAX_FILES_PER_CHAPTER = 30;

function findingBody(finding: Finding): string {
  const parts = [finding.content];
  if (finding.suggestionCode) {
    parts.push("", "```suggestion", finding.suggestionCode, "```");
  }
  return parts.join("\n");
}

function unanchoredLine(finding: Finding): string {
  const loc = finding.startLine > 0 ? `:${finding.startLine}` : "";
  return `- \`${finding.path}${loc}\` — ${finding.content.split("\n").join(" ")}`;
}

/**
 * Compose one PR review from the story and findings: a narrative body
 * (headline, synopsis, reading order, walkthrough link) plus inline comments
 * for every finding that anchors into the PR diff. Findings that cannot
 * anchor (no resolved lines, or path not in the PR) are listed in the body
 * instead, so nothing is dropped.
 */
export function buildPullRequestReview(args: {
  story: Story;
  findings: Finding[];
  prPaths: Set<string>;
  headSha: string;
  walkthroughUrl?: string;
}): PullRequestReviewPayload {
  const anchored: PullRequestReviewPayload["comments"] = [];
  const unanchored: Finding[] = [];
  for (const finding of args.findings) {
    if (finding.startLine > 0 && args.prPaths.has(finding.path)) {
      const multiLine = finding.endLine > finding.startLine;
      anchored.push({
        path: finding.path,
        line: multiLine ? finding.endLine : finding.startLine,
        side: "RIGHT",
        ...(multiLine ? { start_line: finding.startLine, start_side: "RIGHT" as const } : {}),
        body: findingBody(finding),
      });
    } else {
      unanchored.push(finding);
    }
  }

  const lines: string[] = ["<!-- smithers-review -->"];
  lines.push(`## smithers review — ${args.story.headline || "change walkthrough"}`);
  if (args.story.synopsis) lines.push("", args.story.synopsis);
  if (args.walkthroughUrl) lines.push("", `**📖 Full walkthrough:** ${args.walkthroughUrl}`);

  if (args.story.chapters.length > 0) {
    lines.push("", "### Reading order");
    args.story.chapters.forEach((chapter, index) => {
      lines.push("", `**${index + 1}. ${chapter.title}**`);
      if (chapter.narrative) lines.push("", chapter.narrative);
      const shown = chapter.files.slice(0, MAX_FILES_PER_CHAPTER);
      for (const file of shown) {
        lines.push(`- \`${file.path}\`${file.role ? ` — ${file.role}` : ""}`);
      }
      const hidden = chapter.files.length - shown.length;
      if (hidden > 0) lines.push(`- …and ${hidden} more file(s)`);
    });
  }

  if (unanchored.length > 0) {
    lines.push("", `### Findings without inline anchors (${unanchored.length})`);
    lines.push(...unanchored.map(unanchoredLine));
  }

  lines.push(
    "",
    `_${args.findings.length} finding(s) · ${anchored.length} inline · generated by smithers review_`,
  );

  let body = lines.join("\n");
  if (body.length > MAX_BODY_CHARS) {
    body = `${body.slice(0, MAX_BODY_CHARS)}\n\n_…truncated; see the full walkthrough._`;
  }

  return { commit_id: args.headSha, event: "COMMENT", body, comments: anchored };
}
