#!/usr/bin/env node
/** Projects package-owned CLI API documentation into the repository site. */
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join, posix } from "node:path"
import { fileURLToPath } from "node:url"
import { Manifest } from "../docs/Manifest.ts"

const check = process.argv.includes("--check")
const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const repoRoot = join(packageRoot, "..", "..")
const read = (path) => readFileSync(path, "utf8")
const readModule = (relative) => read(join(packageRoot, "src", relative))

const ungutter = (block) => block.split("\n").map((line) => line.replace(/^\s*\* ?/, "")).join("\n")

const description = (body) => {
  const lines = []
  for (const line of body.split("\n")) {
    if (/^@\w+/.test(line)) break
    lines.push(line)
  }
  return lines.join("\n").trim()
}

const delink = (value) =>
  value
    .replace(/\{@link\s+(https?:\/\/\S+)\s*\|\s*([^}]+)\}/g, (_, url, label) => `[${label.trim()}](${url})`)
    .replace(/\{@link\s+(https?:\/\/\S+?)\s*\}/g, (_, url) => `<${url}>`)
    .replace(/\{@link\s+([^}|]+)\|([^}]+)\}/g, (_, __, label) => `\`${label.trim()}\``)
    .replace(/\{@link\s+([^}]+)\}/g, (_, symbol) => `\`${symbol.trim()}\``)

const paragraphs = (value) => {
  const blocks = []
  let current = []
  for (const line of value.split("\n")) {
    if (line.trim() === "") {
      if (current.length > 0) blocks.push(current.join(" "))
      current = []
    } else current.push(line.trim())
  }
  if (current.length > 0) blocks.push(current.join(" "))
  return blocks.join("\n\n")
}

const firstSentence = (value) => {
  const flat = delink(value).split("\n\n")[0].split("\n").join(" ")
  return (/^[\s\S]*?\.(?=\s|$)/.exec(flat)?.[0] ?? flat).trim()
}

const moduleDoc = (source) => {
  const match = /\/\*\*((?:[^*]|\*(?!\/))*)\*\//.exec(source)
  if (match === null) throw new Error("cli docs: no module JSDoc block")
  return delink(description(ungutter(match[1])))
}

const exportedDocs = (source, relative, prefix) => {
  const entries = []
  const pattern = /\/\*\*((?:[^*]|\*(?!\/))*)\*\/\s*\nexport (type|const|class|interface|function) (\w+)/g
  for (let match = pattern.exec(source); match !== null; match = pattern.exec(source)) {
    const body = ungutter(match[1])
    const category = /@category (\S+)/.exec(body)?.[1]
    if (category === undefined) continue
    entries.push({
      name: `${prefix}${match[3]}`,
      declaration: match[2],
      category,
      module: relative,
      summary: firstSentence(description(body))
    })
  }
  return entries
}

const collect = (relative, prefix, seen) => {
  if (seen.has(relative)) return []
  seen.add(relative)
  const source = readModule(relative)
  const directory = posix.dirname(relative)
  const resolve = (specifier) => posix.normalize(posix.join(directory, specifier))
  const entries = exportedDocs(source, relative, prefix)
  for (const match of source.matchAll(/export \* (?:as (\w+) )?from "(\.[\w./-]+)"/g)) {
    const nested = match[1] === undefined ? prefix : `${prefix}${match[1]}.`
    entries.push(...collect(resolve(match[2]), nested, seen))
  }
  return entries
}

const manifest = JSON.parse(read(join(packageRoot, "package.json")))
if (manifest.name !== Manifest.name) throw new Error("cli docs: Manifest.ts and package.json names differ")
if (Manifest.snippets.length > 0) throw new Error("cli docs: snippet projection is not implemented")

const barrel = readModule("index.ts")
const exports = collect("index.ts", "", new Set())
if (exports.length === 0) throw new Error("cli docs: no documented exports found")

const table = [
  "| Export | Kind | Summary |",
  "| --- | --- | --- |",
  ...exports.map((entry) => `| \`${entry.name}\` (${entry.declaration}) | ${entry.category} | ${entry.summary} |`)
].join("\n")

const apiPage = `---
description: "${manifest.description}."
---

{/* Generated by \`node packages/cli/scripts/docs.mjs\` from packages/cli. Edit package sources, never this file. */}

# @smthrs/cli

${paragraphs(moduleDoc(barrel))}

${read(join(packageRoot, Manifest.api.source)).trim()}

## Exports

${table}
`

const outputs = new Map([[Manifest.api.target, apiPage]])
const failures = []
for (const path of Manifest.references) {
  const content = read(join(repoRoot, path))
  if (!content.includes(Manifest.name) || !content.includes("/api/cli")) {
    failures.push(`${path}: must reference ${Manifest.name} and /api/cli`)
  }
}
for (const [path, content] of outputs) {
  if (content.includes("—")) failures.push(`${path}: generated content contains an em-dash`)
}

let drifted = false
for (const [path, content] of outputs) {
  const absolute = join(repoRoot, path)
  let current
  try {
    current = read(absolute)
  } catch {
    current = undefined
  }
  if (current === content) continue
  drifted = true
  if (check) failures.push(`${path}: drifted; run node packages/cli/scripts/docs.mjs`)
  else {
    writeFileSync(absolute, content)
    console.log(`wrote ${path}`)
  }
}

if (failures.length > 0) {
  for (const failure of failures) console.error(`✗ ${failure}`)
  process.exit(1)
}

console.log(
  check
    ? "✓ the CLI package documentation is current"
    : drifted
    ? "✓ CLI package documentation regenerated"
    : "✓ CLI package documentation already current"
)
