#!/usr/bin/env node
/** Projects package-owned flows documentation into the site. */
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { Package } from "../Package.ts"

const check = process.argv.includes("--check")
const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const repositoryRoot = join(packageRoot, "..", "..")
const read = (path) => readFileSync(path, "utf8")
const cell = (value) => value.replaceAll("|", "\\|").replace(/\s+/g, " ").trim()
const ungutter = (block) => block.split("\n").map((line) => line.replace(/^\s*\* ?/, "")).join("\n")

const description = (body) => {
  const lines = []
  for (const line of body.split("\n")) {
    if (/^@\w+/.test(line)) break
    lines.push(line)
  }
  return lines.join("\n").trim()
}

const firstSentence = (value) => {
  const flat = value.replace(/\{@link\s+([^}]+)\}/g, "`$1`").split("\n\n")[0].replace(/\s+/g, " ")
  return (/^[\s\S]*?\.(?=\s|$)/.exec(flat)?.[0] ?? flat).trim()
}

const replaceMarker = (source, marker, body) => {
  const token = `<!-- generated:${marker} -->`
  if (source.split(token).length !== 2) throw new Error(`flows docs: expected one ${token}`)
  return source.replace(token, body)
}

const barrel = read(join(packageRoot, "src", "index.ts"))
const namespaces = [...barrel.matchAll(/export \* as (\w+) from "(@smthrs\/[^"]+)"/g)]
  .map((match) => ({ name: match[1], source: match[2] }))
const runtimeNamesMatch = /export const namespaces = \[([\s\S]*?)\] as const/.exec(barrel)
if (runtimeNamesMatch === null) throw new Error("flows docs: namespaces constant is missing")
const runtimeNames = [...runtimeNamesMatch[1].matchAll(/"([^"]+)"/g)].map((match) => match[1])
const namespaced = new Set(namespaces.map(({ name }) => name))
const flat = runtimeNames.filter((name) => !namespaced.has(name))
const namespaceTable = [
  "| Export | Source | Shape |",
  "| --- | --- | --- |",
  ...namespaces.map(({ name, source }) => `| \`${name}\` | \`${source}\` | namespace |`),
  `| ${flat.map((name) => `\`${name}\``).join(", ")} | \`@smthrs/flow\` and \`@smthrs/time-travel\` | flat |`
].join("\n")

/** The documented exports of one source module, as a table. */
const exportTable = (module) => {
  const source = read(join(packageRoot, "src", `${module}.ts`))
  const exports = []
  const exported = /^\/\*\*((?:[^*]|\*(?!\/))*)\*\/\s*\nexport (type|const|class|interface) (\w+)/gm
  for (let match = exported.exec(source); match !== null; match = exported.exec(source)) {
    const body = ungutter(match[1])
    const category = /@category (\S+)/.exec(body)?.[1]
    if (category === undefined) continue
    exports.push({
      name: match[3],
      kind: match[2],
      category,
      summary: firstSentence(description(body))
    })
  }
  if (exports.length === 0) throw new Error(`flows docs: ${module} documents no exports`)
  return [
    "| Export | Kind | Category | Summary |",
    "| --- | --- | --- | --- |",
    ...exports.map((entry) =>
      `| \`${entry.name}\` | ${entry.kind} | ${entry.category} | ${cell(entry.summary)} |`
    )
  ].join("\n")
}

const nodeTable = exportTable("NodeRuntime")
const sandboxedTable = exportTable("SandboxedFlow")

const manifest = JSON.parse(read(join(packageRoot, "package.json")))
if (manifest.name !== Package.name) throw new Error("flows docs: Package.ts and package.json names differ")
const narrative = replaceMarker(
  replaceMarker(
    replaceMarker(read(join(packageRoot, Package.api.source)), "namespaces", namespaceTable),
    "node-runtime",
    nodeTable
  ),
  "sandboxed-flow",
  sandboxedTable
)
const output = `---\ndescription: "${manifest.description}."\n---\n\n`
  + `{/* Generated by \`node packages/flows/scripts/docs.mjs\`. Edit packages/flows sources. */}\n\n`
  + narrative.trim()
  + "\n"

const failures = []
for (const path of Package.references) {
  const content = read(join(repositoryRoot, path))
  if (!content.includes(Package.name) || !content.includes("/api/flows")) {
    failures.push(`${path}: must reference ${Package.name} and /api/flows`)
  }
}
if (output.includes("—")) failures.push(`${Package.api.target}: generated content contains an em-dash`)

const target = join(repositoryRoot, Package.api.target)
const drifted = read(target) !== output
if (drifted && check) failures.push(`${Package.api.target}: drifted; run node packages/flows/scripts/docs.mjs`)
else if (drifted) {
  writeFileSync(target, output)
  console.log(`wrote ${Package.api.target}`)
}

if (failures.length > 0) {
  for (const failure of failures) console.error(`✗ ${failure}`)
  process.exit(1)
}
console.log(check ? "✓ flows documentation is current" : "✓ flows documentation regenerated")
