import { expect, test } from "@playwright/test"

test("onboarding persists a real interaction and hands off to the conversation", async ({ page }) => {
  await page.goto("/")
  await expect(page.locator(".guide-dialogue > p")).toHaveText("Hello. I’m Smithers. Let me show how Smithers works")
  await expect(page.locator(".guide-lesson h1, .guide-sigil")).toHaveCount(0)
  await expect(page.getByTestId("composer-input")).toBeHidden()
  await expect(page.getByRole("navigation", { name: "Installed capabilities" })).toBeHidden()
  const greeting = await page.locator('[data-message-step="0"]').elementHandle()
  await page.getByRole("button", { name: "Let’s begin" }).click()
  await expect(page.getByRole("log", { name: "Onboarding chat history" }).locator("article")).toHaveCount(2)
  expect(await greeting?.evaluate(node => node.isConnected)).toBe(true)
  await expect(page.locator('[data-message-step="1"]')).toContainText("I can speak to you normally like this")
  await expect(page.locator(".guide-action-current")).toHaveCSS("animation-name", "guide-actions-in")
  await page.getByRole("button", { name: "Continue", exact: true }).click()
  await page.getByRole("button", { name: "Send me a notification" }).click()
  await expect(page.getByText("You can keep working", { exact: true })).toBeVisible()
  await page.getByRole("button", { name: "Continue", exact: true }).click()
  await page.getByLabel("How did you hear about Smithers?").fill('A friend called "Sam" ')
  await expect(page.getByLabel("How did you hear about Smithers?")).toHaveAttribute(
    "data-saved-value",
    'A friend called "Sam" ',
  )
  await expect(page.getByText("Saved on this device. Both answers are optional.")).toBeVisible()
  await page.getByLabel("What would you love to build?").focus()
  await page.reload()
  await expect(page.getByLabel("How did you hear about Smithers?")).toHaveValue('A friend called "Sam" ')
  await expect(page.locator(".guide-transcript article")).toHaveCount(4)
  await page.getByRole("button", { name: "Continue, with or without answers" }).click()
  await page.getByRole("button", { name: "Continue", exact: true }).click()
  await page.getByRole("button", { name: "Run dark-mode flow" }).click()
  await expect(page.locator("html")).toHaveAttribute("data-theme", "dark")
  await page.getByRole("button", { name: "Bring back the light" }).click()
  await expect(page.locator("html")).toHaveAttribute("data-theme", "light")
  await page.keyboard.press("Control+k")
  await expect(page.getByRole("dialog", { name: "Talk to Smithers" })).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(page.getByRole("dialog")).toBeHidden()
  await page.getByRole("button", { name: "Install Library" }).click()
  await expect(page.getByRole("navigation", { name: "Installed capabilities" })).toBeVisible()
  await page.getByRole("button", { name: "Add Librarian" }).click()
  await page.getByRole("button", { name: "Let’s make something" }).click()
  await page.getByRole("button", { name: "Try editing it" }).click()
  await page.getByLabel("Prototype heading").fill("A garden of possible futures")
  await expect(page.locator(".guide-board h2")).toHaveText("A garden of possible futures")
  await page.getByRole("button", { name: "Keep this direction" }).click()
  await expect(page.locator(".guide-history")).toContainText("A garden of possible futures")
  await page.getByRole("button", { name: "See the path to a PR" }).click()
  await expect(page.locator(".guide-pr")).toContainText("nothing has been pushed or published")
  await expect(page.getByLabel("Practice heading change")).toContainText("A garden of possible futures")
  await page.getByRole("button", { name: "I’d like to change something" }).click()
  await page.getByLabel("Prototype heading").fill("A garden worth growing")
  await page.getByRole("button", { name: "Keep this direction" }).click()
  await page.getByRole("button", { name: "See the path to a PR" }).click()
  await expect(page.getByLabel("Practice heading change")).toContainText("A garden worth growing")
  await page.getByRole("button", { name: "Accept practice change" }).click()
  await expect(page.locator(".guide-review-accepted")).toContainText("A garden worth growing")
  await page.keyboard.press("Control+k")
  await expect(page.getByTestId("composer-input")).toBeVisible()
  await page.getByTestId("composer-input").fill("say ok")
  await page.getByTestId("composer-send").click()
  await expect(
    page.locator('.smithers-chat-message[data-role="assistant"]', { hasText: "stub: say ok" }),
  ).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(page.getByRole("dialog")).toBeHidden()
  await page.reload()
  await expect(page.locator(".guide-shell")).toHaveAttribute("data-step", "15")
  await expect(page.getByTestId("composer-input")).toBeHidden()
})

test("small screens and reduced motion preserve the first action", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: "reduce" })
  await page.goto("/")
  await expect(page.getByRole("button", { name: "Let’s begin" })).toBeVisible()
  expect(await page.locator(".guide-wordmark").evaluate((el) => getComputedStyle(el).animationName)).toBe(
    "none",
  )
  expect(await page.locator(".guide-shell").evaluate((el) => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.keyboard.press("Control+k")
  await expect(page.getByTestId("composer-input")).toBeFocused()
  await page.keyboard.press("Escape")
  await expect(page.getByRole("dialog")).toBeHidden()
})

test("the entire introduction is completable with only a keyboard", async ({ page }) => {
  await page.goto("/")
  const shell = page.locator(".guide-shell")
  await expect(shell).toHaveAttribute("data-step", "0")
  await expect(page.locator(".guide-action-current .guide-actions .guide-primary .guide-button-key")).toHaveText("↵ Enter")
  for (let step = 1; step <= 3; step++) {
    await page.keyboard.press(step % 2 ? "Enter" : "ArrowRight")
    await expect(shell).toHaveAttribute("data-step", String(step))
    await expect(page.locator(".guide-lesson h1, .guide-eyebrow, .guide-chapter, .guide-sigil")).toHaveCount(0)
    await expect(page.locator(".guide-dialogue > p")).toHaveCount(step + 1)
    if (step === 2) {
      await expect(page.getByRole("button", { name: "Send me a notification" }).locator("kbd")).toHaveText("N")
      await page.keyboard.press("n")
      await expect(page.getByText("You can keep working", { exact: true })).toBeVisible()
      await expect(shell).toHaveAttribute("data-step", "2")
    }
    if (step < 15) {
      await expect(page.locator(".guide-action-current .guide-actions .guide-primary .guide-button-key").last()).toHaveText("↵ Enter")
      await expect(page.locator(".guide-action-current .guide-back .guide-button-key")).toHaveText("←")
    }
  }
  await page.keyboard.press("Tab")
  await expect(page.getByRole("log", { name: "Onboarding chat history" })).toBeFocused()
  await page.keyboard.press("Tab")
  await expect(page.getByLabel("How did you hear about Smithers?")).toBeFocused()
  await page.keyboard.type("A friend told me")
  await page.keyboard.press("ArrowLeft")
  await page.keyboard.type("!")
  await expect(page.getByLabel("How did you hear about Smithers?")).toHaveValue("A friend told m!e")
  await expect(shell).toHaveAttribute("data-step", "3")
  await page.keyboard.press("Enter")
  await expect(shell).toHaveAttribute("data-step", "4")
  for (let step = 5; step <= 7; step++) {
    await page.keyboard.press("ArrowRight")
    await expect(shell).toHaveAttribute("data-step", String(step))
    await expect(page.locator(".guide-lesson h1, .guide-eyebrow, .guide-chapter, .guide-sigil")).toHaveCount(0)
    await expect(page.locator(".guide-dialogue > p")).toHaveCount(step + 1)
    if (step < 15) {
      await expect(page.locator(".guide-action-current .guide-actions .guide-primary .guide-button-key").last()).toHaveText("↵ Enter")
      await expect(page.locator(".guide-action-current .guide-back .guide-button-key")).toHaveText("←")
    }
  }
  await page.keyboard.press("ArrowLeft")
  await expect(shell).toHaveAttribute("data-step", "6")
  await page.keyboard.press("ArrowRight")
  await expect(shell).toHaveAttribute("data-step", "7")
  await page.keyboard.press("Control+k")
  await expect(page.getByRole("dialog")).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(page.getByRole("dialog")).toBeHidden()
  for (let step = 9; step <= 15; step++) {
    await page.keyboard.press("ArrowRight")
    await expect(shell).toHaveAttribute("data-step", String(step))
    await expect(page.locator(".guide-lesson h1, .guide-eyebrow, .guide-chapter, .guide-sigil")).toHaveCount(0)
    await expect(page.locator(".guide-dialogue > p")).toHaveCount(step + 1)
    if (step < 15) {
      await expect(page.locator(".guide-action-current .guide-actions .guide-primary .guide-button-key").last()).toHaveText("↵ Enter")
      await expect(page.locator(".guide-action-current .guide-back .guide-button-key")).toHaveText("←")
    }
  }
  await page.keyboard.press("Control+k")
  await expect(page.getByTestId("composer-input")).toBeFocused()
  await page.keyboard.type("say ok")
  await page.keyboard.press("Enter")
  await expect(
    page.locator('.smithers-chat-message[data-role="assistant"]', { hasText: "stub: say ok" }),
  ).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(page.getByRole("dialog")).toBeHidden()
})

test("Command K can replay the tutorial and reset a returning user", async ({ page }) => {
  await page.goto("/")
  await expect(page.locator(".guide-shell")).toHaveAttribute("data-step", "0")
  await page.keyboard.press("ArrowRight")
  await page.keyboard.press("Control+k")
  await page.getByTestId("composer-input").fill("/tut")
  await page.keyboard.press("Enter")
  await expect(page.locator(".guide-shell")).toHaveAttribute("data-step", "0")
  await expect(page.getByTestId("composer-input")).toBeHidden()
  // Even the special Library greeting must keep the command input reachable.
  for (let step = 1; step <= 7; step++) {
    await page.keyboard.press("ArrowRight")
    await expect(page.locator(".guide-shell")).toHaveAttribute("data-step", String(step))
  }
  await page.keyboard.press("Control+k")
  await expect(page.getByTestId("composer-input")).toBeFocused()
  await page.keyboard.press("Escape")
  await page.keyboard.press("ArrowRight")
  await page.keyboard.press("ArrowRight")
  await expect(page.getByRole("navigation", { name: "Installed capabilities" })).toBeVisible()
  await page.keyboard.press("Control+k")
  await page.getByTestId("composer-input").fill("/debug.reset")
  await Promise.all([page.waitForEvent("load"), page.keyboard.press("Enter")])
  await expect(page.locator(".guide-shell")).toHaveAttribute("data-step", "0")
  await expect(page.getByTestId("composer-input")).toBeHidden()
  await expect(page.getByRole("navigation", { name: "Installed capabilities" })).toBeHidden()
  await page.keyboard.press("Control+k")
  await expect(page.getByTestId("composer-input")).toHaveValue("")
  await expect(page.locator('.smithers-chat-message[data-role="user"]')).toHaveCount(0)
  await page.keyboard.press("Escape")
  await page.reload()
  await expect(page.locator(".guide-shell")).toHaveAttribute("data-step", "0")
})
