/**
 * Versioned static-analysis rules shared by the scorer and future lint.
 * Keep command exemptions beside mutations so additions cannot silently
 * weaken the git/read boundary.
 */
export const sideEffectRules = Object.freeze({
    version: 4,
    networkMutationMethods: Object.freeze(["POST", "PUT", "PATCH", "DELETE"]),
    readMethods: Object.freeze(["GET", "HEAD", "OPTIONS"]),
    shell: Object.freeze({
        exemptExecutables: Object.freeze(["git", "jj"]),
        ghReadVerbs: Object.freeze(["view", "list", "status", "checks", "diff"]),
        ghMutations: Object.freeze([
            Object.freeze(["agent-task", "create"]),
            Object.freeze(["alias", "delete"]),
            Object.freeze(["alias", "import"]),
            Object.freeze(["alias", "set"]),
            Object.freeze(["auth", "login"]),
            Object.freeze(["auth", "logout"]),
            Object.freeze(["auth", "refresh"]),
            Object.freeze(["auth", "setup-git"]),
            Object.freeze(["auth", "switch"]),
            Object.freeze(["cache", "delete"]),
            Object.freeze(["codespace", "cp"]),
            Object.freeze(["codespace", "create"]),
            Object.freeze(["codespace", "delete"]),
            Object.freeze(["codespace", "edit"]),
            Object.freeze(["codespace", "ports", "forward"]),
            Object.freeze(["codespace", "ports", "visibility"]),
            Object.freeze(["codespace", "rebuild"]),
            Object.freeze(["codespace", "stop"]),
            Object.freeze(["config", "clear-cache"]),
            Object.freeze(["config", "set"]),
            Object.freeze(["discussion", "comment"]),
            Object.freeze(["discussion", "create"]),
            Object.freeze(["discussion", "edit"]),
            Object.freeze(["extension", "install"]),
            Object.freeze(["extension", "remove"]),
            Object.freeze(["extension", "upgrade"]),
            Object.freeze(["pr", "create"]),
            Object.freeze(["pr", "merge"]),
            Object.freeze(["pr", "close"]),
            Object.freeze(["pr", "comment"]),
            Object.freeze(["pr", "edit"]),
            Object.freeze(["pr", "lock"]),
            Object.freeze(["pr", "ready"]),
            Object.freeze(["pr", "reopen"]),
            Object.freeze(["pr", "revert"]),
            Object.freeze(["pr", "review"]),
            Object.freeze(["pr", "unlock"]),
            Object.freeze(["pr", "update-branch"]),
            Object.freeze(["issue", "create"]),
            Object.freeze(["issue", "close"]),
            Object.freeze(["issue", "comment"]),
            Object.freeze(["issue", "delete"]),
            Object.freeze(["issue", "develop"]),
            Object.freeze(["issue", "edit"]),
            Object.freeze(["issue", "lock"]),
            Object.freeze(["issue", "pin"]),
            Object.freeze(["issue", "reopen"]),
            Object.freeze(["issue", "transfer"]),
            Object.freeze(["issue", "unlock"]),
            Object.freeze(["issue", "unpin"]),
            Object.freeze(["release", "create"]),
            Object.freeze(["release", "delete"]),
            Object.freeze(["release", "delete-asset"]),
            Object.freeze(["release", "edit"]),
            Object.freeze(["release", "upload"]),
            Object.freeze(["repo", "archive"]),
            Object.freeze(["repo", "create"]),
            Object.freeze(["repo", "delete"]),
            Object.freeze(["repo", "edit"]),
            Object.freeze(["repo", "fork"]),
            Object.freeze(["repo", "rename"]),
            Object.freeze(["repo", "set-default"]),
            Object.freeze(["repo", "sync"]),
            Object.freeze(["repo", "unarchive"]),
            Object.freeze(["repo", "autolink", "create"]),
            Object.freeze(["repo", "autolink", "delete"]),
            Object.freeze(["repo", "deploy-key", "add"]),
            Object.freeze(["repo", "deploy-key", "delete"]),
            Object.freeze(["gist", "create"]),
            Object.freeze(["gist", "delete"]),
            Object.freeze(["gist", "edit"]),
            Object.freeze(["gist", "rename"]),
            Object.freeze(["project", "close"]),
            Object.freeze(["project", "copy"]),
            Object.freeze(["project", "create"]),
            Object.freeze(["project", "delete"]),
            Object.freeze(["project", "edit"]),
            Object.freeze(["project", "field-create"]),
            Object.freeze(["project", "field-delete"]),
            Object.freeze(["project", "item-add"]),
            Object.freeze(["project", "item-archive"]),
            Object.freeze(["project", "item-create"]),
            Object.freeze(["project", "item-delete"]),
            Object.freeze(["project", "item-edit"]),
            Object.freeze(["project", "link"]),
            Object.freeze(["project", "mark-template"]),
            Object.freeze(["project", "unlink"]),
            Object.freeze(["workflow", "disable"]),
            Object.freeze(["workflow", "enable"]),
            Object.freeze(["workflow", "run"]),
            Object.freeze(["run", "cancel"]),
            Object.freeze(["run", "delete"]),
            Object.freeze(["run", "rerun"]),
            Object.freeze(["secret", "delete"]),
            Object.freeze(["secret", "set"]),
            Object.freeze(["variable", "delete"]),
            Object.freeze(["variable", "set"]),
            Object.freeze(["label", "create"]),
            Object.freeze(["label", "delete"]),
            Object.freeze(["label", "edit"]),
            Object.freeze(["label", "clone"]),
            Object.freeze(["ssh-key", "add"]),
            Object.freeze(["ssh-key", "delete"]),
            Object.freeze(["gpg-key", "add"]),
            Object.freeze(["gpg-key", "delete"]),
            Object.freeze(["skill", "install"]),
            Object.freeze(["skill", "publish"]),
            Object.freeze(["skill", "update"]),
        ]),
        commandMutations: Object.freeze([
            Object.freeze({ executable: "wrangler", verbs: Object.freeze(["deploy", "publish", "delete"]), dryRunFlags: Object.freeze(["--dry-run"]) }),
            Object.freeze({ executable: "kubectl", verbs: Object.freeze(["apply", "create", "delete", "patch", "replace", "rollout", "scale", "set"]), dryRunFlags: Object.freeze(["--dry-run"]) }),
            Object.freeze({ executable: "terraform", verbs: Object.freeze(["apply", "destroy", "import", "taint"]) }),
            Object.freeze({ executable: "helm", verbs: Object.freeze(["install", "upgrade", "rollback", "uninstall"]), dryRunFlags: Object.freeze(["--dry-run"]) }),
            Object.freeze({ executable: "npm", verbs: Object.freeze(["publish", "unpublish", "deprecate"]), dryRunFlags: Object.freeze(["--dry-run"]) }),
            Object.freeze({ executable: "docker", verbs: Object.freeze(["push"]) }),
            Object.freeze({ executable: "fly", verbs: Object.freeze(["deploy", "release"]) }),
            Object.freeze({ executable: "flyctl", verbs: Object.freeze(["deploy", "release"]) }),
        ]),
        awsMutationVerbs: Object.freeze([
            "create", "delete", "put", "update", "upload", "copy", "move", "publish",
            "send", "start", "stop", "terminate", "register", "deregister", "invoke",
        ]),
        gcloudMutationVerbs: Object.freeze([
            "create", "delete", "deploy", "update", "publish", "submit", "write",
            "add-iam-policy-binding", "remove-iam-policy-binding",
        ]),
    }),
    sdkMutationPaths: Object.freeze([
        Object.freeze({ id: "slack-message", pattern: /(?:^|\.)chat\.postMessage$/i }),
        Object.freeze({ id: "slack-delete", pattern: /(?:^|\.)chat\.delete$/i }),
        Object.freeze({ id: "email-send", pattern: /(?:^|\.)(?:sendMail|sendEmail)$/i }),
        Object.freeze({ id: "twilio-message", pattern: /(?:^|\.)messages\.create$/i }),
        Object.freeze({ id: "telegram-message", pattern: /(?:^|\.)(?:sendMessage|sendPhoto|sendDocument)$/i }),
        Object.freeze({ id: "discord-message", pattern: /(?:^|\.)(?:sendDiscordMessage|createMessage)$/i }),
        Object.freeze({ id: "social-post", pattern: /(?:^|\.)(?:tweet|createTweet|postTweet|createPost|publishPost)$/i }),
        Object.freeze({ id: "stripe-payment", pattern: /(?:^|\.)(?:charges|paymentIntents|refunds|customers|subscriptions)\.(?:create|update|cancel)$/i }),
        Object.freeze({ id: "stripe-refund", pattern: /(?:^|\.)(?:createRefund|refundPayment)$/i }),
        Object.freeze({ id: "object-storage-write", pattern: /(?:^|\.)(?:putObject|deleteObject|uploadObject|uploadFile)$/i }),
        Object.freeze({ id: "webhook-registration", pattern: /(?:^|\.)(?:createWebhook|registerWebhook|deleteWebhook)$/i }),
        Object.freeze({ id: "cron-registration", pattern: /(?:^|\.)(?:createCron|registerCron|scheduleJob|cancelJob)$/i }),
        Object.freeze({ id: "pagerduty-event", pattern: /(?:^|\.)(?:triggerIncident|resolveIncident|enqueueEvent)$/i }),
        Object.freeze({ id: "sentry-event", pattern: /(?:^|\.)(?:captureException|captureMessage|captureEvent)$/i }),
    ]),
    databaseReceiverPattern: /(?:^|\.)(?:db|database|prisma|supabase|dynamo|firestore|collection|table|redis|sql)(?:\.|$)/i,
    databaseMutationMethods: Object.freeze([
        "insert", "insertOne", "insertMany", "update", "updateOne", "updateMany",
        "upsert", "delete", "deleteOne", "deleteMany", "remove", "set", "create",
    ]),
    filesystemWriteCalls: Object.freeze([
        "writeFile", "writeFileSync", "appendFile", "appendFileSync", "truncate",
        "truncateSync", "rename", "renameSync", "copyFile", "copyFileSync", "mkdir",
        "mkdirSync", "rm", "rmSync", "unlink", "unlinkSync",
    ]),
    filesystemTwoPathCalls: Object.freeze([
        "rename", "renameSync", "copyFile", "copyFileSync",
    ]),
    reversalVerbs: Object.freeze({
        callRules: Object.freeze([
            Object.freeze({
                effectClass: "slack-message",
                effects: Object.freeze([/(?:^|\.)chat\.postMessage$/i]),
                reversals: Object.freeze([/(?:^|\.)chat\.delete$/i]),
                resourceKeys: Object.freeze(["channel"]),
            }),
            Object.freeze({
                effectClass: "twilio-message",
                effects: Object.freeze([/(?:^|\.)messages\.create$/i]),
                reversals: Object.freeze([/(?:^|\.)messages\.(?:delete|remove)$/i]),
                resourceKeys: Object.freeze(["accountSid", "serviceSid"]),
            }),
            Object.freeze({
                effectClass: "telegram-message",
                effects: Object.freeze([/(?:^|\.)(?:sendMessage|sendPhoto|sendDocument)$/i]),
                reversals: Object.freeze([/(?:^|\.)deleteMessage$/i]),
                resourceKeys: Object.freeze(["chatId", "chat_id"]),
            }),
            Object.freeze({
                effectClass: "discord-message",
                effects: Object.freeze([/(?:^|\.)(?:sendDiscordMessage|createMessage)$/i]),
                reversals: Object.freeze([/(?:^|\.)(?:deleteDiscordMessage|deleteMessage)$/i]),
                resourceKeys: Object.freeze(["channelId", "channel_id"]),
            }),
            Object.freeze({
                effectClass: "social-post",
                effects: Object.freeze([/(?:^|\.)(?:tweet|createTweet|postTweet|createPost|publishPost)$/i]),
                reversals: Object.freeze([/(?:^|\.)(?:deleteTweet|deletePost|unpublishPost)$/i]),
                resourceKeys: Object.freeze(["accountId", "pageId", "profileId"]),
            }),
            Object.freeze({
                effectClass: "stripe-charge",
                effects: Object.freeze([/(?:^|\.)(?:charges\.create|createCharge)$/i]),
                reversals: Object.freeze([/(?:^|\.)(?:refunds\.create|createRefund|refundPayment)$/i]),
            }),
            Object.freeze({
                effectClass: "stripe-payment-intent",
                effects: Object.freeze([/(?:^|\.)paymentIntents\.create$/i]),
                reversals: Object.freeze([
                    /(?:^|\.)paymentIntents\.cancel$/i,
                    /(?:^|\.)(?:refunds\.create|createRefund|refundPayment)$/i,
                ]),
            }),
            Object.freeze({
                effectClass: "stripe-refund",
                effects: Object.freeze([/(?:^|\.)(?:refunds\.create|createRefund|refundPayment)$/i]),
                reversals: Object.freeze([/(?:^|\.)refunds\.cancel$/i]),
            }),
            Object.freeze({
                effectClass: "object-storage-write",
                effects: Object.freeze([/(?:^|\.)(?:putObject|uploadObject|uploadFile)$/i]),
                reversals: Object.freeze([/(?:^|\.)(?:deleteObject|deleteFile|removeObject)$/i]),
                resourceKeys: Object.freeze(["Bucket", "bucket", "Key", "key", "path"]),
            }),
            Object.freeze({
                effectClass: "webhook-registration",
                effects: Object.freeze([/(?:^|\.)(?:createWebhook|registerWebhook)$/i]),
                reversals: Object.freeze([/(?:^|\.)(?:deleteWebhook|unregisterWebhook)$/i]),
                resourceKeys: Object.freeze(["url", "path", "hookId", "webhookId", "id"]),
            }),
            Object.freeze({
                effectClass: "cron-registration",
                effects: Object.freeze([/(?:^|\.)(?:createCron|registerCron|scheduleJob)$/i]),
                reversals: Object.freeze([/(?:^|\.)(?:deleteCron|unregisterCron|cancelJob|unscheduleJob)$/i]),
                resourceKeys: Object.freeze(["name", "jobId", "cronId", "id"]),
            }),
            Object.freeze({
                effectClass: "pagerduty-incident",
                effects: Object.freeze([/(?:^|\.)triggerIncident$/i]),
                reversals: Object.freeze([/(?:^|\.)resolveIncident$/i]),
            }),
            Object.freeze({
                effectClass: "github-issue-create",
                effects: Object.freeze([/(?:^|\.)issues\.create$/i]),
                reversals: Object.freeze([/(?:^|\.)issues\.(?:delete|close)$/i]),
                resourceKeys: Object.freeze(["owner", "repo"]),
            }),
            Object.freeze({
                effectClass: "github-issue-close",
                effects: Object.freeze([/(?:^|\.)issues\.close$/i]),
                reversals: Object.freeze([/(?:^|\.)issues\.reopen$/i]),
                resourceKeys: Object.freeze(["owner", "repo", "issue_number", "issueNumber"]),
            }),
            Object.freeze({
                effectClass: "package-publish",
                effects: Object.freeze([/(?:^|\.)(?:publish|publishPackage)$/i]),
                reversals: Object.freeze([/(?:^|\.)(?:unpublish|deprecate|unpublishPackage)$/i]),
                resourceKeys: Object.freeze(["name", "package", "packageName"]),
            }),
        ]),
        shellRules: Object.freeze([
            Object.freeze({ effectClass: "github-issue-create", effects: Object.freeze(["gh issue create"]), reversals: Object.freeze(["gh issue close", "gh issue delete"]) }),
            Object.freeze({ effectClass: "github-issue-close", effects: Object.freeze(["gh issue close"]), reversals: Object.freeze(["gh issue reopen"]) }),
            Object.freeze({ effectClass: "github-pr-create", effects: Object.freeze(["gh pr create"]), reversals: Object.freeze(["gh pr close"]) }),
            Object.freeze({ effectClass: "github-pr-close", effects: Object.freeze(["gh pr close"]), reversals: Object.freeze(["gh pr reopen"]) }),
            Object.freeze({ effectClass: "github-pr-merge", effects: Object.freeze(["gh pr merge"]), reversals: Object.freeze(["gh pr revert"]) }),
            Object.freeze({ effectClass: "github-release", effects: Object.freeze(["gh release create"]), reversals: Object.freeze(["gh release delete"]) }),
            Object.freeze({ effectClass: "kubernetes-resource", effects: Object.freeze(["kubectl apply", "kubectl create"]), reversals: Object.freeze(["kubectl delete"]), matchResource: true }),
            Object.freeze({ effectClass: "terraform-apply", effects: Object.freeze(["terraform apply"]), reversals: Object.freeze(["terraform destroy"]) }),
            Object.freeze({ effectClass: "helm-release", effects: Object.freeze(["helm install", "helm upgrade"]), reversals: Object.freeze(["helm uninstall", "helm rollback"]) }),
            Object.freeze({ effectClass: "package-publish", effects: Object.freeze(["npm publish"]), reversals: Object.freeze(["npm unpublish", "npm deprecate"]) }),
            Object.freeze({ effectClass: "worker-publish", effects: Object.freeze(["wrangler deploy", "wrangler publish"]), reversals: Object.freeze(["wrangler delete"]) }),
        ]),
        databaseCreationVerbs: Object.freeze([
            "insert", "insertOne", "insertMany", "update", "updateOne", "updateMany",
            "upsert", "set", "create",
        ]),
        databaseReversalVerbs: Object.freeze([
            "delete", "deleteOne", "deleteMany", "remove",
        ]),
        filesystemCreationVerbs: Object.freeze([
            "writeFile", "writeFileSync", "appendFile", "appendFileSync", "copyFile",
            "copyFileSync", "mkdir", "mkdirSync", "Bun.write",
        ]),
        filesystemReversalVerbs: Object.freeze([
            "rm", "rmSync", "unlink", "unlinkSync",
        ]),
        effectCreationVerbPattern: /(?:^|\.)(?:postMessage|sendMessage|sendMail|sendEmail|create|insert|insertOne|insertMany|putObject|uploadObject|uploadFile|publish|deploy)$/i,
        unknownDeleteVerbPattern: /(?:^|\.)(?:delete|deleteOne|deleteMany|remove|rm|rmSync|unlink|unlinkSync|destroy|unpublish|deprecate)$/i,
    }),
    existenceCheckPattern: /(?:^|\.)(?:exists|find|get|head|lookup|retrieve|search|list|describe|stat)[A-Za-z0-9_]*$/i,
});
