/**
 * The generated theme files, against the generator that writes them.
 *
 * `src/themes/*.ts` (fucory excepted) are emitted by
 * `scripts/generate-theme-registry.ts`. Two things can drift, and a reader of
 * the files alone cannot see either:
 *
 * 1. A hand edit to a generated file survives until the next regeneration
 *    silently reverts it. The extension on the emitted import specifier is
 *    exactly that case: `apps/review` loads this package under Node ESM, where
 *    a relative specifier without `.ts` does not resolve, and a fix applied to
 *    the files instead of to the generator lasts until someone re-runs it.
 * 2. The upstream themes move and the checked-in registry stops matching what
 *    the generator would write from them.
 *
 * The generator's `--check` mode compares its own output to the files byte for
 * byte and writes nothing, so this test is that comparison.
 */
import { describe, expect, test } from "bun:test";
import { spawnSync } from "node:child_process";
import { readdirSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { nodeExecutable } from "./nodeBinary.ts";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repositoryRoot = resolve(packageRoot, "../..");
const themesDir = join(packageRoot, "src/themes");

describe("the generated theme registry", () => {
  test("matches what the generator writes today, byte for byte", () => {
    // Node, not the Bun that runs this suite: the generator is a Node script,
    // and running it under a different runtime would compare this package
    // against output nobody regenerates it with.
    const result = spawnSync(
      nodeExecutable,
      ["--experimental-strip-types", "scripts/generate-theme-registry.ts", "--check"],
      { cwd: repositoryRoot, encoding: "utf8" },
    );
    expect(`${result.stdout ?? ""}${result.stderr ?? ""}`.trim()).toBe("");
    expect(result.status).toBe(0);
  }, 120_000);

  test("imports the theme type with the extension Node ESM resolves", () => {
    // Generated files only. A hand-written theme's specifiers are that file's
    // own; only these are rewritten by a regeneration.
    const generated = readdirSync(themesDir)
      .filter((file) => file.endsWith(".ts"))
      .map((file) => [file, readFileSync(join(themesDir, file), "utf8")] as const)
      .filter(([, source]) => source.startsWith("// Generated by scripts/generate-theme-registry.ts"));
    expect(generated.length).toBe(7);
    expect(generated.filter(([, source]) => source.includes('from "../SmithersTheme"')).map(([file]) => file))
      .toEqual([]);
  });
});
