import { A as AgentCliEventLike$1, H as HerdrRunSurface$1, a as HerdrRunSurfaceOptions$1, b as HijackLaunchSpec$1, c as HijackPaneContext$1, d as HijackPaneResult$1, S as SmithersEventLike$1 } from './createHerdrRunSurface-DYYanfXR.js';
export { e as HERDR_SURFACE_EVENT_TYPES, O as OUTCOME_MARKERS, f as createHerdrRunSurface, l as launchHijackPane, o as openTabPane, g as outcomeMarkerFor, s as shortNodeId, h as shortRunId, i as stripOutcomeMarker, w as workspaceLabelMatches } from './createHerdrRunSurface-DYYanfXR.js';
import { H as HerdrAgentInfo$1, a as HerdrAgentListResult$1, b as HerdrAgentStartParams$1, c as HerdrAgentStartResult$1, d as HerdrAgentState$1, e as HerdrAgentStatus$1, f as HerdrClient$1, g as HerdrClientOptions$1, h as HerdrEvent$1, i as HerdrLogLevel$1, j as HerdrLogger$1, k as HerdrNotificationShowParams$1, l as HerdrNotificationShowResult$1, m as HerdrOkResult$1, n as HerdrOutputMatch$1, o as HerdrPaneInfo$1, p as HerdrPaneListParams$1, q as HerdrPaneListResult$1, r as HerdrPaneReadParams$1, s as HerdrPaneReadResult$1, t as HerdrPaneReadResultEnvelope$1, u as HerdrPaneReleaseAgentParams$1, v as HerdrPaneReportAgentParams$1, w as HerdrPaneReportAgentSessionParams$1, x as HerdrPaneReportMetadataParams$1, y as HerdrPaneWaitForOutputParams$1, z as HerdrPaneWaitForOutputResult$1, A as HerdrPingOptions$1, B as HerdrPong$1, C as HerdrReadFormat$1, D as HerdrReadSource$1, E as HerdrServerCapabilities$1, F as HerdrSplitDirection$1, G as HerdrSubscription$1, I as HerdrSubscriptionHandle$1, J as HerdrTabInfo$1, K as HerdrWorkspaceCloseParams$1, L as HerdrWorkspaceCreateParams$1, M as HerdrWorkspaceCreateResult$1, N as HerdrWorkspaceInfo$1, O as HerdrWorkspaceListResult$1, P as HerdrWorkspaceRenameParams$1, Q as HerdrWorkspaceRenameResult$1 } from './HerdrClientOptions-CfjzN_zB.js';
export { HERDR_PROTOCOL } from './HERDR_PROTOCOL.js';
export { HerdrError } from './HerdrError.js';
export { createHerdrClient, normalizeHerdrEventName } from './createHerdrClient.js';
export { DEFAULT_SOFT_PIN_SLOTS, gateTabLabel, isLikelyWorkerNodeId, isPinnedNodeId, resolveAutoOpenPolicy, resolveSoftPinSlots, shouldAutoOpenDetailTab, updateSoftPinSet } from './cockpitPolicy.js';
export { DEFAULT_HARNESS_CANDIDATES, detectHarnessCommand, isExecutableOnPath, resolveHarnessCommand, shouldDockIntoCurrentPane, shouldSplitCockpit } from './cockpitLayout.js';
export { DEFAULT_DIGEST_INTERVAL_MS, buildDigestBlock, buildFleetStrip, digestSignature, formatClockHm, formatElapsed } from './digest.js';
export { defaultSessionNameForRun, isStubWorkspaceLabel, sessionAttachHint, stubWorkspaceLabel } from './sessionLifecycle.js';
export { resolveSocketPath, sessionSocketPath } from './resolveSocketPath.js';

type HerdrClientOptions = HerdrClientOptions$1;
type HerdrPingOptions = HerdrPingOptions$1;
type HerdrClient = HerdrClient$1;
type HerdrLogger = HerdrLogger$1;
type HerdrLogLevel = HerdrLogLevel$1;
type HerdrEvent = HerdrEvent$1;
type HerdrSubscription = HerdrSubscription$1;
type HerdrSubscriptionHandle = HerdrSubscriptionHandle$1;
type HerdrAgentState = HerdrAgentState$1;
type HerdrAgentStatus = HerdrAgentStatus$1;
type HerdrReadSource = HerdrReadSource$1;
type HerdrReadFormat = HerdrReadFormat$1;
type HerdrSplitDirection = HerdrSplitDirection$1;
type HerdrOutputMatch = HerdrOutputMatch$1;
type HerdrPong = HerdrPong$1;
type HerdrServerCapabilities = HerdrServerCapabilities$1;
type HerdrWorkspaceInfo = HerdrWorkspaceInfo$1;
type HerdrTabInfo = HerdrTabInfo$1;
type HerdrPaneInfo = HerdrPaneInfo$1;
type HerdrAgentInfo = HerdrAgentInfo$1;
type HerdrPaneReadResult = HerdrPaneReadResult$1;
type HerdrWorkspaceCreateParams = HerdrWorkspaceCreateParams$1;
type HerdrWorkspaceCreateResult = HerdrWorkspaceCreateResult$1;
type HerdrWorkspaceCloseParams = HerdrWorkspaceCloseParams$1;
type HerdrWorkspaceRenameParams = HerdrWorkspaceRenameParams$1;
type HerdrWorkspaceRenameResult = HerdrWorkspaceRenameResult$1;
type HerdrWorkspaceListResult = HerdrWorkspaceListResult$1;
type HerdrOkResult = HerdrOkResult$1;
type HerdrAgentStartParams = HerdrAgentStartParams$1;
type HerdrAgentStartResult = HerdrAgentStartResult$1;
type HerdrAgentListResult = HerdrAgentListResult$1;
type HerdrPaneListParams = HerdrPaneListParams$1;
type HerdrPaneListResult = HerdrPaneListResult$1;
type HerdrPaneReportAgentParams = HerdrPaneReportAgentParams$1;
type HerdrPaneReportAgentSessionParams = HerdrPaneReportAgentSessionParams$1;
type HerdrPaneReleaseAgentParams = HerdrPaneReleaseAgentParams$1;
type HerdrPaneReportMetadataParams = HerdrPaneReportMetadataParams$1;
type HerdrPaneReadParams = HerdrPaneReadParams$1;
type HerdrPaneReadResultEnvelope = HerdrPaneReadResultEnvelope$1;
type HerdrPaneWaitForOutputParams = HerdrPaneWaitForOutputParams$1;
type HerdrPaneWaitForOutputResult = HerdrPaneWaitForOutputResult$1;
type HerdrNotificationShowParams = HerdrNotificationShowParams$1;
type HerdrNotificationShowResult = HerdrNotificationShowResult$1;
type HerdrRunSurfaceOptions = HerdrRunSurfaceOptions$1;
type HerdrRunSurface = HerdrRunSurface$1;
type SmithersEventLike = SmithersEventLike$1;
type AgentCliEventLike = AgentCliEventLike$1;
type HijackLaunchSpec = HijackLaunchSpec$1;
type HijackPaneContext = HijackPaneContext$1;
type HijackPaneResult = HijackPaneResult$1;

export type { AgentCliEventLike, HerdrAgentInfo, HerdrAgentListResult, HerdrAgentStartParams, HerdrAgentStartResult, HerdrAgentState, HerdrAgentStatus, HerdrClient, HerdrClientOptions, HerdrEvent, HerdrLogLevel, HerdrLogger, HerdrNotificationShowParams, HerdrNotificationShowResult, HerdrOkResult, HerdrOutputMatch, HerdrPaneInfo, HerdrPaneListParams, HerdrPaneListResult, HerdrPaneReadParams, HerdrPaneReadResult, HerdrPaneReadResultEnvelope, HerdrPaneReleaseAgentParams, HerdrPaneReportAgentParams, HerdrPaneReportAgentSessionParams, HerdrPaneReportMetadataParams, HerdrPaneWaitForOutputParams, HerdrPaneWaitForOutputResult, HerdrPingOptions, HerdrPong, HerdrReadFormat, HerdrReadSource, HerdrRunSurface, HerdrRunSurfaceOptions, HerdrServerCapabilities, HerdrSplitDirection, HerdrSubscription, HerdrSubscriptionHandle, HerdrTabInfo, HerdrWorkspaceCloseParams, HerdrWorkspaceCreateParams, HerdrWorkspaceCreateResult, HerdrWorkspaceInfo, HerdrWorkspaceListResult, HerdrWorkspaceRenameParams, HerdrWorkspaceRenameResult, HijackLaunchSpec, HijackPaneContext, HijackPaneResult, SmithersEventLike };
