#!/usr/bin/env node
/** Projects package-owned Model documentation into the repository site. */
import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { Package } from "../Package.ts"

const check = process.argv.includes("--check")
const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const repoRoot = join(packageRoot, "..", "..")
const read = (path) => readFileSync(path, "utf8")
const readOrEmpty = (path) => (existsSync(path) ? read(path) : "")

const ungutter = (block) => block.split("\n").map((line) => line.replace(/^\s*\* ?/, "")).join("\n")

const description = (body) => {
  const lines = []
  for (const line of body.split("\n")) {
    if (/^@\w+/.test(line.trim())) break
    lines.push(line)
  }
  return lines.join("\n").trim()
}

const delink = (value) => value.replace(/\{@link\s+([^}]+)\}/g, "`$1`")

// House style forbids an em-dash on a published page. Package JSDoc predates
// that rule, so a summary lifted from it is normalized here rather than by
// rewriting prose the compiler also reads.
const unemdash = (value) => value.replace(/\s*—\s*/g, ", ")

const paragraphs = (value) => {
  const blocks = []
  let current = []
  for (const line of value.split("\n")) {
    if (line.trim() === "") {
      if (current.length > 0) blocks.push(current.join(" "))
      current = []
    } else current.push(line.trim())
  }
  if (current.length > 0) blocks.push(current.join(" "))
  return blocks.join("\n\n")
}

const firstSentence = (value) => {
  const flat = delink(value).split("\n\n")[0].split("\n").join(" ")
  return (/^[\s\S]*?\.(?=\s|$)/.exec(flat)?.[0] ?? flat).trim()
}

const cell = (value) => unemdash(value).replaceAll("|", "\\|")

const moduleDoc = (source, name) => {
  const match = /\/\*\*((?:[^*]|\*(?!\/))*)\*\//.exec(source)
  if (match === null) throw new Error(`model docs: ${name} has no module JSDoc block`)
  return delink(description(ungutter(match[1])))
}

const exportedDocs = (source) => {
  const entries = []
  const pattern = /\/\*\*((?:[^*]|\*(?!\/))*)\*\/\s*\nexport (?:declare )?(type|const|class|interface|function) (\w+)/g
  for (let match = pattern.exec(source); match !== null; match = pattern.exec(source)) {
    const body = ungutter(match[1])
    const category = /@category (\S+)/.exec(body)?.[1]
    if (category === undefined) continue
    entries.push({
      name: match[3],
      declaration: match[2],
      category,
      summary: firstSentence(description(body))
    })
  }
  return entries
}

const manifest = JSON.parse(read(join(packageRoot, "package.json")))
if (manifest.name !== Package.name) throw new Error("model docs: Package.ts and package.json names differ")

const barrel = read(join(packageRoot, "src", "index.ts"))
const namespaces = [...barrel.matchAll(/export \* as (\w+) from "\.\/(\w+)\.ts"/g)].map((match) => ({
  namespace: match[1],
  module: match[2]
}))
if (namespaces.length === 0) throw new Error("model docs: the barrel re-exports no namespaces")

const modules = namespaces.map((entry) => {
  const source = read(join(packageRoot, "src", `${entry.module}.ts`))
  const exports = exportedDocs(source)
  if (exports.length === 0) throw new Error(`model docs: ${entry.module} has no documented exports`)
  // A type and its schema share one name on purpose; the table names each once.
  const seen = new Set()
  const unique = exports.filter((item) => (seen.has(item.name) ? false : seen.add(item.name)))
  return { ...entry, summary: firstSentence(moduleDoc(source, entry.module)), exports: unique }
})

const table = (exports) =>
  [
    "| Export | Kind | Summary |",
    "| --- | --- | --- |",
    ...exports.map((item) => `| \`${item.name}\` | ${item.category} | ${cell(item.summary)} |`)
  ].join("\n")

const sections = modules
  .map((entry) => `### \`${entry.namespace}\`\n\n${unemdash(entry.summary)}\n\n${table(entry.exports)}`)
  .join("\n\n")

const apiPage = `---
description: "${manifest.description}."
---

{/* Generated by \`node packages/model/scripts/docs.mjs\` from packages/model. Edit package sources, never this file. */}

# @smthrs/model

${unemdash(paragraphs(moduleDoc(barrel, "index")))}

${unemdash(read(join(packageRoot, Package.api.source)).trim())}

## Exports

Every namespace below is exported by the root entry point and is also
importable as \`@smthrs/model/<Namespace>\`.

${sections}
`

// A list, not a table: dprint aligns markdown table cells, and a generated
// table would drift against its own formatted output on every run.
const readmeBlock = modules
  .map((entry) =>
    `- **\`${entry.namespace}\`**: ${cell(entry.summary)}\n  ${
      entry.exports.map((item) => `\`${item.name}\``).join(", ")
    }`
  )
  .join("\n")

const regionStart = (name) => `<!-- generated:${name} start -->`
const regionEnd = (name) => `<!-- generated:${name} end -->`
const replaceRegion = (source, name, body) => {
  const start = source.indexOf(regionStart(name))
  const end = source.indexOf(regionEnd(name))
  if (start < 0 || end < 0 || end < start) throw new Error(`model docs: region ${name} is missing`)
  return `${source.slice(0, start)}${regionStart(name)}\n\n${body.trim()}\n\n${source.slice(end)}`
}

const outputs = new Map([
  [Package.api.target, apiPage],
  [Package.reference.target, apiPage]
])
for (const region of Package.regions) {
  const absolute = join(repoRoot, region.target)
  outputs.set(region.target, replaceRegion(read(absolute), region.region, readmeBlock))
}

const failures = []
for (const path of Package.references) {
  const content = read(join(repoRoot, path))
  if (!content.includes(Package.name) || !content.includes("/api/model")) {
    failures.push(`${path}: must reference ${Package.name} and /api/model`)
  }
}
for (const [path, content] of outputs) {
  if (content.includes("—")) failures.push(`${path}: generated content contains an em-dash`)
}

let drifted = false
for (const [path, content] of outputs) {
  const absolute = join(repoRoot, path)
  if (readOrEmpty(absolute) === content) continue
  drifted = true
  if (check) failures.push(`${path}: drifted; run node packages/model/scripts/docs.mjs`)
  else {
    writeFileSync(absolute, content)
    console.log(`wrote ${path}`)
  }
}

if (failures.length > 0) {
  for (const failure of failures) console.error(`✗ ${failure}`)
  process.exit(1)
}

console.log(
  check
    ? "✓ the model package documentation is current"
    : drifted
    ? "✓ model package documentation regenerated"
    : "✓ model package documentation already current"
)
