#!/usr/bin/env node
/**
 * Projects package-owned flow documentation into the repository site.
 *
 * Every published sentence about `@smthrs/flow` has one source inside the
 * package: the narrative in `docs/api.md`, the summary of each export in the
 * JSDoc above it, and the one-line description in `package.json`. This script
 * stitches those into `docs/pages/api/flow.md`. Run it with no arguments to
 * write the page, and with `--check` to fail when the committed page has
 * drifted from the sources.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { DocsManifest } from "../DocsManifest.ts"

const check = process.argv.includes("--check")
const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const sourceRoot = join(packageRoot, "src")
const repoRoot = join(packageRoot, "..", "..")
const read = (path) => readFileSync(path, "utf8")

const ungutter = (block) => block.split("\n").map((line) => line.replace(/^\s*\* ?/, "")).join("\n")

const description = (body) => {
  const lines = []
  for (const line of body.split("\n")) {
    if (/^@\w+/.test(line)) break
    lines.push(line)
  }
  return lines.join("\n").trim()
}

const delink = (value) => value.replace(/\{@link\s+(?:module:)?([^}]+)\}/g, "`$1`")

const firstSentence = (value) => {
  const flat = delink(value).split("\n\n")[0].split("\n").join(" ")
  return (/^[\s\S]*?\.(?=\s|$)/.exec(flat)?.[0] ?? flat).trim()
}

/** A table cell may not carry a pipe or a line break. */
const cell = (value) => value.replaceAll("|", "\\|").replace(/\s+/g, " ").trim()

/**
 * The namespaces the barrel publishes, in barrel order, each with the summary
 * written above its re-export.
 */
const namespaces = (barrel) => {
  const pattern = /\/\*\*((?:[^*]|\*(?!\/))*)\*\/\s*\nexport \* as (\w+) from "\.\/(.+?)"/g
  const found = []
  for (let match = pattern.exec(barrel); match !== null; match = pattern.exec(barrel)) {
    found.push({
      name: match[2],
      summary: firstSentence(description(ungutter(match[1]))),
      entry: match[3]
    })
  }
  return found
}

/** The module files one namespace is assembled from, following its barrel. */
const modulesOf = (entry) => {
  const absolute = join(sourceRoot, entry)
  if (!entry.endsWith("/index.ts")) return [absolute]
  const directory = dirname(absolute)
  return [...read(absolute).matchAll(/export \* (?:as \w+ )?from "\.\/(.+?)"/g)]
    .map((match) => join(directory, match[1]))
}

/** Every export in one module that carries an `@category` tag, in file order. */
const exportedDocs = (source) => {
  const entries = []
  const pattern =
    /\/\*\*((?:[^*]|\*(?!\/))*)\*\/\s*\nexport (?:declare )?(type|const|class|interface|function|abstract class) (\w+)/g
  for (let match = pattern.exec(source); match !== null; match = pattern.exec(source)) {
    const body = ungutter(match[1])
    const category = /@category (\S+)/.exec(body)?.[1]
    if (category === undefined) continue
    entries.push({
      name: match[3],
      declaration: match[2],
      category,
      summary: firstSentence(description(body))
    })
  }
  return entries
}

const manifest = JSON.parse(read(join(packageRoot, "package.json")))
if (manifest.name !== DocsManifest.name) throw new Error("flow docs: DocsManifest.ts and package.json names differ")

const barrel = read(join(sourceRoot, "index.ts"))
const published = namespaces(barrel)
if (published.length === 0) throw new Error("flow docs: the barrel publishes no namespaces")

const sections = []
let documented = 0
for (const namespace of published) {
  const exports = modulesOf(namespace.entry).flatMap((file) => exportedDocs(read(file)))
  if (exports.length === 0) throw new Error(`flow docs: ${namespace.name} documents no exports`)
  documented += exports.length
  sections.push(
    [
      `### \`${namespace.name}\``,
      "",
      namespace.summary,
      "",
      "| Export | Kind | Category | Summary |",
      "| --- | --- | --- | --- |",
      ...exports.map((entry) =>
        `| \`${entry.name}\` | ${entry.declaration} | ${entry.category} | ${cell(entry.summary)} |`
      )
    ].join("\n")
  )
}

const apiPage = `---
description: "${manifest.description}."
---

{/* Generated by \`node packages/flow/scripts/docs.mjs\` from packages/flow. Edit package sources, never this file. */}

# @smthrs/flow

${read(join(packageRoot, DocsManifest.api.source)).trim()}

## Exports

The tables below are generated from the JSDoc above each exported declaration, so every export the
barrel publishes with an \`@category\` tag appears here. ${documented} declarations across
${published.length} namespaces.

${sections.join("\n\n")}
`

const regionStart = (name) => `{/* generated:${name} start */}`
const regionEnd = (name) => `{/* generated:${name} end */}`

/** Replaces the body between one page's region markers, keeping the markers. */
const replaceRegion = (source, name, body) => {
  const start = source.indexOf(regionStart(name))
  const end = source.indexOf(regionEnd(name))
  if (start < 0 || end < 0 || end < start) throw new Error(`flow docs: region ${name} is missing`)
  return `${source.slice(0, start)}${regionStart(name)}\n\n${body.trim()}\n\n${source.slice(end)}`
}

const outputs = new Map([[DocsManifest.api.target, apiPage]])
for (const snippet of DocsManifest.snippets) {
  const current = outputs.get(snippet.target) ?? read(join(repoRoot, snippet.target))
  outputs.set(snippet.target, replaceRegion(current, snippet.region, read(join(packageRoot, snippet.source))))
}

const failures = []

/**
 * The suite count `docs/pages/api-tests.md` publishes for this package.
 *
 * The inventory table is shared with every other package and dprint aligns its
 * columns, so a generator that owned one cell would fight the formatter. The
 * number is gated instead of generated: the row has to agree with the test
 * files on disk, so the count cannot drift the way it did when the page claimed
 * twelve suites for a package that had twenty-eight.
 */
const suites = readdirSync(join(packageRoot, "test")).filter((entry) => entry.endsWith(".test.ts"))
const inventory = outputs.get("docs/pages/api-tests.md") ?? read(join(repoRoot, "docs/pages/api-tests.md"))
const row = /^\| \[`@smthrs\/flow`]\(\/api\/flow\)\s*\|\s*(\d+)\s*\|/m.exec(inventory)
if (row === null) failures.push("docs/pages/api-tests.md: the @smthrs/flow inventory row is missing")
else if (Number(row[1]) !== suites.length) {
  failures.push(
    `docs/pages/api-tests.md: the @smthrs/flow inventory row says ${row[1]} suites, and the package has ${suites.length}`
  )
}
for (const path of DocsManifest.references) {
  const content = read(join(repoRoot, path))
  if (!content.includes(DocsManifest.name) || !content.includes("/api/flow")) {
    failures.push(`${path}: must reference ${DocsManifest.name} and /api/flow`)
  }
}
for (const [path, content] of outputs) {
  if (content.includes("—")) failures.push(`${path}: generated content contains an em-dash`)
}

let drifted = false
for (const [path, content] of outputs) {
  const absolute = join(repoRoot, path)
  if (read(absolute) === content) continue
  drifted = true
  if (check) failures.push(`${path}: drifted; run node packages/flow/scripts/docs.mjs`)
  else {
    writeFileSync(absolute, content)
    console.log(`wrote ${path}`)
  }
}

if (failures.length > 0) {
  for (const failure of failures) console.error(`✗ ${failure}`)
  process.exit(1)
}

console.log(
  check
    ? "✓ the flow package documentation is current"
    : drifted
    ? "✓ flow package documentation regenerated"
    : "✓ flow package documentation already current"
)
